### ISSUE TITLE
NullReferenceException in Reko.Analysis.SsaTransform.IdentifierTransformer.InsertAfterDefinition for Win16

### ISSUE THREAD

**Issue by blindmatrix** [uxmal/reko#1000]
Running reko (built from master 409c4f2c8b0afdfb1d2353af2f375b976cb0e142) I get a NullReferenceException during "Analyze dataflow" for Bang! Bang!. I only opened in the WindowsDecompiler and clicked "Finish Decompilation".

stmBefore is null when entering InsertAfterDefinition.

I got the shareware of Bang! Bang! from https://www.classicdosgames.com/game/Bang!_Bang!.html

**Comment by uxmal** [comment]
I'm no longer seeing that crash. There is one happening later in the type inference phase, but that's being tracked in a separate issue. I'm closing this now, but if you see the same error feel free to reopen.
