### ISSUE TITLE
After a 2 day decompile attempt on a 2 GB sized EXE... Structure analysis stopped making progress, quitting...

### ISSUE THREAD

**Issue by SingeStheos** [uxmal/reko#1026]
Please. PLEASE. TELL ME THERES SOME HOPE FOR MY DECOMPILE.

**Comment by uxmal** [comment]
That message is harmless. It's stating that progress couldn't be made on a particular procedure reducing it from a "soup" of basic blocks to structured high-level language. In such cases Reko will stop trying to reduce, and continues with the next procedure.

**Comment by SingeStheos** [comment]
Reko didnt give me the option to continue and I have no idea where it
outputs the decompile, if it did. Can I have a general location for the
Win64 version?

**Comment by uxmal** [comment]
If the full path to the binary is `/home/user/mybinary`, reko will create a subfolder `/home/user/mybinanary.reko` where the outputs are stored.
