### ISSUE TITLE
[MacOS] Drivers are not decompiled

### ISSUE THREAD

**Issue by claunia** [uxmal/reko#1031]
Drivers store the code in a `DRVR` resource with a different format (as seen in Inside Macintosh: Devices).

**Comment by uxmal** [comment]
Thanks for reporting this. Is there any chance you can provide such a device driver?

**Comment by claunia** [comment]
Sure.

[MD Driver.rsrc.zip](https://github.com/uxmal/reko/files/6426755/MD.Driver.rsrc.zip)

**Comment by claunia** [comment]
Please note that the attached driver loads as an extension, contrary to other drivers.

Drivers can be in ROM (like in a Macintosh II NuBus card -format known-, or the System ROM -format not really known-), inside the System file (as several `DRVR` resources inside) or as an extension (with an `INIT` resource that tells how to load it, see #1032).

[Inside Macintosh: Device Manager](http://mirror.informatimago.com/next/developer.apple.com/documentation/mac/Devices/Devices-10.html)

**Comment by uxmal** [comment]
@claunia : the sample you provided contains a `DRVR` resource whose first few bytes are:
```
00100DF8                         60 00 41 EE 5F 00 00 00         `.A._...
00100E00 00 00 00 00 00 84 00 9C 00 AC 00 C8 00 F4 07 2E ................
00100E10 53 6F 6E 79 4D 44 01 12 4D 44 20 44 41 54 41    SonyMD..MD DATA
```
The `60 00 41 EE` is a relative jump to code in the resource, which looks like a valid procedure entry prolog. Following the relative jump, I see the device header as described in the documentation at http://mirror.informatimago.com/next/developer.apple.com/documentation/mac/Devices/Devices-14.html. However, the documentation makes no mention of the relative jump or what the code the jump is pointing to may be. Is it safe to assume that all `DRVR` resources will have this jump? 

Please confirm that the new code in commit beecb29 is behaving as you expect it.

**Comment by claunia** [comment]
It's lookin correct, I'll check other drivers asap.

**Comment by claunia** [comment]
ok I checked other drivers, and the answer is no. I'll try to prepare a pack of drivers for the weekend.
