### ISSUE TITLE
[MacOS] Extensions are not decompiled

### ISSUE THREAD

**Issue by claunia** [uxmal/reko#1032]
Extensions store the code in an `INIT` resource as described in the [Start Manager](http://mirror.informatimago.com/next/developer.apple.com/documentation/mac/OSUtilities/OSUtilities-188.html#HEADING188-0)

[MD File System.rsrc.zip](https://github.com/uxmal/reko/files/6426770/MD.File.System.rsrc.zip)

**Comment by claunia** [comment]
Please note that the `INIT` resource usually says "hey the code is in this other resource" so that would need to be parsed as a procedure declaration, because such "other resource" changes with the file (should be unique in a single system).

**Comment by uxmal** [comment]
Reko now detects the `INIT` resource and disassembles it. As you note, it doesn't find all executable code automatically, so you need to give the decompiler a hint on where the code is in the "other resource".
