### ISSUE TITLE
Showing "Open As" window after project file loading failure is useless

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#1048]
It is good to show "Open As" window when `Reko` failed to load binary. But it should not be opened when
project file can't be loaded.
![изображение](https://user-images.githubusercontent.com/13188041/120674280-60f53100-c4ad-11eb-92d8-20f6c397f277.png)

**Comment by uxmal** [comment]
The binary loading code is a tangled mess right now. We need to look at how best refactor it to make it work as expected. The exception resulting from the malformed project file ("Could not find file..." resulting from a mistyped/missing file) is reported, but then swallowed quietly. 

I'm thinking about chaing the WorkerDialog service interface to `async`, which will help in bubbling up exceptions correctly.

**Comment by uxmal** [comment]
I have a partial fix, but it leaves the decompiler shell in an unstable state. I will push it for now, but as mentioned above the proper fix is to rewrite the loading code. I'll open a separate issue for it.

**Comment by uxmal** [comment]
Look to #1051 for a "real" fix.

**Comment by ptomin** [comment]
Thanks for fix, John!
