### ISSUE TITLE
16-Bit NE resources not being extracted.

### ISSUE THREAD

**Issue by jamestodd7** [uxmal/reko#1054]
As discussed earlier, there seems to be an issue where the resources contained within 16-Bit NE Dlls are not extracted out to the Reko project folder.

Thanks,
James.

**Comment by uxmal** [comment]
The resource extraction logic was hard-wired to PE only. I'm working on a generalization that should work for any executable format that has embedded resources.

**Comment by uxmal** [comment]
Thanks for reporting this.  Support for NE resources was added in commit d0e6b1d. It took a little longer than expected. I had to redo the way resources were handled. 

If you find other bugs, please don't hesitate to opening new issues here on github.

**Comment by jamestodd7** [comment]
Thanks for that, I've just confirmed that the changes all seem to be working and the bitmaps are extracted as expected.

Thanks very much for making those changes.

James.
