### ISSUE TITLE
New resources handling causes unnecessary their extraction

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#1060]
After d0e6b1d Reko ignores `extractResources` at project file.
Example:
https://github.com/uxmal/reko/blob/e7aedc96a522052c889a8a16481d3f56d1c0504e/subjects/scripting/pyFuncNames.dcproject#L14
 `extractResources` is `false` but resources were extracted:
https://github.com/uxmal/reko/blob/a8d127e8e1026673f74e23076b3e92ec7c32cdd6/subjects/scripting/pyFuncNames.reko/resources/MANIFEST/2/MANIFEST_2-en.xml

**Comment by uxmal** [comment]
Fixed in 65f9745. Thanks for reporting this.
