### ISSUE TITLE
MSI install does not respect file path

### ISSUE THREAD

**Issue by Elthial** [uxmal/reko#1066]
The MSI installer for 0.10 does not respect the supplied file path and always installs on the C: drive.

I've been trying to get it to install on my G: drive but it won't accept either changing the filepath or browsing to the folder location on G:\program files\reko\

**Comment by uxmal** [comment]
Nice catch, it's unfortunate we didn't see this before the 0.10.0 release.... 

I've fixed this in 8eb6f2da890de749eb50d9bb9c3f2ebbc8864c86.
