### ISSUE TITLE
Created AArch64Dis.tests, AArch64Rw.tests and X86Rw.tests files

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1069]
Reko version is 0.10.0.0

[reko_AArch64Dis.tests.log](https://github.com/uxmal/reko/files/7131510/reko_AArch64Dis.tests.log)
[reko_AArch64Rw.tests.log](https://github.com/uxmal/reko/files/7131511/reko_AArch64Rw.tests.log)
[reko_X86Rw.tests.log](https://github.com/uxmal/reko/files/7131512/reko_X86Rw.tests.log)

**Comment by uxmal** [comment]
Tracking the sub-issues here:

- [ ] reko_AArch64dis.tests
- [ ] reko_X86rw.tests
- [ ] reko_AArch64rw.tests

**Comment by uxmal** [comment]
Commit 5d9d0b9 addresses the missing `vzeroupper` rewriter.

**Comment by uxmal** [comment]
The issues should have been addressed in commit d7cbc75.
