### ISSUE TITLE
--version should also output the git hash

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1080]
After downloading a version from https://cirrus-ci.com/uxmal/reko it is unclear later what git version this download belongs to.

`dotnet .../decompile.dll --version` prints `Decompile.exe version 0.10.1.0` but it should also include the git version like `Decompile.exe version 0.10.1.0 (git:f7fcefa)`. OR provide a version.txt or similar file which contains the git hash. Grepping around I didn't find the git hash in any file.

**Comment by uxmal** [comment]
The command line ```--version``` switch now writes the git hash. Opening the About dialog box displays the git hash.
