### ISSUE TITLE
Disassembler doesn't understand SIMD integer arm64 instructions

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1081]
See attached files.

[reko_AArch64Dis.tests.txt](https://github.com/uxmal/reko/files/7205708/reko_AArch64Dis.tests.txt)
[reko_AArch64Rw.tests.txt](https://github.com/uxmal/reko/files/7205709/reko_AArch64Rw.tests.txt)

Subject is https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/stress_arm64/arm64_macho_simdInt_single_inst__1_var

**Comment by uxmal** [comment]
A big push was made to implement many SIMD instructions. The binary above no longer triggers errors. There are still dozens of uncommon instructions left, but they are straightforward to add for volunteers with spare time.
