### ISSUE TITLE
New test files after a re-run with the decompiler subjects

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1084]
Attached.
[reko_AArch64Dis.tests.txt](https://github.com/uxmal/reko/files/7318058/reko_AArch64Dis.tests.txt)
[reko_AArch64Rw.tests.txt](https://github.com/uxmal/reko/files/7318060/reko_AArch64Rw.tests.txt)
[reko_PaRiscRw.tests.txt](https://github.com/uxmal/reko/files/7318061/reko_PaRiscRw.tests.txt)
[reko_PPCDis.tests.txt](https://github.com/uxmal/reko/files/7318062/reko_PPCDis.tests.txt)

**Comment by uxmal** [comment]
Thanks for reporting these. They have been addressed in a31dc09

**Comment by uxmal** [comment]
Correction: it's commit c20ee77f4ea46 or later that you want.
