### ISSUE TITLE
PA RISC 1.1 SOM binary decompilation

### ISSUE THREAD

**Issue by kernelgurumeditation** [uxmal/reko#1101]
Hi, 

I have done some experiments with reko, and it's a very impressive tool, thanks for your hard work, 
I have noticed that in the last version(0.10.1) it seems reko is unable to detect functions in PA RISC 1.1 binaries that version (0.10.0) would detect, is this a known issue?
Also, reko complains about not finding a binaryname.reko file

Thanks again for this amazing tool

**Comment by uxmal** [comment]
I'm not aware of this issue. Thanks for bringing it to my attention. If you can provide me with a sample that exhibits the problem i can take a look.

**Comment by uxmal** [comment]
Commit 53d993cfd67155b3f35a3f858f64c15c2e01296f added enhancements to the loading of HP SOM images. You can test the CI build to see whether this improves or not. You can contact the Reko team members on https://gitter.im/uxmal/reko or using the Discord channel (see the Reko README.md page).
