### ISSUE TITLE
Created AArch64Dis.tests, AArch64Rw.tests and X86Rw.tests files

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1113]
Version: 4190e52

[reko_X86Rw.tests.txt](https://github.com/uxmal/reko/files/7783520/reko_X86Rw.tests.txt)
[reko_AArch64Rw.tests.txt](https://github.com/uxmal/reko/files/7783521/reko_AArch64Rw.tests.txt)
[reko_AArch64Dis.tests.txt](https://github.com/uxmal/reko/files/7783522/reko_AArch64Dis.tests.txt)

**Comment by uxmal** [comment]
Thanks for reporting this, @rfalke. Commit e8b7470 addresses this, but it's likely there may be more instructions "hidden" behind the ones that were reported as NYI.
