### ISSUE TITLE
Multiple issues in andn

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1114]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_boomerang/andn/arm64_elf_clang_O0_from_rfalke/by_reko.c
Version: 4190e52

Source:
```
int main()
{
  int a = 0x55AA55AA;
  int b = 0x12345678;
  int c = 0x98765432;
  printf("a andn b is %d\n", a & ~b);
  printf("b orn  a is %d\n",  b | ~a);
  printf("a xorn c is %d\n", a ^ ~c);
  return 0;
}
```

Output:
```
void main()
{
	x0_27 = (uint64) printf("a andn b is %d\n", ~22136 & 0x55AA);
	x0_40 = (uint64) printf("b orn  a is %d\n", ~0x55AA | 22136);
	x0_53 = (uint64) printf("a xorn c is %d\n", ~dwLoc28 ^ 0x55AA);
}
```

Issues:
- the variables are not needed
- the literals look truncated
- the operations between literals are not performed
- the dwLoc28 should be replaced with a literal

**Comment by uxmal** [comment]
- [ ] Unnecessary variables
- [x] Truncated literals
- [ ] Constant folding on unary operators
- [ ] dwLoc28 should be folded

**Comment by uxmal** [comment]
The remaining `~` is an artifact of Reko's heuristic for rendering numeric constant (#546)
