### ISSUE TITLE
Bad parameter passing for 'long double'

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1120]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/arm64_simple_float_adds/arm64_elf_clang_O0/by_reko.c

Source:
```
printf("long double: %2ld %Lf\n", sizeof(long double), add_long_double(1.0, 0.1));
```

Output:
```
	x0_85 = (uint64) printf("long double: %2ld %Lf\n", 0x10, add_long_double(g_t1340, g_ow1350, sysreg3_3_4_4_0, sysreg3_3_4_4_1));
```

**Comment by uxmal** [comment]
The `sysreg3_3_4_4_0` references are gone in commit 00b4311.
