### ISSUE TITLE
Struct and union types are parsed incorrectly

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#113]
Try to parse "char * test(_locale_tstruct *s)". Parser does not accept it but its correct. 
Type _locale_tstruct exists in windows32.xml. Its definition:

    typedef name="_locale_tstruct"
      struct name="localeinfo_struct"
    typedef

Struct localeinfo_struct was defined before.

Type library deserializer finds localeinfo_struct in list of structures and creates Type reference with NULL name. Then DataTypeNameSerializer creates Serialized Type reference with NULL name and  CParser could not resolve it.

**Comment by ptomin** [comment]
It could be fixed by https://github.com/uxmal/reko/compare/master...ptomin:fix-struct-and-union-references. But I am not sure if it is correct

**Comment by ptomin** [comment]
Maybe better solution is to add domain field (enum with struct, union and typedef enumerators) to TypeReference. John, what do you think about it?

**Comment by uxmal** [comment]
I thought I'd fixed this before. Let me look at this and come up with a solution.

**Comment by uxmal** [comment]
@ptomin: Does the above commit address the problem?

**Comment by ptomin** [comment]
Parser does not accept "char * test(_locale_tstruct *s)"  as before

**Comment by ptomin** [comment]
After VisitUnion implementation StackOverflow is thrown. Case "struct testStruct{struct testStruct *next}" causes infinite recursion.
I still suggest to add domain field to TypeReference. In that case desirialize-serialize process for struct references will be 
SerializedStruct{name=`<strName>`}=>TypeReference(domain=struct, name = `<strName>`, referent = StructureType(`<structure-fields>`))=>SerializedStruct{name=`<strName>`}
Current implementation supposes
SerializedStruct{name=`<strName>`}=>StructureType(name=`<strName>`, `<structure-fields>`)=>SerializedStruct(name=`<strName>`, `<structure-fields>`)
So undefined struct becomes defined after desirialize-serialize process

**Comment by uxmal** [comment]
Pavel, do you think you could create a unit test that reproduces the error on a branched named something like `issue-113` so I can get a clear look at the problem? I'm a lttle reluctant to modify the `TypeReference` if there is any way I can avoid it.

**Comment by ptomin** [comment]
Could you try to enter "char * test(_locale_tstruct *s)" to user signature editor of WindowsDecompiler?

**Comment by uxmal** [comment]
OK, got it. I will be creating a new branch for this issue to firmly nail it into the ground.

**Comment by ptomin** [comment]
Looks fine. Now parser accepts "char * test(_locale_tstruct *s)". Thanks
