### ISSUE TITLE
Doesn't recognize call parameters in arm64 binary

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1130]
Version: 9a281a1
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/branchless_arithmetic/arm64_macho/by_reko.c

Output:
```
void _main()
{
	_sat_addu32b();
	_printf();
	_sat_subu32b();
	_printf();
	_sat_mulu32b();
...
```

**Comment by uxmal** [comment]
The output now contains parameters to `printf`.
