### ISSUE TITLE
MacOS Classic (Master) - loading .hqx files fails to include MacsBug symbols and scan binary correctly 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#1133]
Sample file loaded LinkIIgs.hqx

**Comment by uxmal** [comment]
It's time to remove the `ProgramImageLoader.Relocate` methods. All image loaders need to be changed to put any symbols they discover inside of the `Program` object directly. They already have access to the `Program` object, so this is mostly a mechanical grind through all of the file formats.

**Comment by uxmal** [comment]
Starting with commit 3a6118a, this will work again. Give it a try!
