### ISSUE TITLE
Microsoft Visual C++ Packer

### ISSUE THREAD

**Issue by gariemiller** [uxmal/reko#1141]
Would it be possible to add a Microsoft Visual C++ Unpacker to Reko? I have a GPL application here that the Reko Diagnostic reads "Packer 'Microsoft Visual C++' detected. Unable to unpack executable file packed with 'Microsoft Visual C++'.

**Comment by uxmal** [comment]
Could you provide me with the binary in question so I can take a look at why this is happening?

**Comment by gariemiller** [comment]
Hi John

I attached it to an eMail but it got blocked. Let me try this instead...

This wont support dropping an .exe either. Any suggestions?

Garie Miller

**Comment by uxmal** [comment]
Try zipping the file up, then meet me over at https://gitter.im/uxmal/reko . We can transfer the file there, or in a private channel.

**Comment by uxmal** [comment]
Another trick I've used to send exes in the mail is to ZIP them first, then rename the file from `file.zip` to `file.zip.txt`, and then ZIP the file again. This double zipping defeats most virus scanners.

**Comment by gariemiller** [comment]
Sorry John

Looks like we are foiled again.

Let me check my friend's web page. He may still have it posted and you can get it from there. It is called PathSim.

Garie

**Comment by gariemiller** [comment]
Yes! His page is still up. And he has posted the source code too.

www.moetronix.com/ ae4jy/

"PathSim"

Garie

**Comment by gariemiller** [comment]
That should be :

www.moetronix.com/ae4jy/

**Comment by uxmal** [comment]
@gariemiller : I downloaded the binary, ran it with the most recent build of Reko, and saw no warnings. I think you may be running an older version of Reko, perhaps the 0.10.1 release. The message you're seeing is harmless and was toned down somewhere between now and version 0.10.1.

For what it's woth, I hope to make a release in a couple of weeks. In the meantime, you can find the Continuous integration builds over here: https://github.com/uxmal/reko/actions/runs/1730515562 , at the bottom of the page. Unfortunately, github doesn't automatically give you the latest CI build, you have to go to the "Actions" tab and poke around (https://github.com/uxmal/reko/actions/workflows/reko.yml).

Do let me know if you find other issues with Reko.

**Comment by gariemiller** [comment]
Thanks John

Yes I was running Reko 9.2.3. I will get the newer one when it comes out. Great! If I see any more common packers I will drop you an issue.

Thanks again

Garie
