### ISSUE TITLE
Phar Lap executables that aren't packed don't load into memory

### ISSUE THREAD

**Issue by slartibardfast** [uxmal/reko#1142]
Hi, 

I noticed there's no equivalent to UnpackImage to load into memory an unpacked Phar Lap EXP. 
So, I've added it in a pull request to follow. 

(I'm in the process of reversing the DOS/V version of Strike Commander, which runs on DX386 a Phar Lap style extender)

thanks so much for reko, very cool stuff!

pull request is here: #1143

**Comment by uxmal** [comment]
This was fixed in #1143
