### ISSUE TITLE
"Address 00000001 is not within the image range.        at Reko.Core.ImageMap.AddItemWithSize"

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1148]
Version: c44f71e1
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_internet/asmutils/test1/ia32_elf_static/by_reko.out

The other `test*` do also fail.

**Comment by uxmal** [comment]
Reko didn't like symbols based in the `SHN_ABS` "section". So they are now ignored in  6b3767e.
