### ISSUE TITLE
Strange memory write

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1153]
Version: c44f71e1
Subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/stress_arm64/arm64_macho_simdInt_single_inst__1_var

Output:
```
void inst_255_var_0(word64 q13_64_64)
{
        0x52 = (byte) 1374083987;   <=========== ????
        g_qw44020 = q13_64_64 - 7225339094864742789;
        g_t44028.u1 = ~0x40;
        g_qw44018 = 0x00;
}
```

Also why does reko think that there is an input parameter?

**Comment by uxmal** [comment]
Fixed in commit 05557e17b23f81ee26bde12de0c94a08959ce27a.
