### ISSUE TITLE
Classic MAC OS - new error during Reconstruct Data Type phase. 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#1164]
Sample file: LinkIIgs
This is a new error that appears during the Reconstruct Data Type.

Code prior to Reconstruct data type
0010133E 598F subq.l #$04,a7
00101340 3F3C A88F move.w #$A88F,-(a7)
00101344 7001 moveq #$01,d0
00101346 1F00 move.b d0,-(a7)
00101348 4EBA 3076 jsr.l get_trap                                                            ; $3078(pc)
0010134C 303C A89F move.w #$A89F,d0
00101350 A146 illegal #$A146
00101352 B1DF cmpa.l (a7)+,a0
00101354 56C3 sne d3
00101356 4403 neg.b d3
00101358 1B43 EDF2 move.b d3,-$120E(a5)
0010135C 602E bra $0010138C

l0010133E:
    Mem259[a7_117 - 2:word16] = 0xA88F
    Mem263[a7_117 - 3:byte] = 0x01
    get_trap(Mem263[a7_117 - 3:char], Mem263[a7_117 + 1:int16])
    Mem284[a5 + -4622:byte] = -(GetTrapAddress(~0x5760) - Mem263[a7_117 + 0x01:word32] != 0x00 ? ~0x00 : 0x00)
    a7_116 = a7_117 + 0x05
    goto l0010138C
l0010135E:
    branch v33_126 != 0x54 l0010138C

Error,00101358,An error occurred while processing the statement Mem284[a5 + -4622<i32>:byte] = -(GetTrapAddress(0xA89F<16>) - Mem263[a7_117 + 1<32>:word32] != 0<32> ? 0xFF<8> : 0<8>). Not handling ptr32 and UniversalProcPtr yet

**Comment by uxmal** [comment]
Whoa! `UniversalProcPtr` indeed! Let's see if I can fix this quickly.

**Comment by uxmal** [comment]
Hm. I'm unable to reproduce the error. What commit of Reko are you on?

**Comment by gbody** [comment]
MASTER Commit d20b55b2.
It occurs with just opening the hqx file and analyzing the file via each phase. Error still occurs in the Reconstruct Data Type phase.

**Comment by uxmal** [comment]
Commit a4f07f332dca756fe174893cb238d45115bc199f fixes this.
