### ISSUE TITLE
Master - Disassembly view changes some instructions to Hex dump when scrolling up.

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#1166]
Sample File LinkIIgs.hqx Master instance.
Load sample file, scan binary.
Select procedure Get_Org to see disassembly.
00101B46 4E56 FFFC link a6,#$FFFC
00101B4A 486E FFFC pea -$0004(a6)
00101B4E 70FF moveq #-$01,d0
00101B50 2F00 move.l d0,-(a7)
00101B52 486D EF02 pea -$10FE(a5)
00101B56 2F2E 0008 move.l $0008(a6),-(a7)
00101B5A 4EBA 04FE jsr.l Num_Option                                                            ; $0500(pc)
00101B5E 4A00 tst.b d0
00101B60 4FEF 0010 lea $0010(a7),a7
00101B64 6706 beq $00101B6C
00101B66 202E FFFC move.l -$0004(a6),d0
00101B6A 600E bra $00101B7A
00101B6C 2F2D F93C move.l -$06C4(a5),-(a7)
00101B70 7001 moveq #$01,d0
00101B72 2F00 move.l d0,-(a7)
00101B74 4EBA F3AC jsr.l fatal                                                            ; -$0C52(pc)
00101B78 504F addq.w #$08,a7
00101B7A 4E5E unlk a6
00101B7C 4E75 rts

click on scroll up once and output changes to this. 
and get this.

00101B3A                               89 47 65 74 5F 49           .Get_I
00101B40 6E 70 75 74 00 00 4E 56 FF FC 48 6E FF FC 70 FF nput..NV..Hn..p.
00101B50 2F00 move.l d0,-(a7)
00101B52 486D EF02 pea -$10FE(a5)
00101B56 2F2E 0008 move.l $0008(a6),-(a7)
00101B5A 4EBA 04FE jsr.l Num_Option                                                            ; $0500(pc)
00101B5E 4A00 tst.b d0
00101B60 4FEF 0010 lea $0010(a7),a7
00101B64 6706 beq $00101B6C
00101B66 202E FFFC move.l -$0004(a6),d0
00101B6A 600E bra $00101B7A
00101B6C 2F2D F93C move.l -$06C4(a5),-(a7)
00101B70 7001 moveq #$01,d0
00101B72 2F00 move.l d0,-(a7)
00101B74 4EBA F3AC jsr.l fatal                                                            ; -$0C52(pc)
00101B78 504F addq.w #$08,a7
00101B7A 4E5E unlk a6
00101B7C 4E75 rts 

Appears that the hex dump produced is displaying a line of 16 bytes which is including 10 bytes of code that should be displayed disassembled.
First appears in Commit 28ca9b75

**Comment by uxmal** [comment]
Thanks for the effort you put into locating the point of the regression, it made it so easy to find the error and fix it.
