### ISSUE TITLE
Option to filter the information displayed in the "Diagnostics" tab

### ISSUE THREAD

**Issue by draiN-NEO** [uxmal/reko#1180]
An option to filter the information shown in the "Diagnostics" tab will be helpful. For example, when aiming to do a successful decompilation with manual fixes needed, the tab would only need to show the addresses with errors that need to be resolved.

My suggestion is mainly based off of a similar feature that's provided in Ghidra:
![ghidra 1](https://user-images.githubusercontent.com/52803804/171510819-a5230e0f-809b-4f3b-8984-1e095cc927a5.png)
![ghidra](https://user-images.githubusercontent.com/52803804/171510838-5d31a550-e4a9-4fb1-9d56-82b4a0c461f1.png)

**Comment by uxmal** [comment]
I just implemented a first cut of a diagnostics filter dialog. 
![image](https://user-images.githubusercontent.com/10154465/171997955-55b5d82c-c5c0-40ed-b079-dd95db10d295.png)

**Comment by uxmal** [comment]
For extra credit, add fancy icons :)
