### ISSUE TITLE
Crash log generated during data flow analysis

### ISSUE THREAD

**Issue by draiN-NEO** [uxmal/reko#1183]
Crash log: [analysis_99_crash.txt](https://github.com/uxmal/reko/files/8931329/analysis_99_crash.txt)
A XEX file was used to generate a decompilation and the following error log with "Shingle scanning" enabled.

**Comment by uxmal** [comment]
I'm able to reproduce the issue

**Comment by uxmal** [comment]
The binary contains "minicode" sequences, used to save registers in the _caller's_ stack frame. These sequences use negative stack offsets. This confuses the Escaped frame variable analysis. 

I have a fix on my machine, but it uncovered a few other issues that I'm chasing down.

**Comment by uxmal** [comment]
I've added support for some missing instructions in the Xenon instruction set, as well as fixing the original issue.

**Comment by draiN-NEO** [comment]
A new crash log was generated during the same phase: [analysis_99_crash.txt](https://github.com/uxmal/reko/files/8955690/analysis_99_crash.txt)
