### ISSUE TITLE
Feature Request/Help

### ISSUE THREAD

**Issue by youarebamboozled** [uxmal/reko#1184]
I wanna open a .pak file where I know, are c files in there and i wanna have them.

**Comment by uxmal** [comment]
A quick google search reveals both that `.pak` is an archive format. You therefore need not a decompiler like Reko, but an archive/unarchiver. There are many such programs available on the net. I leave it as an exercise for the reader to download such software and use it to extract the files from the `.pak` file.

**Comment by youarebamboozled** [comment]
The problem is this pak file cant be open
