### ISSUE TITLE
Feature Request: Add annotations to .Inc file

### ISSUE THREAD

**Issue by Elthial** [uxmal/reko#1187]
This is a request to allow annotations in .inc files so that the complete workflow can be done in a C like environment instead of being split between the .inc and dcproject file.

The suggested syntax: 
[[reko::annotation("0234:23ED", "The following code formats my hard drive on Fridays")]]

**Comment by uxmal** [comment]
Finally got around to implementing this.... The new feature uses the exact syntax specified above.
