### ISSUE TITLE
seam not work with ELF 32-bit MSB executable, MIPS, MIPS-I version 1 (SYSV), dynamically linked, interpreter /lib/ld-uClibc.so.0, no section header

### ISSUE THREAD

**Issue by alphaonex86** [uxmal/reko#1191]
Example of simple binary, unable to reverse:
[elfmips.gz](https://github.com/uxmal/reko/files/9433753/elfmips.gz)

**Comment by uxmal** [comment]
Thanks for reporting this, I'm able to reproduce the issue. I will try to have a fix the coming week.

**Comment by uxmal** [comment]
After commit d56acf3f0a4415d81924253442b3baf77ceb5ca4, this has been fixed. In addition, support for varargs functions like ` printf` was improved for MIPS.
