### ISSUE TITLE
Linux kernel modules decompilation bug

### ISSUE THREAD

**Issue by alphaonex86** [uxmal/reko#1192]
Hi, I try decompile this MIPS kernel module
[omcidrv.ko.gz](https://github.com/uxmal/reko/files/9482514/omcidrv.ko.gz)
 with nightly build, the output have lot of <unknown> Mem0 and char corrupted, I can't copy into text file.

PS: README.md -> https://cirrus-ci.com/uxmal/reko -> link down

**Comment by uxmal** [comment]
After commit 4265ea85d66e05d942eb Reko doesn't show any errors when loading the given `.ko` file.
