### ISSUE TITLE
To run this application, you must install .NET

### ISSUE THREAD

**Issue by Devarite** [uxmal/reko#1195]
When I open the app I get the error: "To run this application, you must install .NET".

![explorer_q7BLbkIAPD](https://user-images.githubusercontent.com/80384432/191413470-0783d674-9e3c-491e-a37e-483e31b13942.png)

When I click Yes It closes and does nothing.

I Already have .NET installed.

**Comment by uxmal** [comment]
Exactly which version of .NET do you have installed? And did you build Reko yourself or are you using the released binary bits? Reko currently uses .NET 5. Try the following link:
https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by Devarite** [comment]
Looks like I did not have that specific .NET version installed, it now works after installing net 5.

I had 6 (latest) and Core 3 installed.
