### ISSUE TITLE
Reko could not decompile m68k jump tables

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#121]
Subj:
movea.l	off_C070(pc,d0.l),a5
jmp	(a5)
; ---------------------------------------------------------------------------
off_C070:dc.l loc_C0A0
dc.l loc_C0B6
dc.l loc_C0D0
dc.l loc_C0FA
dc.l loc_C136
dc.l loc_C16A
dc.l loc_C1A0
dc.l loc_C218
dc.l loc_C22A
dc.l loc_C23E
dc.l loc_C27A
dc.l loc_C2E0

It tells about array index bounds error. Sample binary: [m68k_jump.zip](https://github.com/uxmal/reko/files/108123/m68k_jump.zip)

Full AmigaOS binary (just inserted previous binary at entry point: [m68k_jump_bin.zip](https://github.com/uxmal/reko/files/108127/m68k_jump_bin.zip)

**Comment by uxmal** [comment]
The exception no longer occurs. However, Reko overestimates the number of branches in your code sample, so it may "go off the track". This is a harder problem to solve; I've opened a separate issue to deal with that.

**Comment by lab313ru** [comment]
![2016-01-29_105734](https://cloud.githubusercontent.com/assets/7189309/12670154/38251f22-c677-11e5-8029-6aa33a91fba1.png)
Hmm... It is strange. I think, it doesn't work well with m68000, but does work with m68020. Could you fix that?
It doesn't recognize that these offsets are long length. Code should look like that.

`
		movem.l	d0-a6,-(sp)
		movea.l	a0,a2
		movea.l	a1,a6
		move.l	(a2)+,d0
		move.l	d0,(dword_FF0F08).l
		moveq	#0,d6
		move.l	d6,(dword_FF0F04).l
		movea.l	d6,a4
		moveq	#$F,d2
		move.l	#$FF,d7
		bra.w	loc_C3DE
; ---------------------------------------------------------------------------

loc_C050:				; CODE XREF: sub_C02A+3C0j
		move.l	a4,d3
		addq.l	#1,a4
		move.b	(a2,d3.l),d3
		and.l	d7,d3
		move.l	d3,d0
		andi.w	#$F0,d0	; 'р'
		lsr.b	#2,d0
		cmpi.w	#$2C,d0	; ','
		bgt.w	loc_C3DE
		movea.l	off_C070(pc,d0.l),a5
		jmp	(a5)
; ---------------------------------------------------------------------------
off_C070:	dc.l loc_C0A0
		dc.l loc_C0B6
		dc.l loc_C0D0
		dc.l loc_C0FA
		dc.l loc_C136
		dc.l loc_C16A
		dc.l loc_C1A0
		dc.l loc_C218
		dc.l loc_C22A
		dc.l loc_C23E
		dc.l loc_C27A
		dc.l loc_C2E0
`

**Comment by uxmal** [comment]
I will look at this again in a couple of hours.

**Comment by lab313ru** [comment]
You may close this bug. This bug ill be more specific: https://github.com/uxmal/reko/issues/122
