### ISSUE TITLE
Bug: Need to click between marking data with Ctrl+T

### ISSUE THREAD

**Issue by throwaway96** [uxmal/reko#1219]
After marking data (in particular, strings) with Ctrl+T, the next byte is highlighted. However, pressing Ctrl+T again doesn't bring up the type prompt. You have to click on the highlighted byte before it will work again.

**Comment by uxmal** [comment]
Focus is being lost when the data type marker window is closed.

**Comment by uxmal** [comment]
Fixed in 6e13af2.
