### ISSUE TITLE
Bug: Labels overlap text boxes in Edit Procedure dialog

### ISSUE THREAD

**Issue by throwaway96** [uxmal/reko#1220]
The `Signature:` and `Comment:` labels are in front of and overlapping their associated text boxes in the Edit Procedure dialog.
![image](https://user-images.githubusercontent.com/68320646/207314696-7fe05bcb-d31d-4e2e-8aba-5270bc433c57.png)

**Comment by uxmal** [comment]
This has been fixed:
![image](https://user-images.githubusercontent.com/10154465/216017845-9603c1f3-e061-4e9a-ac87-a4a94e32ee1d.png)
