### ISSUE TITLE
Feature request: Marking instructions as "unlikely"

### ISSUE THREAD

**Issue by throwaway96** [uxmal/reko#1226]
The goal is to help the shingle scanner find only valid code, while maintaining the ability to analyze binaries that are intentionally obfuscated or otherwise do unusual things. Examples (on AEON) include modifying the zero register and jumping to the stack.  This could be an `instrclass` bit.

**Comment by uxmal** [comment]
This has been implemented. Disassemblers that wish to participate can mark instructions with the `InstrClass.Unlikely` bit. The user can set the `Unlikely` bit in the `Program > Properties` dialog in the GUI.
