### ISSUE TITLE
MacOS Classic - (Master) -  Unable to load metadata file macos/MacOSClassicInterfaces.p. Specified method is not supported. 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#1228]
Recent changes have caused the error Unable to load metadata file macos/MacOSClassicInterfaces.p. Specified method is not supported. 
when opening a MacOS Classic application or existing project file of a MacOS classic application. 

 This exception was originally thrown at this call stack:
    Reko.Environments.MacOS.Classic.ConstantEvaluator.VisitStringLiteral(Reko.Core.Hll.Pascal.StringLiteral) in ConstantEvaluator.cs
    Reko.Core.Hll.Pascal.StringLiteral.Accept<T>(Reko.Core.Hll.Pascal.IPascalSyntaxVisitor<T>) in PascalSyntax.cs
    Reko.Environments.MacOS.Classic.MpwPascalInterfaceLoader.EvaluateConstants(System.Collections.Generic.IEnumerable<Reko.Core.Hll.Pascal.Declaration>) in MpwPascalInterfaceLoader.cs
    Reko.Environments.MacOS.Classic.MpwPascalInterfaceLoader.Load(Reko.Core.IPlatform, Reko.Core.TypeLibrary) in MpwPascalInterfaceLoader.cs
    Reko.Core.MetadataLoader.Load(Reko.Core.IPlatform, string, Reko.Core.TypeLibrary) in MetadataLoader.cs
    Reko.Core.Services.TypeLibraryLoaderServiceImpl.LoadMetadataIntoLibrary(Reko.Core.IPlatform, Reko.Core.Configuration.TypeLibraryDefinition, Reko.Core.TypeLibrary) in ITypeLibraryLoaderService.cs

Call Stack
	Reko.Core.dll!Reko.Core.Services.TypeLibraryLoaderServiceImpl.LoadMetadataIntoLibrary(Reko.Core.IPlatform platform, Reko.Core.Configuration.TypeLibraryDefinition tlElement, Reko.Core.TypeLibrary libDst) Line 75	C#
 	Reko.Core.dll!Reko.Core.Platform.EnsureTypeLibraries(string envName) Line 497	C#
 	Reko.Core.dll!Reko.Core.Platform.CreateMetadata() Line 432	C#
 	Reko.Core.dll!Reko.Core.Serialization.ProjectLoader.LoadProject(Reko.Core.Serialization.Project_v5 sp) Line 196	C#
 	Reko.Core.dll!Reko.Core.Serialization.ProjectLoader.Deserializer.VisitProject_v5(Reko.Core.Serialization.Project_v5 sProject) Line 157	C#
 	Reko.Core.dll!Reko.Core.Serialization.Project_v5.Accept<Reko.Core.Project>(Reko.Core.Serialization.ISerializedProjectVisitor<Reko.Core.Project> visitor) Line 72	C#
 	Reko.Core.dll!Reko.Core.Serialization.ProjectLoader.LoadProject(System.IO.Stream stm) Line 140	C#
 	Reko.Core.dll!Reko.Core.Serialization.ProjectLoader.LoadProject(byte[] image) Line 87	C#
 	Reko.dll!Reko.Loading.Loader.Load(Reko.Core.ImageLocation imageLocation, string loaderName, Reko.Core.Address addrLoad) Line 109	C#
 	Reko.Gui.dll!Reko.Gui.Forms.InitialPageInteractorImpl.OpenBinary.AnonymousMethod__0() Line 126	C#
 	Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.WindowsDecompilerEventListener.Worker_DoWork(object sender, System.ComponentModel.DoWorkEventArgs e) Line 158	C#

**Comment by uxmal** [comment]
Thanks for reporting this. It has been fixed in commit 39d8c89.
