### ISSUE TITLE
Blsr Instruction

### ISSUE THREAD

**Issue by tgiphil** [uxmal/reko#1233]
Reko isn't decoding the following opcodes: c4 e2 78 f3 c8 

It should translate to: "blsr eax,eax" 

Instead, it translates to: 

00000006 c4 e2                           illegal
00000008 78 f3                           js 00xfffffffd
0000000a c8 5d c3                        illegal

**Comment by uxmal** [comment]
Indeed, this instruction shouldn't be restricted to 64 bit mode only. Once I'm home, an easy fix will be on its way. You will need a new nuget release,

**Comment by uxmal** [comment]
Working on the nuget release now
