### ISSUE TITLE
Open As... should allow user to pick "unknown" platform if 

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#124]
Issue #122 @lab313ru is complaining that it's impossible to proceed in Open As... without supplying a platform from the list. There should be an option to pick a "neutral" or "default" platform, so that no platform-specific quirks sneak into the decompilation.

**Comment by lab313ru** [comment]
I can't open [a raw m68k binary](https://github.com/uxmal/reko/files/108123/m68k_jump.zip) (not Sega Genesis ROM).
1. File_name.bin
2. (Unknown)
3. (None)
4. Motorola 68K family
5. C02A

It tells about an error "object reference not set to an instance of an object".

**Comment by uxmal** [comment]
Working on it... patience, dear @lab313ru  :-)

**Comment by lab313ru** [comment]
Error,,Error when reconstructing types. object reference not set to an instance of an object

**Comment by uxmal** [comment]
That error is not what this bug is tracking; I've copied this to #122, which is what I'm using to track the issues with `m68k_jump.bin`.
