### ISSUE TITLE
Add support for Sega Genesis platform

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#126]
Should at least be able to load SEGA ROM images without all the fussing. @lab313ru: at what address does a SEGA ROM image load?

Other ifno
 https://github.com/lab313ru/smd_ida_tools/blob/master/smd_loader/smd_loader.h

**Comment by lab313ru** [comment]
Loading address is constantly 0.

**Comment by uxmal** [comment]
* Sega Genesis platform has been added
* Sega Genesis ROM file type has been added. You still need to use "Open As", though, since there is no magic cookie like the "MZ" in MS-DOS files.
* Open As.. dialog now allows you to either enter architecture, environment, and address manually or pick a pre-configured raw file format (like CP/M .COM or Sega Genesis ROM image)
