### ISSUE TITLE
An item with the same key has already been added. (Parameter 'key') - NE Executable Error

### ISSUE THREAD

**Issue by cesar-avalos3** [uxmal/reko#1277]
Hello, I'm trying to decompile an old WATCOM-compiled 16-Bit NE Windows executable, and I'm getting this error,

```
Error: An error occurred during decompilation.
    An item with the same key has already been added. Key: 0015:4F8A (Parameter 'key')
       at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at Reko.ImageLoaders.MzExe.NeImageLoader.LoadProgram(Address addrLoad) in d:\dev\uxmal\reko\master\src\ImageLoaders\MzExe\NeImageLoader.cs:line 293
 [...]
```
The executable is from "_Dark Sun Crimson Sands_", Mdark.exe. I have two different versions of the program, and both exhibit the same behavior.

[Mdark.zip](https://github.com/uxmal/reko/files/12354806/Mdark.zip)

Thanks.

**Comment by uxmal** [comment]
Thanks for submitting this report. I will look into it later today
