### ISSUE TITLE
Reko throws exception when decompiling Python module sample

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#128]
The following exception is thrown at the reconstruct data types stage: "Error when reconstructing types. Comparer threw an exception. Way too deep" The reason is known by #113 issue: recursive structure("struct testStruct{struct testStruct *next}")

**Comment by uxmal** [comment]
Thanks for this fix.

**Comment by ptomin** [comment]
Now it fails with "Error when reconstructing types. Pulling difference word32 and ui32" . It occurs when TypeCollector::CollectTypes() calling. If OLD macro defined then type collecting does not fail (DataTypeBuilder and TraitCollector are used)

**Comment by uxmal** [comment]
The expression in question is `esp_314 - 4`. For some reason, `esp_314` is not a pointer using the new Type analysis framework. I need to look at this a little closer.

**Comment by ptomin** [comment]
I have created issue #130 for exception in TypeCollector
