### ISSUE TITLE
New test files after a re-run with the decompiler subjects (2023-08)

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#1280]
Version: 0.11.4.0-931ca7d

[reko_X86Rw.tests.txt](https://github.com/uxmal/reko/files/12446476/reko_X86Rw.tests.txt)
[reko_X86Dis.tests.txt](https://github.com/uxmal/reko/files/12446477/reko_X86Dis.tests.txt)
[reko_PaRiscDis.tests.txt](https://github.com/uxmal/reko/files/12446478/reko_PaRiscDis.tests.txt)
[reko_AArch64Rw.tests.txt](https://github.com/uxmal/reko/files/12446479/reko_AArch64Rw.tests.txt)
[reko_AArch64Dis.tests.txt](https://github.com/uxmal/reko/files/12446480/reko_AArch64Dis.tests.txt)

**Comment by uxmal** [comment]
Added decoders and rewriters for the reported instructions.
