### ISSUE TITLE
RISC-V: disassembler incorrectly decodes CSRRx instructions

### ISSUE THREAD

**Issue by gregoral** [uxmal/reko#1299]
**CSRR**x instructions are incorrectly decoded by `Reko.Arch.RiscV` disassembler.

`CSRRW`, `CSRRS` and `CSRRC` are incorrectly decoded.
The reason is because decoders for these instructions are using register `r2`.
This is incorrect and should be changed to use `r1`.

Variants with immediate operand `CSRRWI`, `CSRRSI` and `CSRRCI` are correctly decoded.
This is because the index offset for immediate operand is hardcoded to bit 15, which is correct.

For example, a `csrr` pseudo instruction:
```asm
csrr t0, mhartid
// or
csrrs t0,mhartid,x0
```
From the RISC-V documentation:
> The assembler pseudoinstruction to read a CSR, `CSRR rd, csr`, is encoded as `CSRRS rd, csr, x0`.

reko incorrectly disassembles it as:
```asm
22F3 F140 csrrs t0,mhartid,s4
```

It should be:
```asm
22F3 F140 csrrs t0,mhartid,x0
// or
22F3 F140 csrr t0,mhartid
```
gdb correctly disassembles it as:
```asm
f3 22 40 f1     csrr    t0,mhartid
```

I have already debugged the issue and have a fix.
Should I submit a pull request to this repo or do I have to create a fork fist?

The root cause for this issue is in `InstructionSet` class (src\Arch\RiscV\InstructionSet.cs):
```cs
Instr(Mnemonic.csrrw, d, Csr20, r2),
Instr(Mnemonic.csrrs, d, Csr20, r2),
Instr(Mnemonic.csrrc, d, Csr20, r2),
```
which should be corrected to use `r1` register instead of `r2`:
```cs
Instr(Mnemonic.csrrw, d, Csr20, r1),
Instr(Mnemonic.csrrs, d, Csr20, r1),
Instr(Mnemonic.csrrc, d, Csr20, r1),
```
`r2` starts at offset 20, which is incorrect for these instructions.

This is from the documentation:
**RV32/RV64 Zicsr Standard Extension**
```
 31               20 19  15 14 12 11 7 6       0
┌───────────────────┬──────┬─────┬────┬─────────┐
│        csr        │ rs1  │ 001 │ rd │ 1110011 │ CSRRW
│        csr        │ rs1  │ 010 │ rd │ 1110011 │ CSRRS
│        csr        │ rs1  │ 011 │ rd │ 1110011 │ CSRRC
│        csr        │ uimm │ 101 │ rd │ 1110011 │ CSRRWI
│        csr        │ uimm │ 110 │ rd │ 1110011 │ CSRRSI
│        csr        | uimm | 111 | rd | 1110011 | CSRRCI
└───────────────────┴──────┴─────┴────┴─────────┘
```

Could you please give me some hints, about the process to submit a patch for this.  
I would also try to add new tests for these instructions.

**Comment by gregoral** [comment]
Hi,
thanks for reviewing the proposed changes.
I'm familiar with git but I have never contributed to other projects.

I'll create a fork and follow the steps you outlined.
When I have a fix ready I'll create a PR.

Thank you for creating and maintaining this interesting project.

**Comment by gregoral** [comment]
Hi,
I have added one test but I plan to write more.

Along the way I found a bad test:
```cs
public void RiscV_dasm_csrrc()
{
    AssertCode("csrrc\tzero,mstatus,zero", "73B00230");
}
```

This appears to be an error and should be changed to:
```cs
AssertCode("csrrc\tzero,mstatus,zero", "73300030");
// or
AssertCode("csrrc\tzero,mstatus,t0", "73B00230");
```
as  `73B00230` is actually `csrrc zero,mstatus,t0`, which I double-checked using gdb disassembler as a reference.

This is how gdb decompiles `csrrs` and `csrrc`:
```asm
73 30 00 30     csrc    mstatus,zero
73 b0 02 30     csrc    mstatus,t0
f3 22 40 f1     csrr    t0,mhartid
```
NOTE: gdb converts raw instructions to pseudo instructions which reko doesn't do.

Should I group all **CSRR** related tests in one place, or should I add new tests at the bottom?
I think it would be best if all tests for similar instructions are in one place, is that ok?

**Comment by uxmal** [comment]
You're more than welcome to add more tests to ensure correctness. If you want to randomize the bit patterns in the decompiled instructions, feel free to do so as well. When I've written disassembler tests on the various architectures supporteed by Reko, I've typically generated a few kilobytes of random bytes, pointed the relevant disassembler at those bytes, and created unit tests from any bit patterns that the disassembler in question calls `DisassemberBase.NotYetImplemented(string)` on. Sometimes those bit patterns are collected from actual real binaries, which naturally contain more `0x00` and `0xFF` bytes than a uniform distribution of values would.

As for pseudo-instructions: these are common on Risc-like architectures. Adding support to show instructions as pseudo-mnemonics or as their underlying raw mnemonics, and toggling between these two modes, is not terribly hard; it's just that no-one has asked for it yet. If this is something you'd like to see in Reko, open a separate issue and we can discuss further there.

As far as organization of unit tests: they are typically, but not consistently, ordered alphabetically. I have no strong opinions about it, except that I feel that going back to the almost 10000 unit tests and sorting them will prove to be big task, with no concrete benefit, and proves to be a big churn in the git history. But if you feel strongly that the methods in `RiscVDisassemblerTests` need to be sorted alphabetically, by all means go ahead.

**Comment by uxmal** [comment]
I'm closing this issue now, as the original problem was solved by your PR. Don't forget to open new issue(s) for other bugs you've discovered.
