### ISSUE TITLE
TypeCollector throws exception when decompiling Python module sample

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#130]
The following exception is thrown at the reconstruct data types stage "Error when reconstructing types. Pulling difference word32 and ui32" . It occurs when TypeCollector::CollectTypes() calling. If OLD macro defined then type collecting does not fail (DataTypeBuilder and TraitCollector are used)

**Comment by uxmal** [comment]
I've reproduced the error and have a fix. Unfortunately I'm at dinner so you will need to wait a little. ...:-)

**Comment by uxmal** [comment]
This should no longer fail.

**Comment by ptomin** [comment]
Thanks, John. Now TypeCollector does not fail on Python sample. The next stage is to use user defined global variables to discover new entry points (more 4 functions should decompiled). I have crude implementation of GlobalDataScaner 47a56df. It will improve it and do PR.

**Comment by uxmal** [comment]
Are those entry point exported by your DLL? If so, Reko should have picked them up from the PE Import table. If this is the case, plesae open a separate issue to track "missing imports"

**Comment by ptomin** [comment]
No it is not exported entry points. I mean user defined global variables. 
e.g. Python sample contains methods array of PyMethodDef structs. If user set global variable <address> arr[5] of PyMethodDef then Reko could discover 4 new entry points: py_sum,  py_dif,  py_div,   py_fdiv
