### ISSUE TITLE
Reko needs a better mechanism to deal with indirect jumps

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#132]
Reko goes off the rails when certain sequences of opcodes are given to it (see #121 for an example). Currently Reko uses the class `Backwalker` to performa a backwards slice to find the bounds of the indirect jump. The code is adhoc hackery of the worst kind. A better more reliable analysis is needed.

**Comment by gbody** [comment]
@uxmal If you assume that the jumptables have bounds checking, and it is possible to capture the address of the current compare instruction being processed. Then when your jump table needs to be processed, check if the compare address is within say 30 bytes of the jmp instruction. Check the next instruction is a branch and matches one of the expected branch type(s).
If it is there is a good chance that this is the last compare used for bounds checking, then you have the number of entries in the table. From there you just need to check through the instructions to find the size from the load instruction of the register used in the jump instruction This would allow you to get the size of the jump table.

**Comment by uxmal** [comment]
Indeed, one can hope that the jump table is guarded by a bounds check. Most compiler-emitted switch statements will have bounds checks, although many hand-rolled assembly language programs omit the bounds check. For those cases, Reko must fall back on "oracular" information provided by the user.

One has to be careful when making assumptions about the relative location of the bounds check. Compilers are allowed to rearrange emitted machine code instructions so that while they still implement the semantics of the original source code, they may be quite jumbled. In addition, the bounds check could be further than 30 bytes away from the actual indirect jump, so one needs to use a more nuanced approach.

By the time the scanner reaches an indirect jump, it must have passed through a path of basic blocks in the program. It is highly likely that the index expression will be compared using a bounds check (comparison with a constant integer), a cast to a byte (which in essence is a bounds check <= 255) or a bit mask operation (where the least significant bits are `and`ed with a mask of all ones), and that this comparison happens within the 3 basic blocks closest to the indirect jump. This is the essence of the algorithm used by the `BackWalker`.

However, as it stands today, `BackWalker` is incomplete. Among other things, it us not able to handle the following cases:
1. When the indexing variable is kept not in a register but in a memory location (e.g. x86 `ss:[bp+6]` or `ss:[ebp+8]` 
2. When the indexing variable is being cast a lot (e.g. when the resulting Reko IR looks like:
```
d0 = DPB(d0, Mem[a4 + 8:word16], 0)
d0 = (int32) (int16) d0
goto pc + d0
``` 
)
3. When the code is an i386 PIC executable and the PC is obtained by calling a special run-time function
`﻿__x86.get_pc_thunk.ax` or the like. 

Naturally, the existing implementation can be improved to handle all the cases above. The question is whether this is the right approach to take, or whether a more general way of obtaining the possible jump destinations can be devised.

Some binary analysis tools implement Value Set Analysis to attack this problem. This approach represents the possible values in memory and registers as Strided Intervals, and simulates the execution of the program by updating the value sets for each memory location and register. The hope is that faithful simulation will result in a strided interval of possible jump targets at the point of the indirect instruction. The seminal paper is here: http://research.cs.wisc.edu/wpis/papers/wysinwyx.final.pdf and another VSA-related paper is here: http://www.isis.vanderbilt.edu/sites/default/files/2_paper.pdf. Implementing this would be a very nice enhancement to Reko but would require some serious time committment from the implementor.

**Comment by uxmal** [comment]
The new implementation appears to handle different variants of indirect jumps better. Please do test this on your own binary/ies and report any issues.
