### ISSUE TITLE
Unable to cast object of type 'Reko.ImageLoaders.Omf.OmfLoader' to type 'Reko.Core.Loading.ImageLoader'

### ISSUE THREAD

**Issue by mrkite** [uxmal/reko#1331]
Trying to open a library created by Turbo Assembler gives an error.

Unable to cast object of type 'Reko.ImageLoaders.Omf.OmfLoader' to type 'Reko.Core.Loading.ImageLoader'

Version 0.11.4.0 on Win 11.

**Comment by uxmal** [comment]
I don't think I have such a binary in my collection. Would it be possible to provide the library? You can reach out to me on discord if need be.

**Comment by mrkite** [comment]
The s3m library from the Second Reality demo is an example:

https://github.com/mtuomi/SecondReality/blob/master/MAIN/STMIK.300

**Comment by uxmal** [comment]
Commit ac45b10 addresses this crash. Note that Reko cannot determine what the types of the symbols are without assistance from the user: there is no way to distinguish between code and data based on the data in the .obj file. Please open a separate issue if you want to discuss / improve this.

Fresh binaries have been built by the Continuous Integration actions. See the `Actions` tab, look for `Artifacts`.
