### ISSUE TITLE
reko crash during "Finish Decompilation" step with Alone in the Dark

### ISSUE THREAD

**Issue by tigrouind** [uxmal/reko#1344]
I'm trying to decompile Alone in the Dark (1992) executable (INDARK.EXE).
AFAIK it has been compiled with Borland C++

After opening the file everything is fine, it can even see the function names retrieved from debug info.

However, after clicking on "Finish Decompilation" it crashes.
[analysis_99_crash.txt](https://github.com/uxmal/reko/files/15186352/analysis_99_crash.txt)

**Comment by uxmal** [comment]
@tigrouind: thanks for reporting this. To save time, can you provide the executable? I don't need any of the assets of the game, just the `INDARK.EXE` file.

**Comment by tigrouind** [comment]
[INDARK.zip](https://github.com/uxmal/reko/files/15195012/INDARK.zip) it is.

**Comment by tigrouind** [comment]
@uxmal : [INDARK.zip](https://github.com/uxmal/reko/files/15203362/INDARK.zip)

**Comment by uxmal** [comment]
The cause of the crash has been fixed. However, there are several other lesser issues that make Reko's output less than optimal. I will continue looking at these other issues.
