### ISSUE TITLE
Use user defined global variables to discover new entry points

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#137]
Python sample contains array of PyMethodDef structs:

   ```
   static PyMethodDef methods[] = {
        { "sum",     py_sum,     METH_VARARGS,   "sum(a, b) = a + b" },
        { "dif",     py_dif,     METH_VARARGS,   "dif(a, b) = a - b" },
        { "div",     py_div,     METH_VARARGS,   "div(a, b) = a / b" },
        { "fdiv",    py_fdiv,    METH_VARARGS,   "fdiv(a, b) = a / b" },
        { NULL,      NULL,       0,              NULL },
        { "unused",  py_unused,  METH_VARARGS,   "unused" },
    };
   ```
Also project file contains user-defined global variable
```
      <global>
        <Address>10003010</Address>
        <arr length="5">
          <type>PyMethodDef</type>
        </arr>
        <Name>methods</Name>
      </global>
```

These data are enough for Reko to discover 4 new entry points: py_sum, py_dif, py_div, py_fdiv
I have crude implementation of GlobalDataScanner 47a56df. I will improve it and do PR.

**Comment by uxmal** [comment]
Look at `TypedConstantRewriter` for inspiration. Also, `Scanner` is spelled `Scanner` :-)

**Comment by ptomin** [comment]
Not sure that TypedConstantRewriter is appropriate place for it. I think it should be done at scanning phase

**Comment by uxmal** [comment]
I'm just saying that both classes seem to be doing similar things. Once you've done your work, I may refactor them to capitalize on commonalities; don't let me distract you for the time being. 

Any pointers to functions that are provided by users should be added to the scanner in the method `DecompilerDriver.ScanProgram(Program program)`. For each procedure, call `scanner.EnqueueUserProcedure`, passing in the address, name, and C signature.

**Comment by uxmal** [comment]
This is now in master. Thanks Pavel!
