### ISSUE TITLE
Function code preview bug

### ISSUE THREAD

**Issue by halsten** [uxmal/reko#14]
Here are the steps to reproduce the bug

1. Click on a any function resolved by Reko (for simplicity chose the first one in the list)
2. In the code preview window, try to drill down in other functions resolved within this function, if it doesn't exist just move to another function in the tree view and try step 2 again.
3. Now go back and click on the first function you chose from step 1 in the functions tree view on the left side. You will notice that the code preview window is not updated and have yo chose another function and then go back to the function chosen in step 1 in order to see the code output again.

**Comment by uxmal** [comment]
I've reproduce this and working on a fix.

**Comment by uxmal** [comment]
I've checked in a fix for this bug. Please confirm and close the issue if you're satisfied, otherwise please reassign to me with commentary.

**Comment by halsten** [comment]
This was fixed and therefore I am closing this issue.
