### ISSUE TITLE
Deserialized function signatures should be __cdecl by default

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#145]
I have converted Python.h to python.xml using c2xml.
c2xml converts C functions with unset calling convention to SerializedSignature with unset calling convention. Then Reko process  SerializedSignature with unset calling convention as stdcall but it should be cdecl. And there are a lot of warnings of the type: "Multiple different values of stack delta in procedure ..."
There are two ways to fix it.
1. Modify c2xml.
2. Modify Reko deserialization.

**Comment by uxmal** [comment]
Leaving out calling convention should cause the deserializer to fall back on the default deserialization for that platform. For Windows, this is __cdecl. If you need to override it, specify ```<signature convention="{convention-name}" /> 

c2xml is doing the right thing, but there is a problem in Reko deserialization, possibly `X86ProcedureDeserializer`, that causes this.

**Comment by ptomin** [comment]
Look https://github.com/uxmal/reko/blob/master/src/Environments/Windows/Win32Platform.cs. The default calling convention is stdapi

**Comment by uxmal** [comment]
That is incorrect; it should be ```__cdecl```. Good catch! See if changing that helps get rid of those warnings.

**Comment by uxmal** [comment]
I'm assuming your commit fixed the issue?

**Comment by ptomin** [comment]
Yes, it could be closed
