### ISSUE TITLE
Load images containing "SEGA" at $100 as Sega Genesis ROMs

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#146]
The Wikibooks page https://en.wikibooks.org/wiki/Genesis_Programming claims that at offset $100 in the ROM, the name of the console should appear, being one of the following: "SEGA GENESIS" or "SEGA MEGA DRIVE".

If this is really true, then Reko's executable signature library could be updated to allow automatic recognition of Sega Genesis ROM by adding a signature map like:
```XML
 <Loader 
    MagicNumber="5345474120"
    Offset="100" 
   Type="Reko.Environments.SegaGenesis.RomLoader,Reko.Environments.SegaGenesis" />
```
@lab313ru: does this sound reasonable?

**Comment by nemerle** [comment]
Looking at:
http://www.zophar.net/fileuploads/2/10614uauyw/Genesis_ROM_Format.txt

This seems pretty likely ?

**Comment by lab313ru** [comment]
Nope. There is no standard for 'SEGA' word there.

**Comment by uxmal** [comment]
@lab313ru: Can you provide an example of a ROM image that doesn't have "SEGA" at offset $0100?

**Comment by lab313ru** [comment]
SEGA at $100 is the [TMSS](http://segaretro.org/TradeMark_Security_System).

**Comment by uxmal** [comment]
That is very useful information. Would you agree that **if** I find "SEGA" at offset $100 of a binary ROM image, then it is **likely** that it is a Sega Genesis image, and Reko can therefore load it automatically without forcing the user to enter all those pesky details). If there is no "SEGA" there, then users can always fall back to "Open As..."

**Comment by lab313ru** [comment]
Hmm... Sounds good.)

**Comment by uxmal** [comment]
This should be trivial to implement.

**Comment by lab313ru** [comment]
Also add check for size of ROM. Minimal size is 0x200.

**Comment by uxmal** [comment]
...on its way.

**Comment by uxmal** [comment]
Fixed in commit 1ceb6c4.

**Comment by lab313ru** [comment]
0x200, but not 200.!=)

**Comment by uxmal** [comment]
Good catch! I was thinking in hexadecimal, I guess
