### ISSUE TITLE
Reko doesn't seem to identify assignments correctly

### ISSUE THREAD

**Issue by halsten** [uxmal/reko#15]
I have written a rather trivial example of doing only assignment statement to different data type sizes to check if Reko identifies them correctly now. However, it seems that its not recognizing the code in the function at all and returns different errors with different compilation types of the sample (Debug/Release). It seems that Reko has problems dealing with debug versions of C/C++ applications compiled with VS for some reason. It could be for the extra code added for the debug version.

**Comment by uxmal** [comment]
I believe this was resolved, @halsten; I'm closing but reopen if this is still an issue.
