### ISSUE TITLE
Better support for vararg functions with format strings

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#154]
Reko should be extended to support vararg functions like `printf(format,...)` and `PyArg_ParseTuple(format,....)` which have format strings that should be parseable to retrieve parameters and their types.

To use this feature, we add a property to the `characteristics` of a procedure called `varargFormat`. This specifies the name of  a class that will be used to parse the format string. The class will be similar to the `ProcedureDeserializer` class and may use many of its services.

Thus, a `PrintfFormatDeserializer` class would be fed the string `"hello, %s, you last logged in %d days ago"`, and deduce that a `char *` and `int` were provided as arguments. A similar parser can be provided for `scanf` and `PyArg_ParseTuple`

**Comment by uxmal** [comment]
@ptomin: you implemented this! Great job!

**Comment by ptomin** [comment]
I have not implemented parser for `PyArg_ParseTuple` yet. I have implemented only one only for `Py_BuildPavue`
