### ISSUE TITLE
Reko should respect the encoding of a binary and allow user to override it

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#167]
Today, Reko is stupid and assumes all string text is encoded as ASCII. The only exception is the ZX81 environment where the Sinclair character set is done correctly. Reko should be able to:

- [ ] automatically detect the codepage if the binary header contains metadata that describes this
- [x] provide a mechanism to allow the user to override the current text encoding (perhaps with a menu like `View` >> `Text Encoding`)
- [ ] save this setting in the *.dcproj file so it can be retrieved later.

**Comment by uxmal** [comment]
This is a lot better:

![cp1251cyrillic](https://cloud.githubusercontent.com/assets/10154465/13924095/4ad56c28-ef83-11e5-9ea0-52835c0e3b7c.png)

**Comment by ptomin** [comment]
Very good!
