### ISSUE TITLE
Improve numeric formatting

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#17]
Currently reko emits numeric constants as 0x[nn..n] where [nn...n] is a string of hexadecimal digits whose length is always the same as the number of nybbles that fit in the datum size in question. That means that a 8-bit byte being assigned looks like this:

`c = 0x01`

while a 64-bit word assignment looks like this

`c = 0x00000000000000001`

which makes it hard to read.

We still want to maintain this form of output in the intermediate code dumps as it makes diagnostics easier, but the final output should look more like what a C programmer would have written. Therefore:

* For character constants, 8- and 16-bit, reko should emit a character constant according to C rules:

```C
c1 = 'a';  // instead of 0x65
c2 = '\n' // instead of 0x10
c3 = '\xFF'; // instrad of 0xFF
wc4 = L'\uFEFF'; // instead of 0xFEFF
```

* For numeric values, use an entropic measurement to see if the numeric representation has less entropy in hexadecimal rather than decimal, and if so, emit them in hex. Unsigned numbers will have a bias towards hexadecimal while signed numbers will have a bias toward decimal.

```C
w1 = 0x7FFFFFFF;
w2 = 10000;  // not 2710
w3 = 1000;   // Not 3E8
```

**Comment by mewmew** [comment]
> For numeric values, use an entropic measurement to see if the numeric representation has less entropy in hexadecimal rather than decimal, and if so, emit them in hex. Unsigned numbers will have a bias towards hexadecimal while signed numbers will have a bias toward decimal.

Thanks for sharing this idea! I really like your creative thought process.

**Comment by uxmal** [comment]
This has been implemented today and seems to work. A 32-bit word with decimal value 100 will rendered as `100`, but the decimal value 256 will be rendered as `0x0100`.  @Halsten: you've been asking for this for a long time, hope you're happy!

**Comment by uxmal** [comment]
Dang. `0xFFFFFFE` when `uint32_t` should probably be `~0x01`, while when `int32_t` should be `-2`. Reopening

**Comment by uxmal** [comment]
Better now
