### ISSUE TITLE
opening elf sparc binary in reko decompiler

### ISSUE THREAD

**Issue by usman77q** [uxmal/reko#170]
when i open elf sparc binary in reko decompiler following message comes 'an internal error occurred. object reference not set to an instance of an object'

kindly advise

**Comment by uxmal** [comment]
Thanks for reporting this error. I need to look at your binary to see what is going on. I recommend that you upload the binary to some file hosting site, like dropbox, and then provide me with a link so I can download it for analysis.

**Comment by usman77q** [comment]
Hello,Thank you,file attached.

Date: Wed, 23 Mar 2016 00:00:54 -0700

**Comment by uxmal** [comment]
Status: this file is an object file, with no program headers. I need to modify the ELF image loader to handle this case, and that may take a while.

**Comment by usman77q** [comment]
thank you i am waiting.
many thanks for your help and time.

**Comment by usman77q** [comment]
Dear Sir,
Hello, sorry to disturb you. how is the work going.

**Comment by uxmal** [comment]
Reko can now open ELF relocatable files. Your object file contains two functions which depend on other functions not supplied. 

Reko is still under development, and there are more issues here. Please file separate issues as you encounter them.
