### ISSUE TITLE
errors opening the reko-decompiler.sln solution file with Visual Studio 2015

### ISSUE THREAD

**Issue by usman77q** [uxmal/reko#187]
Dear Sir,
I opened the reko-decompiler.sln solution file with Visual Studio 2015, but got following warnings at start:- 
******************************************************************
Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - WixInstaller, "K:\Softwares\REKO\reko-master\src\WixInstaller\WixInstaller.wixproj"
	 - WixInstaller-2012, "K:\Softwares\REKO\reko-master\src\WixInstaller\WixInstaller-2012.wixproj"
WixInstaller
Message
WixInstaller\WixInstaller.wixproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=558818&projecttype=930C7802-8A8C-48F9-8165-68863BCCD9DD
WixInstaller-2012
Message
WixInstaller\WixInstaller-2012.wixproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=558818&projecttype=930C7802-8A8C-48F9-8165-68863BCCD9DD
***********************************************************************
Also after building when i go to Debug 'start without debugging' i get following error:-

A project with an output type of class library cannot be started directly. In order to debug this project, add an executable project to this solution which references the library project. Set the executable project as the startup project.

**Comment by uxmal** [comment]
You can ignore the WixInstaller projects; they only come into play if you are planning on creating an installer for reko. 

The README.md file states:

> The solution folder `Drivers` contains the executables that act as user interfaces: `WindowsDecompiler` is the GUI client for Windows; `MonoDecompiler` is the GUI client for Mono users; `CmdLine` is a command line driver.

Accordingly, make `WindowsDecompiler` your default startup project (since you're running Visual Studio and not MonoDevelop) and start the project.
