### ISSUE TITLE
Edit procedure declaration failed after rescan

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#209]
To reproduce
1. Open project
2. Scan
3. Restart
4. Scan again
5. Open combined code view
6. Execute "Edit declaration" context menu item
The exception will be thrown.

The reason seems to be not cleared image map items (not CombinedCodeViewInteractor code). This block items contains procedures from previous scan. So `program.GetProcedureAddress(proc)` returns null

**Comment by uxmal** [comment]
What exception is being thrown, exactly? I'm not seeing this on my machine.

**Comment by ptomin** [comment]
System.ArgumentNullException at DeclarationFormInteractor.cs:87

**Comment by ptomin** [comment]
Do you do theses steps exactly? What text is shown in declaration text box?

**Comment by ptomin** [comment]
Branch should be nested-textModel, of course

**Comment by uxmal** [comment]
Never mind, I have it reproducing now.

**Comment by uxmal** [comment]
The base issue appears to be fixed. However, the reproduction steps above now cause an error. See #226 for details.

**Comment by ptomin** [comment]
User global variables loaded from project file are not shown now. Project loader should put them to ImageSymbols instead of ImageMap

**Comment by uxmal** [comment]
ImageSymbols are such symbols that came directly from the image. User globals are "overrides"  specified by the user. The scanner should mix these together appropriate and populate the image map. I'll reopen the issue and work on improving this.

**Comment by uxmal** [comment]
Yes, this makes more sense. BuildImageMap can now be re-used when the user restarts the decompilation.

**Comment by ptomin** [comment]
> BuildImageMap can now be re-used
It is actually used in Program.Restart

**Comment by uxmal** [comment]
Looks good, then. Have you tested that a manual restart works fine? If so, time for a PR.

**Comment by ptomin** [comment]
User global variables are kept after restart. But Reko fails to reconstruct data types on PySample after rescan. ArgumentException was thrown at TypeStore. But maybe it is another issue

**Comment by uxmal** [comment]
Yes, this a separate issue. I suspect somewhere there is a `Constant` which survives `Program.Reset` and which has a reference to old data. We could close this one and open a new one that more accurately reflects the problem at hand. Your call, Pavel.

**Comment by ptomin** [comment]
I have open #236. But #234 is more interesting for me at the moment than #236. John, what do you think about #234?
