### ISSUE TITLE
Heuristics scanning roadplan

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#21]
Reko almost always fails to recover all of the code of a binary. Being able to do so in general would be tantamount to being able to distinguish code from data, and therefore crack the Halting Problem. Even though this is impossible, Reko can make a good effort at recovering as much as it can automatically to save human users the bother of wallowing through code dumps. 

In Reko, the scanner is the stage which discovers code and rewrites it to an architecture-neutral RTL form. Today the scanner is recursive descent, with some hacks to manage jump tables. It should be possible to substitute another scanner that does more analyis of the binary to try to find other code that it can't prove to be reachable using the original recursive descent.

Heuristic scanning is the term I'm using for this approach. I'm writing a new scanner implementation, in some parts based on [Static Disassembly of Obfuscated Binaries](https://www.cs.ucsb.edu/~chris/research/doc/usenix04_disasm.pdf). 

Some of this is already in place, but now I need to implement an efficient Trie to collect statistics on the binary that has been scanned so far, or even use statistics from a corpus of existing binaries. Once the trie is implemented, and the corresponding InstructionComparer, it can collect statistics on commonly encountered basic block and procedure beginnings. These will be used in the implementation of the heuristic determination of function locations.

**Comment by nemerle** [comment]
Additional source of information for the scanner: higher level information - given a function known to be taking a function pointer as an argument - add those arguments to scanner's target queue

**Comment by uxmal** [comment]
Well, the `scanner-development` branch was finally merged into the `master` branch last week. It incorporates most of the work above. Basically, about 98% of all code in a non-obfuscated binary should be retrievable now without human assistance. Chasing function pointers is done by the `DataScanner` class.
