### ISSUE TITLE
"Edit Declaration" on a procedure always proposes "fn100010000"

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#226]
While working on the fix to #209, I noticed that "Edit Declaration" seems to fail always:

1. Open "pySample.dcproject" in Reko GUI
2. Scan the binary
3. Click on, say, `fn100011E9` in the project browser
4. On the right pane of the combined code view, right-click on the procedure's name `fn100011E9` and select "Edit declaration" in the menu.

Result:
The declaration editor shows `fn10001000`

Expected:
The declaration editor to show `fn100011E9`

**Comment by uxmal** [comment]
Pavel, do you think you can look into this one?

**Comment by ptomin** [comment]
Now it shows declaration for procedure/variable at the current cursor position at left panel. It does that even if context menu was called at the right panel
Do you think it is not correct?
What should be done to fix it? Disable "Edit Declaration" menu item at the rigth panel? Or show declaration for procedure body at cursor of the right panel? Or maybe show declaration for procedure call at cursor?

**Comment by uxmal** [comment]
My expectation is that if you right-click on something, and get a context menu, the command I choose should act on that something. Since the name of a procedure in the codeView (right side) is stored in a textspan tag, it should be doable to retrieve the selected tag, and then from there see if it is a Procedure.

This pre-supposes that you can quickly ask the TextView "give me all tags in the current selection". Do you feel brave enough to write such a method, or would you prefer me to do it? :-)

**Comment by ptomin** [comment]
GetTagFromPoint method could be used

**Comment by uxmal** [comment]
That's the one

**Comment by ptomin** [comment]
OK. I'll try to fix it
