### ISSUE TITLE
Data flow analysis binds user-defined procedure arguments incorrectly

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#228]
I have created sample to reproduce it (9e113d0)
it outputs `test1(ebp, dwArg00, argc, argv)` but it should be something like ﻿`test1(argv[0], argc, "test123", 1.0)`
If CallRewriter is modified so that it creates ApplicationBuilder with ensureVariables flag set to false then it works fine. But many unit test are failed in this case.

**Comment by ptomin** [comment]
I think, the reason is that the CallSite.StackDepthOnEntry is not set before running CalRewriter. So there are 2 possible fixes:
1. Calculate CallSite.StackDepthOnEntry before running CalRewriter
2. Replace calls to applications for user defined procedures at the scanning phase in the same way as external procedures

John, what do you think about it?

**Comment by uxmal** [comment]
If  the `BlockWorkItem` knows the signature of a user procedure when it encounters a `RtlCall`, it should be generated as a `Application` immediately rather than a `CallStatement`. I'm surprised this isn't happening today. Similarly, `Scanner.EnsureProcedure` doesn't seem to take into account `User.Procedures` when creating the procedures.

**Comment by uxmal** [comment]
Looks like `RegisterLiveness` is prepared for the changes above. I wonder why I never modified `BlockWorkItem` to deal with this. 

Pavel, is this something you feel comfortable working with or would you like me to jump in and do it? I strongly recommend having unit tests written first before attacking it.

**Comment by uxmal** [comment]
Never mind! I already started on this. Keep an eye on this space....

**Comment by uxmal** [comment]
Pavel: I've created a new branch `issue-228` to track this, along with a solution. Let me know if this works correctly for you.

**Comment by uxmal** [comment]
By the way: is there a PR for 9e113d0 so I can incorporate it into the project?

**Comment by ptomin** [comment]
> By the way: is there a PR for 9e113d0 so I can incorporate it into the project?

I have just created #233

**Comment by uxmal** [comment]
Branch `issue-228` fails on the VCExeSample. 
```
l00401000: error: An error occurred during data flow analysis.
    An error occurred while processing the statement test1(dwLoc14_28, dwLoc10_23, dwLoc0C_20, dwLoc08_18).
       at Reko.Analysis.ValuePropagator.Transform(Statement stm) in D:\dev\uxmal\reko\master\src\Decompiler\Analysis\ValuePropagator.cs:line 81
   at Reko.Analysis.ValuePropagator.Transform() in D:\dev\uxmal\reko\master\src\Decompiler\Analysis\ValuePropagator.cs:line 66
   at Reko.Analysis.DataFlowAnalysis.BuildExpressionTrees() in D:\dev\uxmal\reko\master\src\Decompiler\Analysis\DataFlowAnalysis.cs:line 95
       at Reko.Evaluation.IdConstant.Transform() in D:\dev\uxmal\reko\master\src\Decompiler\Evaluation\IdConstant.cs:line 75
   at Reko.Evaluation.ExpressionSimplifier.VisitIdentifier(Identifier id) in D:\dev\uxmal\reko\master\src\Decompiler\Evaluation\ExpressionSimplifier.cs:line 406
   at Reko.Core.Expressions.Identifier.Accept[T](ExpressionVisitor`1 v) in D:\dev\uxmal\reko\master\src\Core\Expressions\Identifier.cs:line 68
   at Reko.Evaluation.ExpressionSimplifier.VisitApplication(Application appl) in D:\dev\uxmal\reko\master\src\Decompiler\Evaluation\ExpressionSimplifier.cs:line 127
   at Reko.Core.Expressions.Application.Accept[T](ExpressionVisitor`1 v) in D:\dev\uxmal\reko\master\src\Core\Expressions\Application.cs:line 48
   at Reko.Analysis.ValuePropagator.VisitSideEffect(SideEffect side) in D:\dev\uxmal\reko\master\src\Decompiler\Analysis\ValuePropagator.cs:line 144
   at Reko.Core.Code.SideEffect.Accept[T](InstructionVisitor`1 visitor) in D:\dev\uxmal\reko\master\src\Core\Code\SideEffect.cs:line 46
   at Reko.Analysis.ValuePropagator.Transform(Statement stm) in D:\dev\uxmal\reko\master\src\Decompiler\Analysis\ValuePropagator.cs:line 77
```
Working on a fix

**Comment by ptomin** [comment]
Now user procedure binding works fine. Thanks!

But there is conflict between real32 and real64 values

**Comment by uxmal** [comment]
Yep, you've managed to find a bug in the rewriter for the x86 `fstp` instruction. I'm working on it now.

**Comment by ptomin** [comment]
Conflict between real32 and real64 values causes following error:
`Error,l00401000,An error occurred during data flow analysis. An error occurred while processing the statement test1(dwLoc14_28, dwLoc10_23, dwLoc0C_20, dwLoc08_18). Resulting type is (union (real64 u0) (word32 u1)), which isn't supported yet. `
Maybe it is the same error as your error.

**Comment by uxmal** [comment]
It is; I'll have a fix in a minute.

**Comment by ptomin** [comment]
`bug in the rewriter`
Rewriter seems to be correct.
`fld1` should be `<fstack>(real64) = 1(real64)` and it is

**Comment by ptomin** [comment]
﻿`fstp dword ptr [esp]` is rewrited to `[esp](32b) = [fstack](64b)`. It is also correct, I think

**Comment by ptomin** [comment]
>fstp dword ptr [esp] is rewrited to [esp](32b) = [fstack](64b). It is also correct, I think

Though... Maybe `Cast` expression should be used

**Comment by uxmal** [comment]
It should be using a cast. My wife just issued a non maskable interrupt so I will be somewhat delayed :-)

**Comment by uxmal** [comment]
I don't know if you have the equivalent of "[fika](https://en.wikipedia.org/wiki/Fika_%28Sweden%29)" in Russia, but it is a holy sacrament that must not be meddled with.... OK back to `fstp` :-)

**Comment by uxmal** [comment]
Commit fixed the 1fstp` issue. I'm now going to get rid of the `(real32) 1` cast; it should be `1F`.

**Comment by ptomin** [comment]
Shouldn't the same fix be applied to `fld`?

**Comment by uxmal** [comment]
Yep, working on that as well.

**Comment by uxmal** [comment]
For `fld`, we're always widening: the 8087 fpu doesn't have a floating point datatype wider than the 80-bit reals on the FPU stack, so a cast is not needed to adjust the value. All references to the x87 stack should be competely gone by the type Reko does type inference, so this won't be an issue.

**Comment by uxmal** [comment]
Pavel, you're OK with this now? Let me know and I'll merge into master and close.

**Comment by ptomin** [comment]
Nice! It works fine, now. Thanks!
