### ISSUE TITLE
Reko fails to reconstruct data types on PySample after rescan

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#236]
Reko fails to reconstruct data types on PySample after rescan. ArgumentException was thrown at TypeStore.EnsureExpressionTypeVariable method. The line is
`this.usedClasses.Add(tv.Class.Number, tv.Class);`

**Comment by ptomin** [comment]
Fixed by ad56456. Could be closed now, is not it, John?

**Comment by uxmal** [comment]
Let's consider this one complete.
