### ISSUE TITLE
An error occurred while processing instruction at address (Amiga binary)

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#238]
[PPAMI.zip](https://github.com/uxmal/reko/files/262887/PPAMI.zip)

Subj. At some point it cannot "*Analyze dataflow*" because of this error. Address is 0x00000000.

**Comment by uxmal** [comment]
Thanks for this. I'm going away over the weekend but will look at it when I get back.

**Comment by uxmal** [comment]
The more recent builds of reko get a little further, but run into difficulties as described in #90. As mentioned elsewhere, I'm working on the long-term fix on the `scanner-development` branch. As a workaround, try locating procedures in the executable and give them explicit signatures.

**Comment by uxmal** [comment]
Closing this now, as issue #90 is tracking interprocedural jump errors.
