### ISSUE TITLE
Cannot open Options menu

### ISSUE THREAD

**Issue by lab313ru** [uxmal/reko#240]
```
dlg.DisassemblyControl.Model = new DisassemblyTextModel(program, program.SegmentMap.Segments.Values.First());
```
NullReferenceException (**UserPreferencesInteractor.cs**)

**Comment by uxmal** [comment]
@lab313ru: could you provide further details on what you did right befire the crash above?

**Comment by lab313ru** [comment]
Just opening Tools->Options menu.
