### ISSUE TITLE
ExePackLoader failing to unpack

### ISSUE THREAD

**Issue by m-lima** [uxmal/reko#242]
When decompiling a MSDOS 16-bit packed EXE, the `ExePackLoader` failed to properly unpack the binary reporting: 

> Couldn't open file \<FILENAME\>. Sequence contains no elements.

Issue temporarily resolved by using third party unpacker (LZEXE) and passing the unpacked binary to Reko for decompilation.

**Comment by uxmal** [comment]
Could you supply the offending EXE file? I'd like to understand why it is failing.

**Comment by m-lima** [comment]
The binary is attached. I had to remove the .exe extension because gmail
blocks it. You can just put it back.
Some background on it: it is a MS-DOS 16-bit abandonware game from 1988
called Kings of the Beach.
If you wish, you can download the full abandonware package (all
dependencies) at
http://www.abandonia.com/en/games/32/Kings+of+the+Beach.html
The unpacker that I used to bypass Reko's own unpacker was LZEXE (
http://bellard.org/lzexe.html)

Regards,

Marcelo Lima

**Comment by uxmal** [comment]
I'm about to commit a fix that resolves the issue. Are you able to build Reko yourself or do you wish me to create a release for you?

**Comment by m-lima** [comment]
That's great :) And I can build it myself, thanks.

**Comment by uxmal** [comment]
Please test to make sure the issue has been resolved once commit is done. Thanks for your feedback!

**Comment by m-lima** [comment]
Yep. Confirmed to be working. Great job!

Marcelo Lima
