### ISSUE TITLE
Please add instructions how to build from command line 

### ISSUE THREAD

**Issue by pfalcon** [uxmal/reko#246]
If I would install a new IDE to test each new decompiler, I would never test Reko. (Well, I didn't.)

**Comment by uxmal** [comment]
You can build the reko project by issuing the command
```
xbuild Reko-decompiler.sln
```
from the $(Reko)/src directory.

**Comment by uxmal** [comment]
I've modified the README to include the above build instruction. Let me know if you need further elucidation.
