### ISSUE TITLE
Project file loading failed when writing suffix array to file

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#250]
Following error occurred:
`Error,,An internal error occurred. Could not find a part of the path "C:\MyPrograms\git_repos\reko_ptomin\src\Drivers\WindowsDecompiler\bin\Debug\pySample\pySample.dll.sufa-raw.ubj". `

To reproduce it save` *.dcproject` file of pySample to `subjects\PE-x86` and try to load it

**Comment by uxmal** [comment]
Pavel, I'm not sure what your expectation is here. What should Reko do when you intentionally move the dcproj file away from the location where all the files are located?

**Comment by ptomin** [comment]
No, not move.
Reko allows to save projects to arbitrary directories. And they were successfully loaded before you have added writing suffix arrays.
To reproduce it, please exactly do the following steps:
1. Open `subjects\PE-x86\pySample.dll`
2. Press Save button
3. Chose `subjects\PE-x86\` directory in "Save as" dialog
4. Try to open saved project

**Comment by uxmal** [comment]
Ponimaiu. I will look at this in a few hours .

**Comment by ptomin** [comment]
Now, it works. Thanks, John
