### ISSUE TITLE
PE: Section names don't have to be unique, fails with dictionary mapping

### ISSUE THREAD

**Issue by Lukas-Dresel** [uxmal/reko#254]
Section names in PE files are afaik not forced to be unique. I have an executable that has 11 sections of the same name. However, the PE loader uses a SortedDictionary which then invalidly seems to contain only 1 section instead of all 11 since the new section assignments overwrite the previous ones.

**Comment by uxmal** [comment]
Great catch. It turns out that section names are merely "suggestions", and bad guys can set them all to the same name if they wish. Unfortunately, reko may be making a lot of assumtions on section name uniqueness. Will look at this tomorrow.

**Comment by Lukas-Dresel** [comment]
Yeah, that's what the obfuscation scheme on my binary does. On the other hand we can maybe use this as a heuristic for the specific packer of that binary.

**Comment by Lukas-Dresel** [comment]
I'll see if i can figure out what the obfuscation schemes are and if they are automatically "unpackable".

**Comment by uxmal** [comment]
As far as I can gather, loader should avoid making decisions based on section names, as they are purely for human consumption (http://stackoverflow.com/questions/14418153/pe-file-section-names)  However, reko uses them in its user interface and so needs a mechanism to differentiate between sections that have identical names.

**Comment by Lukas-Dresel** [comment]
If you want i can try take a look at it to get started. Since i have the binary here maybe i'll run into other stuff too

**Comment by Lukas-Dresel** [comment]
If you want i can try take a look at it to get started. Since i have the binary here maybe i'll run into other stuff too

**Comment by uxmal** [comment]
Be bold and forge ahead!

Some suggestions: have `PeImageLoader.LoadSections` ensure unique names by checking each loaded section name against a *private* dictionary, and if the name already exists, generate a new one, like "foo_1", "foo_2" etc. 

Add a property `OriginalName` to the internal `PeImageLoader.Section` class and the public `Reko.Core.ImageSegment` class. If `OriginalName` != `Name` the `Reko.Gui.Design.ImageMapSegmentNodeDesigner` class should set `TreeNode.Text` to `Foo_1 (Foo)` (that is, `string.Format("{0} ({1})", segment.Name, segment.OriginalName)` ) rather than simply `segment.Text`.

Those are the major points that come to mind at midnight (!). Let me know how I can help you get going.

**Comment by Lukas-Dresel** [comment]
Okay, so I'll fix some other stuff in the PE section alongside this change too, e.g. that the relocation section is found using the name '.reloc'. A better way of doing it can be found here: 

https://github.com/mohic/Relocation-Section-Editor/blob/master/Relocation%20Section%20Editor/Relocations.cs

They find the offset by looking up the base relocation table directory entry address and finding the section that contains this address. This would allow us to leave the section names completely as 'decoration' for display, which would alleviate the problem. 

We could still have duplicate names be displayed differently, however i would suggest appending the virtual address to the name as that provides more information to the user. But with the above change and moving the sectionMap from a dictionary to something else we would not even need distinct names, the functionality would be independent of the names.

**Comment by uxmal** [comment]
Indeed; line 363 of PeImageLoader.cs loads the base relocation address; we should be using that value instead of looking for ".reloc". Sounds like you're going to be able to submit a PR pretty soon!

**Comment by Lukas-Dresel** [comment]
Fixed.
