### ISSUE TITLE
Questions about type analysis

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#256]
John, could you describe what is `EquivalenceClass`, `TypeVariable` and what is difference between `Expression.TypeVariable.OriginalDataType`, `Expression.TypeVariable.OriginalDataType` and `Expression.TypeVariable.DataType`?

I suppose that `TypeVariable` contains type info was collected during type analysis
`EqivalenceClass` contains set of `TypeVariables` are in different sides of `Assignment` instructions.
`Expression.DataType` is data type was got from `Rewriter`. It should not be changed during type analysis
`Expression.TypeVariable.OriginalDataType` is data type after execution of `ExpressionTypeAscender` and `ExpressionTypeDescender`
`Expression.TypeVariable.DataType` is data type after type inference between members of `EquivalenceClass`

Are my guesses right?

**Comment by uxmal** [comment]
Pavel, I apologize for not responding sooner; I've been bedridden with the flu/grippe. Because this is a wide topic, I'm going to respond in the reko wiki and then link to this issue. Bear with me as I slowly recover my health.

**Comment by ptomin** [comment]
OK, writing it to the wiki will be useful. Get well!

**Comment by uxmal** [comment]
Here is a first draft: https://github.com/uxmal/reko/wiki/Type-Analysis
please let me know how I can clarify it further.

**Comment by ptomin** [comment]
Thanks for description, John!
