### ISSUE TITLE
InvalidCastException in OnScroll in UI controls

### ISSUE THREAD

**Issue by Lukas-Dresel** [uxmal/reko#266]
An InvalidCastException occurs when dragging in the hex views string area.

Reproduce:
1. Start reko
2. Open ~/subjects/PE-x86/VCExeSample/VCExeSample.exe
3. Select some bytes in the hexdump so that they are highlighted in blue (definitely works when selecting multiple lines, sometimes doesn't trigger when only selecting bytes in the first line)
4. Click and drag around in the string representation part of the hexdump
5. Exception happens in Gui/Windows/Controls/DisassemblyControl.cs line 119 OnScroll Method when the Model.CurPosition is cast to Address

**Comment by Lukas-Dresel** [comment]
Similar issues could maybe arise in 

Gui/Windows/Controls/MixedCodeDataControl.cs:
- (74, 46) : addrTop = (Address)Model.CurrentPosition;
- (99, 38) : addrTop = (Address)Model.CurrentPosition;
- (105, 49) : var currentAddress = (Address)Model.CurrentPosition;
- (108, 43) : this.addrTop = (Address)model.CurrentPosition;

Line member (because it is assigned CurrentPosition at Gui\Windows\Controls\TextView.cs line 410)
- (131, 43) : return (Address)anchorPos.Line;

Gui\Windows\Controls\NestedTextModel.cs 
- (86, 38) : Location loc = (Location)CurrentPosition;

Gui\Windows\Controls\DisassemblyControl.cs 
- (119, 41) : topAddress = (Address)Model.CurrentPosition;

**Comment by Lukas-Dresel** [comment]
Btw, the problem is that EmptyEditorModel.CurrentPosition cannot be cast to Address which it tries to do because:

Gui\Windows\Controls\TextViewModel.cs - (102,23) :
```
        public object CurrentPosition { get { return this; } }
        public object StartPosition { get { return this; } }
        public object EndPosition{ get { return this; } }
```

**Comment by uxmal** [comment]
The issue is in MemoryControl.  I hope to have a fix tomorrow.

**Comment by Lukas-Dresel** [comment]
For reference, see pull request and John's explanation at #269

**Comment by uxmal** [comment]
Haven't heard from anyone about this for a while, so closing for now. If problem persists, please do reopen the issue.
