### ISSUE TITLE
Add a simple .gitattributes file and normalize all sources line endings ?

### ISSUE THREAD

**Issue by nemerle** [uxmal/reko#27]
This should help somewhat with running tests on linux, since some files have windows line endings and use raw-literals thus embedding \r\n in the expected output ( not sure of the proper c# nomenclature for those ```@" ... " ``` things :smile: )

something like :
```
*        text=auto
*.cs     text diff=csharp
```

**Comment by uxmal** [comment]
Feel free to do what you need to make the tests work on Linux.

**Comment by nemerle** [comment]
Ok I'll follow instructions from https://help.github.com/articles/dealing-with-line-endings/ 
The commit might be pretty large ?

**Comment by uxmal** [comment]
I'll create a branch, "line-endings". Once you commit, make a pull request to that branch, and I can verify that nothing's broken on the Windows end.

**Comment by nemerle** [comment]
Will do

**Comment by uxmal** [comment]
Branch created. Have fun!

**Comment by nemerle** [comment]
And pull request already in the queue

**Comment by uxmal** [comment]
Confirming all unit tests pass in Windows.
