### ISSUE TITLE
PE Image loader couldn't find relocations after fix of #254

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#274]
Reko generates incorrect output for `PE-x86/RussianText` and `PE-x86/pySample` regression tests after fix of #254. I think, the reason is  that relocation section is not found.
@Lukas-Dresel Could you look at it?

**Comment by Lukas-Dresel** [comment]
Sure, but i'll only be able to work on it after tuesday, have to study until then.

**Comment by Lukas-Dresel** [comment]
Should be fixed as of PR #277, closing.

**Comment by Lukas-Dresel** [comment]
Can this be closed?

**Comment by ptomin** [comment]
Yes, the issue is fixed now. Thanks, Lukas.
