### ISSUE TITLE
Consider expanding flag groups during SSA

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#332]
Today reko models the effects of CPU instructions on condition code registers by grouping the bits into a _flag group_ and then creating an assignment to the flag group bits from a pseudo-expression `ConditionOf`. For instance, the x86 instruction:

```
    add eax,ebx
```

will be translated to the following IR code:

```
    eax = eax + ebx
    SZCO = cond(eax)
```

Here, `SZCO` is a combination (group) of the flags affected by the `add` operation. The `cond` is used as an optimization. We want to avoid spending too much work on condition codes since the majority of condition code assignments in most programs are dead code. That is, subsequent instructions will overwrite them before they are read by, say, branch statements.

However, reko requires more granular control of the flags when it does SSA analysis and tracking of flag register livenesses when crossing procedure boundaries. It wants the flag registers expanded at those process boundaries, and this is done in my copy the `analysis-development` branch -- not yet pushed to github. This results in the following x86 code:

```
    add eax, ebx
    ret
```

being converted to 

```
    eax_2 = eax + ebx
    SCZO_3 = cond(eax_2)
    return
exit_block:
    S_4 = SCZO_3
    C_5 = SCZO_3
    Z_6 = SCZO_3
    O_7 = SCZO_3
    use eax_2
    use S_4
    use C_5
    use Z_6
    use O_7
```

The assignments in the exit block are needed so that the `use` statements can keep the registers alive until Reko can prove the flag register are dead or alive on procedure exit. But notice how the assignments are type-incorrect: we're assigning a bit from a group of bits. If we carry out value propagation and dead code elimination we get:

```
    eax_2 = eax + ebx
    SCZO_3 = cond(eax_2)
    return
exit_block:
    use eax_2
    use SCZO_3
    use SCZO_3
    use SCZO_3
    use SCZO_3
```

which is a disaster: we've now lost track 

Reko doesn't have today a way to model the required bit-extraction from a group of bits. I could add an expression like `bitcast` or `bitextract`, but I really don't want the IR to become more complex. An alternative is: during SSA tranformation, expand the flag group -- but only when the flag group cannot be proven to be dead. This would make the above example result in:

```
    eax_2 = eax + ebx
    S_4 = cond(eax_2)
    C_5 = cond(eax_2)
    Z_6 = cond(eax_2)
    O_7 = cond(eax_2)
    return
exit_block:
    use eax_2
    use S_4
    use C_5
    use Z_6
    use O_7
```

which will be a lot easier to handle in later passes of the reko analysis phase.

**Comment by ptomin** [comment]
> Reko doesn't have today a way to model the required bit-extraction from a group of bits

What about `slice`?

**Comment by uxmal** [comment]
I'm glad you're awake, @ptomin; I had dismissed `slice` because I'd somehow convinced myself it only dealt in byte quantities, but we have a `PrimitiveType.Bool` and `slice` has bit resolution. I will tinker with it and see if I can fix the issue.

**Comment by uxmal** [comment]
Looks like flag groups are behaving correctly on the `analysis-development`  branch now.
