### ISSUE TITLE
Ordinal global imports not supported?

### ISSUE THREAD

**Issue by NurudinImsirovic** [uxmal/reko#334]
While I was doing a decompile on DLL or EXE file (I don't really remember). I got an message saying "Ordinal global imports not supported."

Here is the image source:
http://i.imgur.com/lKYWG15.jpg

Also, my reko.config says "WinSpecFileLoader" but it still seems to output the error message.

**Comment by uxmal** [comment]
Thanks for the report; I'll see what the issue is behind the error message. Do you remember if this was an x86, x86-64 or AMD binary?

Bear in mind that if your binary has ordinal inputs, but no additional metadata, Reko will generate very "stupid" stubs for the ordinal imports -- since it has no way of knowing the names of the functions or the parameters they require. Reko does support providing extra metadata in various ways, if you need help with that please let me know.

**Comment by uxmal** [comment]
Ah, these are global _variables_ that are being imported. Reko currently doesn't support this as the message suggests. I will see if I can implement this feature for you in a reasonable amount of time.

**Comment by NurudinImsirovic** [comment]
It was x86. I tried to decompile a game DLL.

**Comment by uxmal** [comment]
It seems you'll want: 1) in the GUI, a list of all imports the binary has, both functions and globals, and 2) some way to give them user-specified metadata (in case the DLL the imports refer to isn't a "standard" one.

**Comment by NurudinImsirovic** [comment]
Sorry I didn't told you that Reko sometimes crashes due to this message error. It could be Windows Compatibility issue or something. I don't know.

**Comment by uxmal** [comment]
You mean the Reko gui dies completely? That's very unusual. It would be very helpful if I had access to the binary that's causing the trouble, but I realize IP rights prevent you from providitng it. I'll try to create a reproduction of this during the weekend if time allows.

**Comment by NurudinImsirovic** [comment]
Okay. Thanks a lot :)

**Comment by uxmal** [comment]
@NurudinImsirovic: are you able to build Reko yourself, or do you need a build from me. I'd like you to show me a screen shot of the newly added "Imports" node after you open your binary with commit d4db2ce applied. If you cannot build yourself, let me know and I will provide you with a build to work with.

**Comment by uxmal** [comment]
Also, I recommend hanging out in https://gitter.im/uxmal/reko so the process is a little faster than bouncing comments back and forth in this issue,

**Comment by uxmal** [comment]
@NurudinImsirovic: I haven't heard from you in a while. Commit 58cfee0dadd066ce0d0e53baacb2ca9de3c87a4e adds support for viewing the imports, and I've verified that Reko can load global data imports. If you're able to build Reko yourself, please do so and check to see if this gets further. If you're not able to build Reko, please let me know; I can do a release for you with this new feature. 

I'm closing this issue now; if you beleive it's not complete, please don't hesitate to reopen it.
