### ISSUE TITLE
mathematical operations with Motorola 68K architecture

### ISSUE THREAD

**Issue by scofield972** [uxmal/reko#351]
There is a problem to work with mathematical operations with Motorola 68K architecture.

I tried to write a program with FPU instructions set and it dropped me message like "Instruction does not support yet".
In C++ it expected to be a “long double” type.

For example:
fadd, fmul, fdiv, fmove, fadd, sub, cmp and etc.

Is there way to fix this issue ? Can I add support with FPU operation in Motorola 68K ?
How I can do it ?

Does reko decompiler have support in FPU instructions in other architectures (like x86, arm, and etc. )

**Comment by uxmal** [comment]
Reko does have support for FPU operations and FPU data types in the architectures that it has implemented (x86, Sparc, ARM, VAX for instanece(. I've just never had access to an 68k binary that contained valid FPU code, so it hasn't been tested. 

As far as I can tell, there is support for *disassembling* 68k FADD (see line 1637 of `M68kDisassembler.cs`), but the logic needed to "lift" the `FADD` machine instruction into a sequence of low-level RTL instructions has not been written. It should be easy enough to add it.

If you feel comfortable adding support for those missing youself, start by looking at the unit test `Reko.UnitTests.Arch.M68k.RewriterTests.cs`. For example, here is the unit test for rewriting `DIVS`:
```C#
    [Test]
        public void M68krw_divs()
        {
            Rewrite(0x81C1);                // divs
            AssertCode(
                "0|L--|00010000(2): 6 instructions",
                "1|L--|v3 = (int16) (d0 % (word16) d1)",
                "2|L--|v4 = (int16) (d0 / (word16) d1)",
                "3|L--|d0 = DPB(d0, v3, 16)",
                "4|L--|d0 = DPB(d0, v4, 0)",
                "5|L--|VZN = cond(v4)",
                "6|L--|C = false");
        }
```
You'd need to write something similar for `FADD` rewriter, where you'd have to generate the RTL for the addition itself as well as RTL to simulate the setting of the FPSR. I'd be glad to assist you if you want to hack code.

If you're not ready to do coding, give me a few days to look at this.

**Comment by uxmal** [comment]
I hang out in https://gitter.im/uxmal/reko if you wish to reach me directly for questions etc.

**Comment by uxmal** [comment]
@scofield972: it would be awesome if you could provide an unencumebered _smallish_ M68k binary that uses the FPU instructions. Even better, if possible, provide the ASM or high-level language source for the FPU sources, so we have something to compare against. As an example, look at https://github.com/uxmal/reko/tree/master/subjects/PE-x86/VCExeSample and its `src` subdirectory. Having a sample binary would help a lot.

**Comment by scofield972** [comment]
Hi friend,
I wrote code for you using FPU instructions as you wanted.

You can download from[ here](http://www20.zippyshare.com/v/PRMNmsJD/file.html),

please update,
Thanks !

**Comment by scofield972** [comment]
Hi friend,
If you need more examples (complex and simply) of source code and binaries,
tell me and I will provide you....
I wanna note that the unconditional and conditional jumps also have FPU instruction
for example: FBGT, FBEQ, FBLT, FBNE and etc.

Thanks !

**Comment by uxmal** [comment]
There is an another issue at play: Reko doesn't currently support ELF files for m68k. Shouldn't be too hard to add as well.

**Comment by uxmal** [comment]
Is the ELF binary targeted to a particular OS?

**Comment by uxmal** [comment]
I will let you know if I need more; for now I have plenty to work with.

**Comment by scofield972** [comment]
Hi uxmal,

Never mind for me with format it will work this is not the challange,
The exisitng of functionality will be more important,
Therefore I need your help here,
The reason for it I have the ability to format what I want and I usually extracting the pure code from the file into a new file and then executes the decompilation process.

This is the command im sending to decompiler while  code.binary is the pure code:
rekoDecompile.rexe --arch m68k --base 0 --entry start_function --heuristic shingle code.binary

**Comment by uxmal** [comment]
@scofield972: no problems, the two commits above have added an ELF loader that seems to work with your binary. I will work on implementing the functions over the weekend. I assume you are able to build Reko yourself -- or would you like me to make a release for you once this issue is completed?

**Comment by scofield972** [comment]
Hi uxmal,

Yes please,
once issue will completed.

Thanks,

**Comment by uxmal** [comment]
@scofield972: reko decompiles the sample you provided with no exceptions thrown. The generated code is still flawed, but showing promise. I will merge the changes into master. To confirm: you can't build reko yourself so you would like me to make a release?

**Comment by scofield972** [comment]
Yes, please.
What do you mean "The generated code is still flawed" ?
Are you continue to work on some issues or you close it ?
Thanks !!!

**Comment by uxmal** [comment]
I could create a release right now. However there are a bunch of places where Reko fails when dealing with doubles and long doubles. For instance, the following copy:
```asm
fmove.d fp3, $-8(a6)
move.l $-8(a6),d0
move.l $-4(a6),d1
move.l d0, $80400000
move.l d1, $80400004
```
which copies `fp3` to global variable `$80400000` cannot be handled properly by Reko right now. 

I will make a 0.6.1.1 release for you so that you can "play" with what I've got and open a separate issue to track the issue above.

**Comment by uxmal** [comment]
@scofield972 : do I have your permission to add the sample binary you supplied to the Reko project?

**Comment by scofield972** [comment]
Hi uxmal,
At first, I wanna say thanks a lot !
Yes, I allow you to add sample binary No problem !
If you need another examples I can provide.
 
I built the last branch in my computer and saw the issues you talking:

```
 fmove.d fp3, $-8(a6) 
 move.l $-8(a6),d0
 move.l $-4(a6),d1
 move.l d0, $80400000
 move.l d1, $80400004
```
It from error massage on first instruction.
So, whats next ? 
Do I can open you separate issue for each ?

Thanks,

**Comment by uxmal** [comment]
Great! I will add it presently.

Generally, the more specific your error reports are, the more helpful they are. Some of the issues I saw are reasonably easily fixed, while others will have to wait until the `analysis-branch` has been completed.

**Comment by scofield972** [comment]
Hi uxmal,
Ok, no problem !
I will wait you finish to handling known issues,
Once you finish notify me and I will test it before you release the new branch
Is it planning ok for you ?

Thanks,

**Comment by uxmal** [comment]
@scofield972: I've just pushed everything to `master`. Look through the generated `.c` file in and see if you can catch the worst 3 errors. It's really helpful if you can show the original asm and the generated C to indicate what you're expecting, and what you actually see. Here is an example:

> The original machine code was:
> `move.l d0,$40(a1)`
> I expected the following C code:
> `a1->dw0040 = d0`
> but Reko generated
> `Mem[a4 + 0x00000040:word32] = d0`

Writing the issues this way helps me a lot in isolating and debugging.

**Comment by uxmal** [comment]
I'm closing this now, as (some of) the FPU instructions have been implemented and it should be fairly easy to add more as needed. I encourage you to expand your source file to add more instructions -- particularly the `FBxx` jumps.
