### ISSUE TITLE
Reko does not respect the little-endian byte order flag in the ELF header for MIPS

### ISSUE THREAD

**Issue by Lukas-Dresel** [uxmal/reko#353]
When trying to load a reversing binary from tuctf ([binary](https://github.com/team-bitskrieg/CTF-writeups/tree/master/tuctf/RE%20for%2050%20plz), [writeup](https://github.com/team-bitskrieg/CTF-writeups/tree/master/tuctf/RE%20for%2050%20plz)) in reko i get many errors about not being able to rewrite instruction 'illegal'. 

This happens for examplebecause reko attempts to decode the instruction at VA 0x004013a8.
Read in little endian the opcode stored in the file there is 0x3c1c004b which is `lui gp, 0x4b`
However, reko reads 0x4b001c3c which is invalid.

It turns out that the MipsDisassembler is instantiated [here](https://github.com/uxmal/reko/blob/master/src/Core/Program.cs#L287) from the architecture the loader of the binary set. 

However, the ELF loader in always sets the architecture to big-endian [here](https://github.com/uxmal/reko/blob/master/src/ImageLoaders/Elf/ElfLoader.cs#L148)

This clashes with the instruction opcodes that are now being read out in big-endian when the file format indicates that the opcodes are instead encoded in little endian.

**Comment by Lukas-Dresel** [comment]
I would attempt a fix, but I am not sure if the solution of setting the Architecture to MipsLe32Architecture is a valid solution because I'm not sure how other things related to endian-ness are then handled.

**Comment by uxmal** [comment]
It's father's day here so my family won't let me at the keyboard today. However if you're willing to try the following:
1. In the class `ElfLoader` add a `endianness` parameter in the constructor. In the derived classes `ElfLoader32` and `ElfLoader64` add the `endianness` too.
2. In the class `ElfImageLoader` when creating the above derived classes, pass the endianness  which was read from the ELF header.
3. In the class `ElfLoader32` when creating the processor architecture,  use the endianness to choose between `mips-le-32` and `mips-be-32`

Reko should be able to deal with endianness after that.

**Comment by Lukas-Dresel** [comment]
It currently has no support for a ProcedureSerializer for mips-le-32, should the one for big endian work?

**Comment by uxmal** [comment]
The procedure serializer used by mips-be-32 should be reusable by mips-le-32.

**Comment by Lukas-Dresel** [comment]
Apart from the fact that some instructions are unimplemented, e.g. rdhwr it looks good so far now.

**Comment by uxmal** [comment]
If you're feeling adventurous, try changing the `MipsDisassembler` and `MipsRewriter` classes to support the missing instructions. Start by copying working unit tests in the `MipsDisassemblerTests` and `MipsRewriterTests` classes and modify them appropriately.

**Comment by Lukas-Dresel** [comment]
I am currently looking into that, however that will unfortunately have to wait until tomorrow. However, from what I have seen so far, rdhwr is used for thread local storage but was designed to be able to get the index of the cpu the current process is running on for example. Any idea how we wanna represent that in reko? 

Do we wanna add corresponding registers in the registerstorage and have an extra Operand type for hardware registers?

**Comment by Lukas-Dresel** [comment]
About the Unit tests, the endianness in the ElfImageLoader is set to private but the method When_CreateLoader32 in the ElfLoader32Tests directly creates a new ElfLoader32 object(`this.el32 = new ElfLoader32(eil, eih, this.bytes);)`. Can I just replace this with `this.eil.CreateLoader()`? Or is there a specific need to initialize it manually?

**Comment by uxmal** [comment]
For now, let `rdhwr` be a pseudoprocedure `__rdhwr`. There are many places where platform- and CPU-specific transforms need to be applied and I haven't finished the design for that yet.

**Comment by uxmal** [comment]
The test fixture is testing the `ElfLoader32` class specifically, so we do want to create instances of `ElfLoad32` explicitly.

You could change signature to `void When_CreateLoader32(bool isBigEndian)` and adjust the code inside the method accordingly. There are two calls to that method in the test suite: one that needs to be little endian and another big endian.

**Comment by uxmal** [comment]
Here is a link to the Linux source file that handles software emulation of the MIPS hardware registers: http://lxr.free-electrons.com/source/arch/mips/kernel/traps.c?v=3.5#L612

**Comment by uxmal** [comment]
You get to close this now, @Lukas-Dresel
