### ISSUE TITLE
Discussion: new popup feature in the mixed dasm/data view

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#371]
Commit 41461c57285b001542c0edbd738fbe764f1b328e introduces a new GUI feature to Reko: a popup window which appears when hovering over addresses. This allows the user to get a preview of the memory area the address points to before clicking on the address actually navigates there. I wanted to put this out there to collect feedback. What do you think?

![image](https://cloud.githubusercontent.com/assets/10154465/20557978/3d55c90a-b16e-11e6-9df5-c94952ecb23f.png)

**Comment by ptomin** [comment]
Good idea. I'll test it when I'll have spare time

**Comment by uxmal** [comment]
Could use some padding along the border -- as does the parent `MixedCodeDataControl`.

**Comment by ptomin** [comment]
I have tested it. This is good feature. For instance it gives me possibility to view string variables without moving current position.
I have suggestions to improve it:
1. Delay before showing preview (like tooltips) to avoid numerous unnecessary showing it when I move mouse in dasm window.
2. Add possibility to resize preview window

**Comment by uxmal** [comment]
Pavel, I've merged the development branch into `master`. Go ahead and test this to see if it feels OK to you.

**Comment by ptomin** [comment]
Very good, John. Thanks.
I have one more issue. Could preview form size be saved across different showing? So that I'll move mouse to address, then set preferred size, then move mouse to other address and size will be the same as previous.

**Comment by uxmal** [comment]
Should be easy enough to save. I'll work on it tonight.

**Comment by ptomin** [comment]
Very nice! Thanks, John!
