### ISSUE TITLE
Reko should support loading Intel HEX files

### ISSUE THREAD

**Issue by Testato** [uxmal/reko#395]
I tested the AVR8 new support, but the .hex file from one of my project it is not recognized, not in automatic (Open command), and not manually (Open as AVR8)

**Comment by uxmal** [comment]
This is a HEX file, a file format Reko doesn't support yet. I'll change the subject to better indicate what you're asking for. It shouldn't be too hard to write a HEX parser (https://en.wikipedia.org/wiki/Intel_HEX)

**Comment by Testato** [comment]
So witvh AVR8 format is supported ?

**Comment by uxmal** [comment]
You should be able to decode AVR8 instructions. It's not tested very heavily however. You're more than likely going to find bugs once you load the image.

**Comment by Testato** [comment]
You mean .elf ?
Normally the gcc avr compiler produce hex, .eep for eeprom inside chip and .elf that nclude symbol for hw debugger

**Comment by uxmal** [comment]
The HEX file very likely contains executable code. HEX files are typically used to write EPROMS for embedded processors.

**Comment by Testato** [comment]
For example, atmega 328 have 32kB of flash memory, that is ised for execute the fw, and 2kB of eeprom, for not volatile data. AVR8 MCU cannot execute the code from eeprom.

So the pnly two file that we can load in Reko is the .hex or .elf.
On which file did you the test ?

**Comment by uxmal** [comment]
I'm working on the HEX file now: here.s the result of loading from it:
![image](https://cloud.githubusercontent.com/assets/10154465/21893236/908841e6-d8da-11e6-9a72-f5b16683a018.png)
as you can see, many of the instructions are not implemented yet.  ELF files should load fine; Reko has a sample $(Reko)/subjects/Elf/AVR.

**Comment by uxmal** [comment]
Commit  ae2b3d15 implemented Intel HEX file loading, using the `Open As...` dialog. There is still a lot AVR8 instructions that aren't handled; a separate issue.

**Comment by Testato** [comment]
i attached here a simple blink project, for your testing
inside zip there is .elf - .hex - .eep
[blink.zip](https://github.com/uxmal/reko/files/702074/blink.zip)

**Comment by uxmal** [comment]
Reko now supports reading Hex files and a larger set of AVR instructions after commit dc9ae3d.

**Comment by Testato** [comment]
new version for testing ? :-)

**Comment by uxmal** [comment]
Try this private drop: https://dl.dropboxusercontent.com/u/26234462/0.6.2.1/reko-0.6.2.0.msi
