### ISSUE TITLE
Add 64 bit Reko builds

### ISSUE THREAD

**Issue by smx-smx** [uxmal/reko#462]
Having 64bit Reko builds will avoid exceptions related to the CLR Heap limit that 32bit builds have

**Comment by uxmal** [comment]
The `interop-development` branch is now yielding 64-bit builds for Mono users. We are unfortunately hampered from bringing this to the Windows users because the Capstone.NET assembly we are depending on only exists in a 32-bit flavor. Work is underway to remove this dependency.

**Comment by uxmal** [comment]
This became available with the release of version 0.8.0.0.
