### ISSUE TITLE
Atari m68k family

### ISSUE THREAD

**Issue by ps68060** [uxmal/reko#463]
I haven't tried a decompiler for years and I was curious to see if Reko can decompile Atari m68k binaries.  I think they are just a.out style binaries but I don't much about the inner workings.

I tried one but it doesn't allow Atari as an option.

**Comment by uxmal** [comment]
If you could provide me with such a binary, I can start looking at what it would take to decompile it.

**Comment by ps68060** [comment]
Did you receive the sample binaries ?

The address had noreply so I wasn't sure it was correct.

**Comment by uxmal** [comment]
No I did not -- perhaps you could use dropbox or some other file sharing method?

**Comment by ps68060** [comment]
You could try some of the items from here:

https://sites.google.com/site/stessential/text-tools/everest

https://github.com/freemint/qed/releases

**Comment by uxmal** [comment]
I'll use the `everest` binary you provided as a sample. It will take me a few days to learn the essentials about TOS to make sure the code => system interface decompiles properly. m68k support should be fairly full-fledged however, so perhaps by next week there will be a prototype. Will you require builds or are you able to build Reko yourself?

**Comment by ps68060** [comment]
Thanks for the quick feedback.

I would need a build (please), I don't have a Windows (C# ?) build environment.

**Comment by uxmal** [comment]
Is an MSI installer OK, or are you running on *ix? If the latter I can supply you with a zip file that should be executable on a system with Mono present.

**Comment by uxmal** [comment]
Sorry for the delay! I just published Reko release 0.7.1.0 which has support for reading Atari TOS binaries. You should be able to read in executables with it. Note that there are some challenges that prevent Reko from properly resolving TOS system calls right now, but you should be able to work around those manually by providing your own signatures to calls. I'm going to add a separate issue to track  this.
