### ISSUE TITLE
Abort the decompilation after a certain amount of time (wall or CPU)

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#466]
Since there is no ulimit -t for windws to limit the maximum amount of cpu time and reko needs a very large amount of time for certain binaries (for example https://github.com/rfalke/decompiler-subjects/blob/master/from_decompile-it.com/elinks/ia32_elf_from_website/subject.exe) it would be nice to have a command line option so that reko aborts the decompilation after the specific time.

**Comment by uxmal** [comment]
Thanks for the feature suggestion and the sample binary, Raimar. I'm currently away on holiday but will look into implementing some wall-clock time type mechanism when I get back next week. I will also look at the provided binary to see if there is anything in particular that is causing reko take so much time to finish running.

**Comment by uxmal** [comment]
As you can see above, I've added a ```--time-limit``` command-line switch to ```decompile.exe```. Are you able to build yourself or do you want a release of Reko from me to test this?

**Comment by rfalke** [comment]
Since running the software on windows is a always a hassle (disable anti-virus software because of the malware subjects, lack of ulimit) I ran Reko after some struggling now successful on linux (https://github.com/rfalke/decompiler-subjects/commit/230ec96795d37b81fd1a4244822698c59efa642a). So this issue is now a bit obsolete.

So no new version required.

**Comment by uxmal** [comment]
Fine. The feature is implemented now, so I will close the issue.
