### ISSUE TITLE
Mips PE Executable

### ISSUE THREAD

**Issue by junalmeida** [uxmal/reko#47]
Cannot decompile mips exe. 
Error message: unsupported machine type 0x0166   in PE header.

I read somewhere that reko support MIPS partially. Is it true?

**Comment by uxmal** [comment]
Indeed, support for the MIPS architecture is only partial. If you can provide me with a MIPS PE executable, I can work on getting reko to the point where it reaches parity with the other  architectures.

**Comment by uxmal** [comment]
Support for MIPS PE architecture has been added. Naturally, there is much more support needed to properly decompile MIPS code. Please experiment with reko and report issues as you find them.
