### ISSUE TITLE
Implement support for floating-point literals > 64 bits

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#485]
The analysis-branch has started discovering loads of x86 80-bit literals in some of the programs in `subjects`. It promptly throws an exception when encountering them In addition, m68k likes to store its 80-bit literals in 96-bit literals. Once started down this path, we might as well implement 128-bit literals for POWER9. I'm unaware of any architecture supporting 256-bit floats.

Reko should be able to load these literals and render them in decimal format. At this time, no support for arithmetic will be attempted.

**Comment by uxmal** [comment]
I have almost completed this item but want to prioritize `analysis-development` branch first.

**Comment by smx-smx** [comment]
This will also be beneficial for:
- SSE registers - 128 bit (XMM0...XMM7 in 32bit) + (XMM8...XMM15 in 64bit mode) + (XMM16...XMM31 with AVX512 in 64bit mode)
- AVX regieters - 256 bit (YMM0...YMM15 in 32bit) + (YMM16...YMM31 in 64bit mode)
- AVX512 registers - 512 bit (ZMM0...ZMM31)
