### ISSUE TITLE
Loading of Mac ClassicOS resource fork

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#488]
Wondering what is the method for loading a file that is just the binary contents of the resource fork.

**Comment by uxmal** [comment]
Because of the peculiarities of the Data/Resource layout of classic MacOS files, Reko currently only supports reading them from binhex + compressed files. However, if you have a file that just contains the contents of a resource fork, perhaps you could share it with me -- either here or via another channel -- and I could take a look at what it would take to extend Reko to make it able to read data directly from such files.

**Comment by uxmal** [comment]
Alternatively, if you're willing to code in C#, you can look at the class `Reko.Environment.MacOS.ResourceFork`, located [here](../blob/master/src/Environments/MacOS/ResourceFork.cs). To create a `ResourceFork` object, you need to supply the contents of the resource fork as a `byte[]` and an instance of the `M68kProcessorArchitecture` class:
```C#
var bytes = File.ReadAllBytes("resource_fork.bin");
var arch = new M68kArchitecture();
var rsrc = new ResourceFork(bytes, arch);
```
The `ResourceFork.Dump()` method is a quick way to look at the contents of a resource fork once it's been loaded.

Let me know if you have further questions on this topic!

**Comment by gbody** [comment]
Thanks for that info.
I created a hexbin 4 file from the original file on the Mac and tried to opening that with Reko, and received a divide by zero error. The original file doesn't have a Data Fork, the length of Resource Fork is 74344 bytes. I have attached the binhex file that I tried to open.

**Comment by uxmal** [comment]
@gbody: I'm not seeing the attachment. Could you send it separately to johnkal AT gmail DOT com ?

**Comment by gbody** [comment]
[LinkIIGS.Hqx.txt](https://github.com/uxmal/reko/files/1410988/LinkIIGS.Hqx.txt)

**Comment by uxmal** [comment]
I've reproduced the division by zero exception. I will look into this issue to see if I can resolve it quickly.

**Comment by uxmal** [comment]
@gbody: I've fixed the zero division issue you reported. I'm able to see the contents of the file, including quite a few MacOS Toolbox calls. The MacOS support for Reko is still quite immature (e.g. see https://github.com/uxmal/reko/wiki/Supported-binaries) but it was able to read your binary fine after the fix I made above.

Are you able to build Reko yourself or you need a build?

**Comment by gbody** [comment]
Not setup for building yet, so if you could provide a build that would be great

**Comment by uxmal** [comment]
Release 0.7.2.0 was just made. Go here to fetch an installer: https://github.com/uxmal/reko/releases/tag/version-0.7.2.0
