### ISSUE TITLE
Possible bug in X86Rewriter.EmitCopy ?

### ISSUE THREAD

**Issue by chostelet** [uxmal/reko#494]
Hello,
Reviewing the latest master code, I think there is a potential bug in the EmitCopy(MachineOperand opDst, Expression src, CopyFlags flags) method with the iDst variable being null in the following code excerpt:
            var idDst = dst as Identifier;
            if (idDst != null || (flags & CopyFlags.ForceBreak) == 0)
            {
                assignToRegister(idDst, src);
            }

assignToRegister() may received a null iDst and fails.

**Comment by uxmal** [comment]
Thanks for this report, it sure looks like a logic bug. But more interestingly, looking closer at the code reveals that every single caller of `EmitCopy` (either direct or indirect callers) always pass `CopyFlags.ForceBreak`, which explains why this error has never been reported before. I will rewrite the code accordingly.

**Comment by uxmal** [comment]
Commit 9d7e4c9 fixes the problem. Thanks again for your report!

**Comment by chostelet** [comment]
You’ve been fast !! :)

 

--

Christian HOSTELET - Grenoble

 

De : John Källén [mailto:notifications@github.com] 
Envoyé : vendredi 17 novembre 2017 07:54
À : uxmal/reko <reko@noreply.github.com>
Cc : chostelet <christian.hostelet@free.fr>; Author <author@noreply.github.com>
Objet : Re: [uxmal/reko] Possible bug in X86Rewriter.EmitCopy ? (#494)

 

Commit  <https://github.com/uxmal/reko/commit/9d7e4c9829f1543d7454e47d079f9d35dfdb4a21> 9d7e4c9 fixes the problem. Thanks again for your report!
