### ISSUE TITLE
Potential bug in X86Assembler.cs/ProcessInOut (line #386) ?

### ISSUE THREAD

**Issue by chostelet** [uxmal/reko#496]
Hello,

I fear I found a logic bug in the 'ProcessInOut()' method in 'X86Asssembler.cs'
If 'regOpPort' is null (not being a RegisterOperand) then line #429 will possibly fail accessing 'regOpPort.Width' in the call to 'EmitOpcode'.
Shouldn't it be replaced by 'immOp.Width' ?

Regards

**Comment by uxmal** [comment]
Merci Christian! I have reproduced the error condition. A fix will be coming in shortly.

**Comment by uxmal** [comment]
When using `in` or `out` instructions with the port number as a constant (not the `[e]dx` register), there is no need for a size override. I changed the code accordingly.
