### ISSUE TITLE
MacOS Classic - Constants of type bcui24 are not supported. 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#503]
Just wondering how this should be handled.
When trying to reconstruct data types I received a number of errors:
eg. 0010F638,Error while analyzing trashed registers. Constants of type bcui24 are not supported. 
I know the early Mac roms used 24 bit pointers, prior to the clean 32 bit roms.

**Comment by uxmal** [comment]
Well I actually think this may be a bug in the ExpressionSimplifier class. I'm investigating this now to see what is generating these 24-bit values.

**Comment by uxmal** [comment]
I have a fix for this on my machine. I still have a few more MacOS + m68k issues to clear up but it's on it's way.

**Comment by gbody** [comment]
Look forward to it

**Comment by uxmal** [comment]
With the most recent push to the Reko repository, this error should be gone.
