### ISSUE TITLE
MacOS Classic - expand Application global data into A5 World

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#504]
Is it possible to get the application global data expanded into the A5World.
This would allow negative references relative to (A5) to be looked up 

The resource %A5Init has routines used to setup initial application global data in memory.

Based on the previous code provided
The routine _DATAINIT starts with the following code.
﻿0010FC02 48 E7 7F F8   movem.l    d1-d7/a0-a4,-(a7)
0010FC06 49 FA 01 A8  lea    0010FDB0,a4 
The offset at 0010FC08 provides a relative address to a header for setting up the global app data.

The header at 0010FDB0
Long - Size below A5, start of global application data
Long - Bank/segment ?? size (00010000) 64KB
Long - offset to start of compressed global data from the start of the header
Long - offset to relocation data from the start of the header
Long - ???? 000000000

uncompress_world routine - passed ptrs to start of compressed data and bottom of below_A5World 
Compressed data
set Repeat count = 1, reset after each completed copy cycle
byte  lower 4 bits number of words to copy from compressed data
         upper 4 bits number of words to skip in global application data space
if either value is 0 then run length value used is in bytes, and if the new run length value for copy is 0 then it's the end of compression data.

get_rl routine
Run length if required is next byte(s). 
0xxxxxxx -  0-$7F 
10xxxxxx - 0 - $3FFF ( run length and $3F + next byte, 14 bits)
110xxxxx - 0 - $1FFFFF ( run length and $1F + next two bytes, 21 bits)
1110xxxx - next 4 bytes, 32 bits
1111xxxx -  get both new runtime length copy in bytes and new runtime length repeat count

**Comment by uxmal** [comment]
One approach that might be viable is to inject an RTL statement `a5 = a5world` into the beginning of each procedure, using `MacOS.InjectProcedureEntryStatements(Procedure proc, Address addr, CodeEmitter emitter)` as the MacOS ABI specifies that a5 must point to the a5 world at all times. `a5world` is a global identifier of type `A5World_t *` (read "pointer to the A5World`), which will contain, at the appropriate negative offsets, the globals you seek. I'll play with this and see what results.

**Comment by uxmal** [comment]
Commit 25b35a8781fbc5f7134b34fad47cd6157b14d56c implemented the above suggestion. The `a5` register is now set to point to a structure of type `A5World_t` at the beginning of every function. However, there is something going on in the type inference module that is causing references to `a5` to not resolve correctly. I'm leaving this issue open as I figure out what is going wrong.

**Comment by uxmal** [comment]
The most recent commits now show references to the a5 world.
