### ISSUE TITLE
Discussion: how aggressive should reko be with constant propagation?

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#51]
@halsten gave me a binary that was decompiled by reko in an amusing way. In pseudo-C, we have:

```C
int foo() {
    return 0;
}
```
and the call site:
```C
    // other code elided
   global_var = foo();
```
The compiler settings @halsten used generated the following code:
```asm
_foo proc
    xor eax,eax
    ret
    endp
```
and the call site:
```asm
    ;; other code elided
    call _foo
    mov ds:[0x12341234],eax
``` 

When reko does its global "registers trashed" analysis, it discovers that at the end of `_foo`, the EAX register is always 0. This constant 0 is then propagated to all call sites of `_foo`, so that they become (in asm format, reko uses its internal RTL format as you may be aware):
```
    call _foo
    mov dword ptr ds:[0x12341234],0   ; <-- Constant 0 propagated
```
After the registers modified pass, reko performs a liveness analysis to see what values are live-in and live-out of procedures. Since all the callers of `_foo` will have a 0 constant propagated, EAX will never be live-out from `_foo`. Therefore, reko assumes that EAX is dead at the exit of `_foo`, and changes the code to:
```asm
_foo proc
    ret
    endp
```
When reko later translates to C we get
```
void foo() {
}
```
and 
```
    foo();
    g_dw12341234 = 0;
```

To an external observer, the behavior of the decompiled program is the same as the original program; they both modify the same global variable and set it to the same value. However, the decompiled code is not the same as the source code.

So why does reko do this aggressive constant propagation? One of the binaries I have been training on -- which alas I can't share due to legal encumberances -- is a x86 real-mode binary which does this:

```asm
some_func proc 
    ;;; lots of stuff not relevant to the discussion
    push 0x1234
    pop ds    ; Set DS to 0x1234
   ret
```
and the (only) calling function looks something like this:
```asm
calling_func proc
    push 0x1234
    pop ds
    ;; lots of code using DS = 0x1234
    push cs
    pop ds              ; DS no longer is 0x1234
    ;; code using altered value of DS
    call some_func
    ;;; after the call, DS is back to 0x1234
    ;; code that relies on DS being 0x1234 follows
    ;;...then later, a computed goto appears
   mov bx,[some_global_var]
   add bx,bx
   jmp ds:[bx+0x5678]   ;; jump to the bx'th offset
```
Rather than the usual `PUSH DS // stuff // POP DS` idiom for saving and restoring a register value, the programmers relied on `some_func` returning a constant value in DS, and a few instructions later there is a computed goto where the entries in the jump table is referred to using DS.

If reko didn't know that `some_proc` returned a constant 0x1234 in DS, it couldn't resolve the jump table -- basically just has to give up or ask the oracle (read "user") for help. By doing the constant propagation, reko can resolve the jump table by itself.

The question is whether reko should be doing the aggressive constant propagation, given that it may result in the decompiled files not matching the original source.. My position is that as long as the program's behavior is still correct, it's OK to do this. So much information is lost in the compilation process anyway that you will never get 100% source recovery anyway.

If a user really wants to preserve the original signature, they can override this either in the GUI or in the `*.dcproj` file.That is, they can force the signature of `_foo` in the first example to be `int foo()`, and reko should oblige by generating the expected 
```C
int foo() {
    return 0;
}
```

 I'd like to hear what other people think of this. Is my position acceptable here, or should reko behave differently?

**Comment by halsten** [comment]
I believe that achieving the same behavior should suffice of decompilation vs source. As you mentioned that the compilation process will result in losing a lot of information anyway so I suggest we let reko does its aggressive constant propagation and *iif* required by the user to override such settings he/she should have the ability to do so via function declaration as an option. In my personal opinion you can't match decompilation with the original source in most cases at least, however we can still do that in some basic scenarios.

**Comment by uxmal** [comment]
We will go with this for the time being; arguments above seem enough for me.
