### ISSUE TITLE
Wrong link in the 'About' window

### ISSUE THREAD

**Issue by insolor** [uxmal/reko#52]
In the 'About' window there is a link:
`https://github/uxmal/reko`
(github without .com)
![screenshot_1](https://cloud.githubusercontent.com/assets/2442833/9834401/8ad5c9d0-59bf-11e5-8d87-c7a11a0781df.png)
Right link:
`https://github.com/uxmal/reko`

**Comment by uxmal** [comment]
Eagle eye! Fixed in the commit above.
