### ISSUE TITLE
Short circuit expressions not detected

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#529]
There is now a test subject at https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/condition_structure/ia32_elf which enumerates all possible ways (for a certain number of conditions) to create a complex short circuit condition.

Reko:
* creates nested ifs where && and/or || should be used
* creates gotos (maybe because of the uncommon block order)
* doesn't show the puts() arguments (maybe already fixed)

Reko 0.7.2:
```
// 0804867A: void test_2_blocks_2_targets_direct_variant_2()
void test_2_blocks_2_targets_direct_variant_2()
{
        if (globals->dw808A0A4 == 0x00)
        {
                if (globals->dw808A0A8 == 0x00)
                {
                        fn080482E0();
l0804867C:
                        fn080482E0();
                        return;
                }
        }
        fn080482E0();
        goto l0804867C;
}
```

Holdec
```
// address: 0804867a.0
// full-signature: func(test_2_blocks_2_targets_direct_variant_2, return=[<int(undef, 4),null,unknown>], parameter=[], varargs=false)
d4 test_2_blocks_2_targets_direct_variant_2(void)
{
  if(g_0x0808a0a4 != 0 || g_0x0808a0a8 != 0) {
    (void) puts("then/else block 5");
  } else {
    (void) puts("then/else block 4");
  }
  (void) puts("return block");
  return 0;
}
```

**Comment by uxmal** [comment]
I've reproduced this on the most recent builds of Reko.

**Comment by uxmal** [comment]
Well, I wish all bugfixes were that easy: swapping the order of two transformations. The fix generally improves the output quality of the code as seen in the regression tests.

@rfalke: to get the most recent builds, @smx-smx changed the Reko AppVeyor build so that the output is saved as an artifact. Try this link to download an MSI file:
https://ci.appveyor.com/project/uxmal/reko/build/artifacts

**Comment by rfalke** [comment]
The MSI download works as expected.

However also with reko-0.7.2.0-f51c658d81 there are still gotos. See for example test_3_blocks_2_targets_variant_4()
