### ISSUE TITLE
NE executable loading not implemented

### ISSUE THREAD

**Issue by moparisthebest** [uxmal/reko#53]
I am trying to see if I can get any code from an [ancient 16-bit win 3.1 exe](https://github.com/mordra/CoTWjs/blob/master/stuff/Castle1/CASTLE1.EXE) but am getting the above error, is there anything I can do to use reko on this?

**Comment by uxmal** [comment]
If you can bear with perhaps a week's wait, I can implement NE loading for you. Thanks for the binary reference, that will come in handy for testing.

**Comment by uxmal** [comment]
You can also open the binary as a "raw" file, by using `File` > `Open as...` but without proper support for resolving those segments in the binary, the results will be disappointing.

**Comment by moparisthebest** [comment]
NE loading would be great!  I'll link you to a few things that might be helpful in doing so:

  * [Another binary for testing](https://github.com/mordra/CoTWjs/blob/master/stuff/Castle2/CASTLE2.EXE)
  * http://wiki.osdev.org/NE
  * http://www.program-transformation.org/Transform/NeFormat

The only thing I've actually found so far capable of loading NE is wine, which runs these perfectly, but on the other hand digging through the wine code to figure out how doesn't sound like a fun time. :)

**Comment by uxmal** [comment]
Googlable information about Win16 is hard to find -- Wine does seem to be the best source. I've started on the loader. I may have been a little optimistic in my time estimate above, but watch the reko project for updates the coming days.

**Comment by moparisthebest** [comment]
Looks like [HT Editor](https://github.com/sebastianbiallas/ht) also has support for NE files.

**Comment by uxmal** [comment]
OK, I've got it to the point where it is able to load CASTLE.EXE and show all the different segments -- see commit f0a9624853fd593f45ee3380e497aa8e537b562b. I hope you are able to build reko yourself as I'm about to leave for a few days and won't be able to make a proper test release until next week.

**Comment by moparisthebest** [comment]
Thanks much, it does load the executable just fine!  It does crash on decompilation now though, with these two errors:

```
An error occurred while reconstructing types. Unable to cast object of type 'Reko.Core.Types.EquivalenceClass' to type 'Reko.Core.Types.StructureType'.
An error occurred while reconstructing types. Unable to cast object of type 'Reko.Core.Types.EquivalenceClass' to type 'Reko.Core.Types.Pointer'.
```

**Comment by uxmal** [comment]
Thanks for the report.  I'm out of town over the weekend but will attend to it when I get back.

**Comment by uxmal** [comment]
I'm closing this as the functionality is implemented.  I've opened a few separate issues to cover defects that I've discovered since. If you find more please open separate issues.
