### ISSUE TITLE
PseudoProcedure signatures are not always set

### ISSUE THREAD

**Issue by Kalmalyzer** [uxmal/reko#535]
(Pardon for filing a lot of bugs lately. I'm trying to find a way to disassemble an 1MB binary, and reko _may_ fit the bill - so I'm trying all avenues - each way displays a different stumbling block.)

When I try the latest version of what's on the analysis-development branch, I run into problems with some parts of the code assuming that all procs have Signatures - but `PseudoProcedure`s do not always have this. On the main branch there are null guards at https://github.com/uxmal/reko/blob/master/src/Decompiler/Typing/EquivalenceClassBuilder.cs#L340 but those do not exist on the analysis-development branch since 8424d1b648c721bc4c1f9641bfeb9edbe106097e .

When I disassemble M68K binaries containing ROL/ROR instructions, the `EquivalenceClassBuilder.VisitProcedure()` calls fail on the analysis-development branch since for the ROL/ROR operations, `proc.Signature == null`.

I have attached some example files that demonstrate this. `test.rol.s` is a hand-written  example file. `test.rol.exe` is the same file after compiling/linking. `test.rol.dis` is reko output when I fed `test.rol.exe` into it.

I'm not sure how to build a good unit test for this. I tried switching to the analysis-development branch and running the regression tests but there were lots of changes there. I can create a test case if I get some tips on where I should insert it (either in form of binary file or as source level unit test).

[test.rol.zip](https://github.com/uxmal/reko/files/1603506/test.rol.zip)

**Comment by uxmal** [comment]
I will look at this in a few hours.  And please don't be shy about reporting issues. It's fantastic to have feedback from users

**Comment by uxmal** [comment]
BTW: the `analysis-development` branch is a hard-hat area. Unless you're really involved in SSA (Static Single Assignment) on partial control flow graphs, I suggest you avoid it for a while :-)

**Comment by Kalmalyzer** [comment]
Well, I've tried the regular branch a bit, but it fails a lot in TrashedRegisterFinder - where some blocks in the middle of a function end up with empty `ctx.RegisterState[]`. Based on comments in #245 I thought it was better to try to see if it's feasible to get that branch to disassemble/decompile the whole binary, than to get the main branch to process the whole binary.

What's your take - which branch should I focus my efforts on, if I continue this?

**Comment by uxmal** [comment]
I just committed some changes that address the original issue: missing `ProcedureSignature`s in `PseudoProcedure`s. However, the issue you are seeing in the `master` branch is not related. As in my comment above, I'd like to understand what is destroying the `RegisterState` in the `TrashedRegisterFinder` and see if we can find a resolution.
