### ISSUE TITLE
Should encode chars >0x7f correctly in string literals

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#543]
Example: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/string_literals/ia32_elf
Version: 0.7.2.0-f51c658d81

Output: `puts("hex=0x80 dec=128 char=?FINI");` (looks for me like a normal question mark)

Expected: `puts("hex=0x80 dec=128 char=\200FINI");`  (or hex encoding)

**Comment by uxmal** [comment]
This was fixed in commit a7eb82a5.
