### ISSUE TITLE
38 compile error in VS 2012 (pro & express)

### ISSUE THREAD

**Issue by beebob23c** [uxmal/reko#55]
downloaded a zip snapshot today

accepted "update" option. select "build solution". 38 compiler errors. I think you need better build instructions?

Error	13	The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	23
Error	14	The type or namespace name 'TestFixtureAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	31
Error	15	The type or namespace name 'TestFixture' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	31
Error	16	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	42
Error	17	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	42
Error	18	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	49
Error	19	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	49
Error	20	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	56
Error	21	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	56
Error	22	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	63
Error	23	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	63
Error	24	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	71
Error	25	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	71
Error	26	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	79
Error	27	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	79
Error	28	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	89
Error	29	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	89
Error	30	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	97
Error	31	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	97
Error	32	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	105
Error	33	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	105
Error	34	The type or namespace name 'TestAttribute' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	113
Error	35	The type or namespace name 'Test' could not be found (are you missing a using directive or an assembly reference?)	C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\MsPrintfFormatParser.Tests.cs	113
Error	42	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\bin\Debug\Reko.Environments.Win32.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\ImageLoaders\MzExe\CSC
Error	62	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\bin\Debug\Reko.Environments.Win32.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\ImageLoaders\OdbgScript\CSC
Error	63	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\ImageLoaders\MzExe\bin\Debug\Reko.ImageLoaders.MzExe.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\ImageLoaders\OdbgScript\CSC
Error	65	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\bin\Debug\Reko.Environments.Win32.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\WindowsItp\CSC
Error	66	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\ImageLoaders\MzExe\bin\Debug\Reko.ImageLoaders.MzExe.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\WindowsItp\CSC
Error	67	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\ImageLoaders\OdbgScript\bin\Debug\Reko.ImageLoaders.OdbgScript.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\WindowsItp\CSC
Error	68	error C2275: 'LPSTR' : illegal use of this type as an expression	C:\Users\beebob\Desktop\reko-master\src\Samples\win32api\win32api.c	8
Error	69	error C2146: syntax error : missing ';' before identifier 'next'	C:\Users\beebob\Desktop\reko-master\src\Samples\win32api\win32api.c	8
Error	70	error C2065: 'next' : undeclared identifier	C:\Users\beebob\Desktop\reko-master\src\Samples\win32api\win32api.c	8
Error	72	error C2065: 'next' : undeclared identifier	C:\Users\beebob\Desktop\reko-master\src\Samples\win32api\win32api.c	9
Error	73	error C2100: illegal indirection	C:\Users\beebob\Desktop\reko-master\src\Samples\win32api\win32api.c	9
Error	74	error MSB3073: The command "nmake  /f makefile /C /D Configuration=Debug" exited with code 2.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.MakeFile.Targets	38
Error	75	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\Environments\Win32\bin\Debug\Reko.Environments.Win32.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\UnitTests\CSC
Error	76	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\ImageLoaders\MzExe\bin\Debug\Reko.ImageLoaders.MzExe.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\UnitTests\CSC
Error	77	Metadata file 'C:\Users\beebob\Desktop\reko-master\src\ImageLoaders\MzExe\bin\Debug\Reko.ImageLoaders.MzExe.dll' could not be found	C:\Users\beebob\Desktop\reko-master\src\Drivers\MonoDecompiler\CSC

**Comment by halsten** [comment]
Just delete the old reference for NUnit, then re-add it again. I had such problem before and that took care of it. Re-compile again and you should have no problems after that.

**Comment by beebob23c** [comment]
delete and re-add where? I've never dealt with C# before, only C.

And it doesn't seem like that will fix things like this, will it?
Error 68 error C2275: 'LPSTR' : illegal use of this type as an expression C:\Users\beebob\Desktop\reko-master\src\Samples\win32api\win32api.c 8

**Comment by halsten** [comment]
For the first compilation problem, I am positive about the fix cause I had the same issue. If you will notice also that NUnit will have a yellow exclamation mark on the reference for the project "Win32", if you remove that reference then re-add it again it should compile properly. The other you can ignore by just choosing to ignore the "samples" from the build phase for the whole solution, you wouldn't need it.

**Comment by beebob23c** [comment]
The correct answer, when someone says "I've never dealt with C# before" is to provide explicit instructions as follows (not to make them waste 15 minutes figuring out something you could have just said in 1 minute):

Expand the Environments->Win32->References folder.
Right click nunit.framework, and select remove
Right click references, and select Add Reference
Select Browse, and navigate to reko/external/nunit directory

So only samples errors remain after that, and I will ignore them
