### ISSUE TITLE
MacOS Classic - Errors during Reconstructing Data Types

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#550]
Using the source from the current master repository, I am getting the following two errors when Reconstructing Data Types.

Error,0010ABF4,An error occurred while processing the statement branch d0_149 - d0_160 >=u 0x00000000 l0010ACEE. Pulling difference ui32 and ptr32 
I guess this is the same/similar to issue #533.

Error,,Error when reconstructing types. PprPrimitiveReplacer found a cycle in type graph. 
Not sure if this is causes early termination

**Comment by uxmal** [comment]
I'm trying to understand the cause of the "cycle in type graph" error first, as it is more serious. Once that is cleared up I can continue with the other error, which is indeed related to #533.

**Comment by uxmal** [comment]
I've been able to reproduce the cycle error with a much smaller sample:
```
asl.l #2,d0
move.l a4,(d0,a4)
```
Now to fix it...

**Comment by uxmal** [comment]
...and the cycle issue is fixed. Next we tackle the remaining exceptions in the run.

**Comment by gbody** [comment]
The recent work appears to have cleared the error 
Error,0010ABF4,An error occurred while processing the statement branch d0_149 - d0_160 >=u 0x00000000 l0010ACEE. Pulling difference ui32 and ptr32
