### ISSUE TITLE
Enhanced 'AssertCode' method for 'ArchTestBase'

### ISSUE THREAD

**Issue by chostelet** [uxmal/reko#556]
Hi,
To help testing my PIC18Rewriter, I've added an other **AssertCode()** method - into my tests - with an additional string parameter. See below for what I've done.
This permits to pass a message that can help determine the actual assertion which failed in a test method with numerous AssertCode() calls.
As an example of usage:
```C#
   Rewrite(0x4000);
   AssertCodeEnh("0x4000", "0|L---|00000200(2): 1 instructions", "1|L--|nop");
   Rewrite(0x5000);
   AssertCodeEnh("0x5000", "0|L---|00000200(2): 1 instructions", "1|L--|div");
   Rewrite(0x0007);
   AssertCodeEnh("0x0007", "0|L---|00000200(2): 1 instructions", "1|L--|WREG = __daw(WREG, C, DC)()");
```
Thus my suggestion to add an other protected method with this **mesg** parameter, and uses this mesg string with all occurrences of Assert.xxx in **AssertCode()** method.
Here is my new AssertCode() version (defined in my tests only.
```C#
protected void AssertCodeEnh(string mesg, params string[] expected)
{
    int i = 0;
    var frame = Architecture.CreateFrame();
    var host = CreateRewriterHost();
    var rewriter = GetInstructionStream(frame, host).GetEnumerator();
    while (i < expected.Length && rewriter.MoveNext())
    {
        Assert.AreEqual(expected[i], $"{i}|{RtlInstruction.FormatClass(rewriter.Current.Class)}|{rewriter.Current}", mesg);
        ++i;
        var ee = rewriter.Current.Instructions.OfType<RtlInstruction>().GetEnumerator();
        while (i < expected.Length && ee.MoveNext())
        {
             Assert.AreEqual(expected[i], $"{i}|{RtlInstruction.FormatClass(ee.Current.Class)}|{ee.Current}", mesg);
             ++i;
        }
    }
    Assert.AreEqual(expected.Length, i, "Expected " + expected.Length + " instructions.", mesg);
    Assert.IsFalse(rewriter.MoveNext(), "More instructions were emitted than were expected.", mesg);
}
```
This user message would appears in the "Test failed" Message in addition to the NUnit message.

**Comment by uxmal** [comment]
Why not just create a separate unit test for each byte sequence you're rewriting? That way you avoid having to change the API at all. Besides which, it is good practice to unit test one thing at a time, to make it easier to spot what's wrong:

```C#
[Test]
public void Pic18rw_nop()
{
    Rewrite(0x4000);
    AssertCodeEnh("0|L---|00000200(2): 1 instructions", "1|L--|nop");
}

[Test]
public void Pic18rw_div()
{
    Rewrite(0x5000);
    AssertCodeEnh("0|L---|00000200(2): 1 instructions", "1|L--|div");
}
```

**Comment by chostelet** [comment]
John,

This is indeed what I’ve done. But, for each instruction, there are variations (addressing mode et destination result).

For example:

```C#
[Test]
public void Rewriter_Trad_Trad_BTFSC()
{
    ExecTest(Words(0xB000),
        "0|T--|00000200(2): 1 instructions",
            "1|T--|if ((Mem0[0x00:byte] & 0x01) == 0x00) branch 00000402"
        );
    ExecTest(Words(0xB102),
        "0|T--|00000200(2): 1 instructions",
            "1|T--|if ((Mem0[(BSR << 0x08) + 0x02:byte] & 0x01) == 0x00) branch 0x00000402"
        );
}
``` 
As a work around, I’ve defined another AssertCode() method in my PIC18RewriterTestsBase class which mimics the original AssertCode() with the addition of this message.
The message itself (only shown in case of test failure) is formatted to show the PIC model, the PIC execution mode and the faulty binary instruction words.
For example:

**Message:   PIC18F1220/Traditional[B000]
   Expected string length 61 but was 59. Strings differ at index 52.
   Expected: "1|T--|if ((Mem0[(BSR << 0x08) + 0x02:byte] & 0x01) == 0x00) branch 0x00000402"
   But was:   "1|T--|if ((Mem0[(BSR << 0x08) + 0x02:byte] & 0x01) == 0x00) branch 00000402"
   ------------------------------------------------------------------ ----------------------^**

Hope this clarify reason of my suggestion.

**Comment by uxmal** [comment]
Then I think you can leave this as a PIC-specific extension. No need to force the over 1000 existing unit tests to change.

**Comment by chostelet** [comment]
There would be no need to change any existing test unit. My suggestion was to *add* another protected AssertCode() method in ArchTestBase. Leaving the existing AssertCode untouched.
Anyway I close this comment :-)
