### ISSUE TITLE
doesn't document where the applications are built to

### ISSUE THREAD

**Issue by beebob23c** [uxmal/reko#56]
"A command-line, a Windows GUI, and a ASP.NET front end exist at the time of writing. "

So where do they actually get built to? Please update the main description to indicate.

Or better yet, just provide pre-built binaries for people who just want to see what the tool is capable of, without spending an hour installing VS + trying to compile

**Comment by halsten** [comment]
After your compilation was successful you should go to `Src/Drivers` and there should be all built binaries depending on which front-end you are looking for you will find it there. For example:
1. `src\Drivers\WindowsDecompiler\bin` will contain the built binaries for the GUI
2. `\src\Drivers\WebSite\bin` will contain the built binaries for the website (thought I never really used it before so I can't comment on that much)
3. `\src\Drivers\CmdLine\bin` will contain the built binaries for the command line

I agree, there should be more documentation regarding that as well as a smooth compilation process.

However, the pre-built binaries are already provided with an installer as well located at (https://github.com/uxmal/reko/releases)

I hope that helps.

**Comment by beebob23c** [comment]
thank you. I do kernel drivers, and I would not have thought to look for executables under "drivers" (also I would say there should be a link to the releases on the main readme.md)
