### ISSUE TITLE
Reko.Arch.Avr missing in MSI build

### ISSUE THREAD

**Issue by kalej** [uxmal/reko#563]
not actually a bug, but a thing to fix

**Comment by uxmal** [comment]
Thanks for reporting this. A new CI build of Reko will be available here shortly: https://ci.appveyor.com/project/uxmal/reko/build/artifacts 

Out of curiosity, are you intending to work with some AVR binaries with Reko? If so, I wonder if you could provide me with a sample file or two so I can use it to improve the quality of the output.

**Comment by uxmal** [comment]
Looks like the build is broken. Hang on.

**Comment by uxmal** [comment]
OK, it's working now.

**Comment by kalej** [comment]
Uploaded and archive with an ELF and a BIN file for AVR as a sample.
[avr.zip](https://github.com/uxmal/reko/files/1682406/avr.zip)

**Comment by uxmal** [comment]
Would you allow me to add that AVR8 ELF file to Reko's regression test suite? It uncovered a few bugs and will be useful in the future when Reko better handles procedures that return values in multiple registers.

**Comment by kalej** [comment]
This ELF was avaliable online as a part of a DIY project so I do not even know who is it's owner. If you need some AVR ELF files, I can compile a test bunch.
