### ISSUE TITLE
MacOS Classic - expand compressed Application global data into A5 World

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#570]
I have hacked together a solution to expand the compressed application global dataI into the A5World.
The code is  based on the code resource %A5Init routines, which would expand the data into the BelowA5 area of A5World.

The hacked code fragment is from line 346 - 456 of the attached modified file src\Environments\MacOS\ResourceFork.cs. It should only load if the bank size is 64K and the offset to packed data is in the A5World memory space 
[ResourceFork.zip](https://github.com/uxmal/reko/files/1695031/ResourceFork.zip)

Summary of what the application code does to setup the application global A5World data.

The routine _DATAINIT starts with the following code.
﻿0010FC02 48 E7 7F F8 movem.l d1-d7/a0-a4,-(a7)
0010FC06 49 FA 01 A8 lea 0010FDB0,a4
The offset at 0010FC08 provides a relative address to a header for setting up the global app data.

The header at 0010FDB0
Long - Size below A5, start of global application data
Long - Bank/segment ?? size (00010000) 64KB
Long - offset to start of compressed global data from the start of the header
Long - offset to relocation data from the start of the header
Long - ???? 000000000

uncompress_world routine - passed ptrs to start of compressed data and bottom of below_A5World
Compressed data
set Repeat count = 1, reset after each completed copy cycle
byte lower 4 bits number of words to copy from compressed data
upper 4 bits number of words to skip in global application data space
if either value is 0 then run length value used is in bytes, and if the new run length value for copy is 0 then it's the end of compression data.

get_rl routine
Run length if required is next byte(s).
0xxxxxxx - 0-$7F
10xxxxxx - 0 - $3FFF ( run length and $3F + next byte, 14 bits)
110xxxxx - 0 - $1FFFFF ( run length and $1F + next two bytes, 21 bits)
1110xxxx - next 4 bytes, 32 bits
1111xxxx - get both new runtime length copy in bytes and new runtime length repeat count

**Comment by uxmal** [comment]
Pardon my ignorance, but is this a standard MacOS behavior, or specific to the program at hand? My MacOS background is not that strong, but it seems a little specialized.

If the earlier, I will look into how to integrate the change you submitted, but there are a few issues, notably with all the "magic numbers" that have no explanation, that will have to be addressed first.

 If the latter, perhaps it'd be better if you created a custom extension to Reko to handle your specific binary? Let me know either way and we can discuss how to proceed.

**Comment by gbody** [comment]
@uxmal which ever is the better way which I will leave to you to decide. But surely having the global application data available during decompile allows for data, like strings, values etc... to be evaluated/identified and be made available for inserting into the decompiled code.
the sample app I was looking at, was developed within MPW and is using the Machintosh runtime environment.
The magic numbers are only the first 8 bytes of the CODE segment, with the last 2 bytes being the offset to the compressed application global data. There are a couple of checks like segment size 64KB and offset is with A5World memory range.

A couple of links providing some discussion on A5World setup.

https://github.com/ksherlock/mpw/wiki/Technical-Note-PT37:-Using-MPW-for-Non-Macintosh-68000-Systems
http://mirror.informatimago.com/next/developer.apple.com/documentation/mac/runtimehtml/RTArch-2.html
http://www.mactech.com/articles/develop/issue_12/Rollin_final.html

**Comment by uxmal** [comment]
Thanks for those links, I will read up on the topic. I have no issue adding this feature, it's just a matter of organization: where does it "belong", in the OS, or in a compiler specific extension.

**Comment by uxmal** [comment]
Hello @gbody . I was wondering if you could submit your code as a pull request?

**Comment by gbody** [comment]
Hi @uxmal what's the right way to do a pull request. Otherwise my code is in the zip file. Which is a single source file.

**Comment by uxmal** [comment]
I noticed that you've created a fork of reko (https://github.com/gbody/reko). I'm assuming you're using a version of Visual Studio that has Git support (2015 or 2017). You can create a PR by:

1. Making a git clone of https://github.com/gbody/reko to somewhere on your computer.
2. Open the `Reko-decompiler.sln` file with VStudio
3. Make the changes to the source files
4. Commit and push the changes to https://github.com/gbody/reko
5. Go to https://github.com/gbody/reko/pulls and push the green `New pull request` button.
6. Submit the pull request.

You will want to make sure that your fork https://github.com/gbody/reko is uptodate by merging from the master repository https://github.com/uxmal/reko before you submit the PR.
