### ISSUE TITLE
Assigning the correct function addresses

### ISSUE THREAD

**Issue by halsten** [uxmal/reko#59]
So far reko doesn't recognize the function's EP for a PE file correctly. By default in most cases of PE files, the EP is set to 401000 however, reko doesn't respect that and assigns the function addresses to its own logic. Am unaware of how it is doing it internally. But, I expect that if I chose function 401000 from the left side panel in the GUI then I should be redirected to the main EP of the executable instead of having to drill down and that takes a lot of time.

**Comment by uxmal** [comment]
Functions are getting the right addresses. It's just wasn't obvious which one of the functions is the entry point. The linker is not obliged to make 401000 the entry point of the binary, so reko GUI needs a way to show the entry point to the user.

I've just checked in a proposal (nothing more) where the Icon for entry point(s) looks different. Please suggest any improvements -- I'm not 100% happy about the icon. I need something more "entry"-like. Suggestions welcome.

**Comment by uxmal** [comment]
@halsten: are you OK with the entry points indicated with a special icon?

**Comment by halsten** [comment]
Yes. Makes sense to me to have a special icon. Thank you!
