### ISSUE TITLE
OpenBinaryAs/ShowLowLevelWindow throws a null reference exception

### ISSUE THREAD

**Issue by chostelet** [uxmal/reko#630]
In the branch 'processor-architecture-customization', if PostprocessProgram method throws an exception to notify that the program image is not accepted, then OpenBinaryAs/ShowLowLevelWindow throws a null reference at line #147 in Gui/Forms/InitialPageInteractor.cs

**Comment by chostelet** [comment]
This is due to 'Decompiler.Project' being null.

**Comment by uxmal** [comment]
Thanks for the report. I Will attend to this shortly

**Comment by uxmal** [comment]
Fixed in the `processor-architecture-customization` branch.
