### ISSUE TITLE
Running tests in x64 configuration mode gives regression in Arm and Thumb.

### ISSUE THREAD

**Issue by chostelet** [uxmal/reko#644]
All but ARM related architecture tests run successfully in x64 mode.
To reproduce: - switch to x64 solution configuration, rebuild solution, switch Test->Test settings-> Default processor architecture to x64. Then run tests.
ARM-related test classes as well as Thumb-related test classes fail.

**Comment by ptomin** [comment]
Yes, there is same problem on my machine. See also #637
