### ISSUE TITLE
Seems the self operation is wrongly translated in SSATransform

### ISSUE THREAD

**Issue by NyaMisty** [uxmal/reko#653]
Suppose we have the source code
```
int i = 10;
do{
    i -= 1;
}while(i - 1 < 0);
```
During the SSA transformation, the statement like ```l0 = l0 + 1 ``` will be renamed to ```l0_83 = l0_75 + 1``` and then being propagated into the later branch statement, causing the self-increment operation becomes a simple add statement like ``` {branch l0_75 + 0x00000001 - l2_79 < 0x00000000 l0001095C_ds_t} ```
I tried to fix by adding special check code in the SsaTransform to make it transform the ```l0 = l0 + 1``` into ```l0_75 = l0_75 + 1``` and make the DeadCode eliminator ignore the statement like this, but it seem that it's breaking other codes. 
I'm wondering if I should make the SsaTransform translate it into ```l0_83 = l0_75 + 1``` and ```l0_75 = l0_83```.

**Comment by NyaMisty** [comment]
Oh it seem that I misunderstood the SSA itself. I'll dig deeper.

**Comment by uxmal** [comment]
Your sample code would, after the SSA transformation, look like this:
```
i_1 = 10;
do {
    i_3 = phi(i_1, i_2);
    i_2 = i_3 - 1
} while (i_2 - 1 < 0);
```
Note the very important `phi` node, which in effect "fuses"  i_1, i_2, and i_3 into what Reko calls a  "web" (see https://github.com/uxmal/reko/blob/417388d5665abe805b273e3a16c25464488a6522/src/Decompiler/Analysis/WebBuilder.cs#L40 . As a final step before emitting source code, we merge all SSA identifiers that are connected with `phi` nodes into `Web`s, which correspond to (mutable) variables the way a C programmer would expect them to appear.

**Comment by NyaMisty** [comment]
Thanks~ I later figured out that the PHI corresponds the [fai] in the SSA
so I closed the issue :)
It seem that the self increment is propagated into the branch condition,
causing the self-increment statement vanished in the decompile output, but
I'm not that sure and I'll try to dig deeper.

John Källén <notifications@github.com> 于2018年6月15日周五 下午3:39写道：
