### ISSUE TITLE
error when launch Decompiler

### ISSUE THREAD

**Issue by rmarshall2** [uxmal/reko#657]
I downloaded reko-0.7.1.0.msi file from sourceforge.net and installed it.
Installation seemed to work ok.
I clicked on the link in Windows programs for Reko Decompiler and got the error pop-up:
"WindowsDecompiler.exe is not a valid Win32 application."
I downloaded from other sites, reko-0.7.2.0.msi and reko-0.8.0.0-x86.msi.
They produce the same error.
I have spent hours trying to resolve this, but no success.
Am wanting advice on how to launch without error.
My request for help at sourceforge was not answered.

Pardon me, but I'm not a developer.  I'm an advanced user, and the sourceforge site says the msi file is for advanced users.
![reko-err](https://user-images.githubusercontent.com/40469137/41730392-3caa7a4c-756b-11e8-9cdb-dc8ad564fd71.gif)

**Comment by uxmal** [comment]
Thanks for reporting this. One question that comes to mind is: what version of Windows are you running? Reko uses .NET Framework 4.7. This will only work on Windows 7 SP1 or later.

**Comment by rmarshall2** [comment]
I am running Window XP SP3.  I have .NET Framework 4 Extended 4.0.30319.

I didn't know it requires Windows 7 SP1 or later.  Sourceforge says support for MS-DOS, Win32, etc.

Can I run Reko Decompiler if I boot up in DOS?

Is there an earlier release compatible with my XP?  Where can I get it?

Thanks for helping.  It looks like an excellent utility, will do exactly what i need.

Richard Marshall
rmarshall@fastmail.com

**Comment by uxmal** [comment]
When it says support for MS-DOS, Win32, it means Reko can decompile MS-DOS binaries and Win32 binaries (among other things). However the Reko software itself requires either Windows 7 SP1 or later, or a recent Linux distribution running Mono. I don't know whether .NET 4.7 can be made to run on Windows XP or Vista.
