### ISSUE TITLE
Build errors on Visual Studio for Mac

### ISSUE THREAD

**Issue by wildptr** [uxmal/reko#658]
I encountered 2 build errors while trying to build on macOS High Sierra with Visual Studio for Mac:
1. cmake cannot find capstone which is already installed (via homebrew). Adding the line `set(PKG_CONFIG_EXECUTABLE /usr/local/bin/pkg-config)` before the `pkg_check_modules` command in CMakeLists.txt works around this.
2. Later in the build process (AfterBuild?), `libArmNative.so` is not found. However, `libArmNative.dylib` is present at its place. I worked around this by replacing `libArmNative.so` in `Drivers/Common.items`.

With both problems resolved, the program compiles successfully, but crashes immediately upon launch. (WindowsDecompiler Debug|x64)

EDIT: Fix formatting.

**Comment by uxmal** [comment]
Thanks for reporting this. Unfortunately, I don't have access to a Macintosh so I've been unaware of these build failures. 

On line 126 of `Drivers\Common.items` you will find the line
```
<ItemGroup Condition=" '$(OS)' == 'Unix'">
```
I'm wondering -- but unable to test -- if changing the condition to something like
```
<ItemGroup Condition=" '$(OS)' == 'Unix' And '(OSName)' == 'OSX'">
      <Architectures Include="$(SolutionDir)Native\build\$(Platform)\$(Configuration)\ArmNative\libArmNative.dylib" />
</ItemGroup>
<ItemGroup Condition=" '$(OS)' == 'Unix' And '(OSName)' != 'OSX'">
      <Architectures Include="$(SolutionDir)Native\build\$(Platform)\$(Configuration)\ArmNative\libArmNative.so" />
</ItemGroup>
```
will preserve the existing build behavior for non-OSX builds, and also work for OSX builds. Perhaps you could verify this?

As for the immediate crash on startup, I'm unable to diagnose without more information. However, I suspect this may have to do with the fact that Visual Studio for Mac doesn't support Windows.Forms.  Reko currently uses Windows Forms for its GUI, but we're actively looking for cross-platform alternatives. 

The command line client should work just fine.  We use Travis CI to catch regressions on non-Windows platforms, but that of course is a Linux environment.
