### ISSUE TITLE
how to uninstall reko decompiler

### ISSUE THREAD

**Issue by rmarshall2** [uxmal/reko#669]
I have Reko decompiler ver 0.6.1.0 and Windows XP. I want to uninstall Reko, but I don't see a good way.  It can't be done via Add/remove programs.  There is no exe that uninstalls.  What is the recommended way to uninstall?

**Comment by uxmal** [comment]
The Reko installer doesn't register anything in the registry, so you should be able to just remove it brutally by deleting all the files in `c:\Program Files\jklSoft\Reko`. Let me know if this doesn't work for you.

**Comment by uxmal** [comment]
Closing this now, let me know if you need further assistance.
