### ISSUE TITLE
Bug: Return value not assigned

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#679]
Exe: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/cfg/ia32_elf/subject.exe
Reko version: 46f203b

Output:
```
void intermediate_1_short_circuit_and(word32 eax, word32 dwArg04, ui32 dwArg08)
{
	word32 esp_4;
	byte SCZO_5;
	word32 edx_6;
	byte SZO_7;
	bool C_8;
	bool Z_9;
	ui32 eax_10;
	rand();
	if (dwArg04 != 0x00 && eax_10 == dwArg08)
		puts("both true");
}
```

There should be a statement like "eax_10 = rand()". For some strange reason reko doesn't have a problem with the time() call in the same binary.

Also the other declared but unused variables shouldn't be there.

**Comment by uxmal** [comment]
This should go away with a correct declaration of `rand`.
