### ISSUE TITLE
Variable doesn't get its value

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#686]
Exe: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/value_prop/ia32_elf/subject.exe
Reko version: d60d899

Output:
```
word32 basic_3_reg_cond_overwrite(int32 dwArg04, ptr32 & ebxOut)
{
	word32 ebx_16;
	*ebxOut = 0x41;
	if (dwArg04 != 0x2A)
		*ebxOut = 0x61;
	putchar(dwArg04 + ebx_16);
	return 0x00;
}
```

Maybe ebxOut should also be written to be returned but more important is that ebx_16 gets the correct value for the putchar() call. Or output `putchar(dwArg04 + *ebxOut);`

**Comment by uxmal** [comment]
This has been fixed in the `analysis-development` branch. The fix cannot be back ported to the `master` branch, but I'm working hard to make a 0.9 release where I merge `analysis-development` into `master`.

**Comment by uxmal** [comment]
Hoping to release 0.9 soon.
