### ISSUE TITLE
TypeGraphWriter and TypeFormatter VisitCode

### ISSUE THREAD

**Issue by nemerle** [uxmal/reko#71]
both of those methods do something like:
```
 writer.Write("code", c.Size);
```
The passed c.Size  is unused ? Should it be ?  :smile:

**Comment by uxmal** [comment]
That's very likely a cut/paste error. The pseudo type `(code)` refers to raw machine code that has not been decoded/decompiled yet, and which should not appear in the finished decompiled code. In the type lattice, `(ptr (code))` < `(ptr (function ...))` You can safely remove the unused argument to `Write`

**Comment by nemerle** [comment]
Closed with c08a4fa
