### ISSUE TITLE
"Hell nodes" are too aggressive and explicit

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#710]
Looking at the `analysis-branch`, the implementation of "hell nodes" -- that is, calls to procedures whose effect on the CPU registers is not known -- works by asking the `IProcessorArchitecture` to enumerate "all" registers and then creates a call instruction that looks something like this:
```
call someFunction
     uses: r0, r1, r2 ..... r31
     defs: r0_32, r1_33, r2_34, ..... r31_63
```
The hope is that at some later point in the analysis process, the signature of `someFunction` will be known and the remaining `defs` can be bypassed by generating assignments after the call:
```
call someFunction
    uses: r3, r4
    defs: r3
r0_32 = r0
r1_33 = r1
r2_33 = r2
// etc
```
Even for x86, this generates a _lot_ of extra register assignments, which cause a lot of unnecessary work.

An idea I have been mulling with recently is to introduce the "hell node" implicitly into the `SsaTransform` phase. Rather than eagerly expanding out all the CPU registers, we instead decorate an indeterminate call instruction with a pair of "collectors" that are responsible for tracking uses and definitions around the call:
```
call someFunction
    uses: <all-reaching-definitions>
    defs: <all-live-registers>
```
Suppose after the call, SSA analysis discovers a use of the `r3` register after the `call`. `SsaTransform` adds it explicitly:
```
call someFunction
    uses: r3<all-reaching-definitions>
    defs: r3_35 <all-live-registers>
Mem[0x00123400:word32] = r3_35
```
If the analysis later determines that `someFunction` doesn't modify `r3`, a "bypass copy" `r3_35 = r3` can be added after the call, as is done today.

I'm opening this to discussion. The hope is that implementing this will improve the performance of `SsaTransform` in the presence of indirect and recursive procedures (which is pretty much all programs these days) by avoiding generating lots of SSA identifiers that are never really used.

**Comment by uxmal** [comment]
I claim that is still too much.  Imagine a procedure that touches many registers,  or a procedure with hundreds of stack local variables. You don't want to emit a SSA variable for each of those variables, because the majority will not be relevant. I'm hoping deferring the generation of the hell node variables will alleviate this.

**Comment by ptomin** [comment]
Code profiling should be done to make sure that hell nodes processing really takes a lot of time.

**Comment by ptomin** [comment]
I have done code profiling on my private binary. The most time is taken by stack definitions `IntervalTree` enumeration in `ReplaceBy` method (I'll raise PR to improve that). Suggested hell node optimization looks insignificant. But maybe it could be useful for other binaries

**Comment by uxmal** [comment]
Good work Pavel, any improvement is good. I'm concerned because I noticed how much slower the 
regression tests in `analysis-development` have become, compared to `master`. I'm suspecting that the great number of `ssaId`s is partially to blame, but I need to measure it. I will try to see when I can get some time to perform a measurement run.

**Comment by ptomin** [comment]
> I noticed how much slower the regression tests in analysis-development have become

Strange. The most regression tests failed at early stages now and so works fast. All regression tests ran in 25 seconds an my machine

**Comment by uxmal** [comment]
I was seeing at least 3 times slowdown -- but that was a month ago. I will see if I can find a particular binary to focus on.

**Comment by uxmal** [comment]
I pushed commit 554e4ecc75bbe025fcb4f4e930f50aa1a9286b9f which changes to the regression script so we can capture tests that are timing out. First one to fail is `Elf\RiscV\ipcalc\ipcalc.dcproject`

**Comment by ptomin** [comment]
> First one to fail is Elf\RiscV\ipcalc\ipcalc.dcproject

Maybe it's infinite loop/recursion

**Comment by uxmal** [comment]
Indeed. It's looping in `TrashedRegisterFinder3` on a phi-assignment. I'm looking into it.

**Comment by ptomin** [comment]
IdState should be reset to `Constant.Invalid` to avoid infinite loop at following line
https://github.com/uxmal/reko/blob/554e4ecc75bbe025fcb4f4e930f50aa1a9286b9f/src/Decompiler/Analysis/TrashedRegisterFinder3.cs#L804

**Comment by uxmal** [comment]
I'm closing this for now. The regression suite are running reasonably fast. I'm still thinking about ways to reduce the excessive registers being generated.
