### ISSUE TITLE
installation fails on win 10

### ISSUE THREAD

**Issue by kelvinwop** [uxmal/reko#713]
The installer shows preparing to install, then disappears and dies

**Comment by kelvinwop** [comment]
Hmm I installed the dot net framework (that the build in vs 2017 prompted me to get) and restarted my computer. The 64 bit msi worked after that. 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔 

It might just be my computer tbh

**Comment by uxmal** [comment]
Thanks for reporting that. It says to me that the installation  instructions need to specify clearly that for Windows users,   .NET Framework 4.7.2 must be installed.
