### ISSUE TITLE
Radare2 integration

### ISSUE THREAD

**Issue by XVilka** [uxmal/reko#725]
Since it support much more features and architectures rather than pure capstone.

## Architectures

i386, x86-64, ARM, MIPS, PowerPC, SPARC, RISC-V, SH, m68k, AVR, XAP,
System Z, XCore, CR16, HPPA, ARC, Blackfin, Z80, H8/300, V810, V850,
CRIS, XAP, PIC, LM32, 8051, 6502, i4004, i8080, Propeller, Tricore, Chip8
LH5801, T8200, GameBoy, SNES, MSP430, Xtensa, NIOS II,
Dalvik, WebAssembly, MSIL, EBC, TMS320 (c54x, c55x, c55+, c66),
Hexagon, Brainfuck, Malbolge, DCPU16.

## File Formats

ELF, Mach-O, Fatmach-O, PE, PE+, MZ, COFF, OMF, TE, XBE, BIOS/UEFI,
Dyldcache, DEX, ART, CGC, Java class, Android boot image, Plan9 executable,
ZIMG, MBN/SBL bootloader, ELF coredump, MDMP (Windows minidump),
WASM (WebAssembly binary), Commodore VICE emulator, 
Game Boy (Advance), Nintendo DS ROMs and Nintendo 3DS FIRMs, various filesystems.

## Operating Systems

Windows (since XP), GNU/Linux, OS X, [Net|Free|Open]BSD,
Android, iOS, OSX, QNX, Solaris, Haiku, FirefoxOS.

## Bindings

Vala/Genie, Python (2, 3), NodeJS, Lua, Go, Perl,
Guile, PHP, Newlisp, Ruby, Java, OCaml...

# Dependencies

radare2 can be built without any special dependency, just
get a working toolchain (gcc, clang, tcc...) and use make or meson.

**Comment by XVilka** [comment]
I also saw your https://github.com/uxmal/reko/projects/4 so r2 ability of loading PDB, DWARF, and dldcache can benefit you too.

**Comment by uxmal** [comment]
Thanks for your interest in this project. You're suggesting integrating Reko and Radare2. The scope of such an integration is very large, and is infeasible to do at this time. Let us know if there is a particular feature you wish implemented in Reko.

**Comment by uxmal** [comment]
Closing due to no action.
