### ISSUE TITLE
MacOS Classic - bug in BinHex decoder

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#729]
While trying to look at a new application, in BinHexImageLoader.cs added "APPL"
if (hdr.FileType == "MPST" || hdr.FileType == "APPL").
Maybe there should be a more generic loader for any file, with only exceptions being added. 

Item 1
When loading the binhex file the system was reporting an internal error and there was no memory segments visible. After a spending a bit of time I have been able to locate the issue in function GetBytes() in the file BinHexDecoder.cs. This occurred with the decoded hex byte sequence 80 00 90 06 90 00 00 which produces decoded/expanded hex sequence 80,0,0,0,0,0,0,90,0,0 which is 1 byte longer than expected. The decoding should be 80 -> single byte 80, then repeat 00 90 06 -> 00 00 00 00 00 00, then 90 00 -> single byte 90, then 00 -> single byte 00.

        public IEnumerable<byte> GetBytes()
        {
            int lastByte = -1;
            IEnumerator<byte> unexpanded = GetUnexpandedBytes().GetEnumerator();
            while (unexpanded.MoveNext())
            {
                byte b = unexpanded.Current;
                if (b == 0x90 && lastByte != -1)
                {
                    if (unexpanded.MoveNext())
                    {
                        int count = unexpanded.Current;
                        if (count > 0)
                        {
                            for (int i = 0; i < count-1; ++i)
                            {
                                yield return (byte)lastByte;
                            }
//
//   You don't need to reset lastByte after each repeat block
//                            lastByte = -1;
                            continue;
                        }
                        else
                            b = 0x90;
                    }
                }
                yield return b;
                lastByte = b;
            }
        }

Item 2
When doing a binary scan  get this warning. 
Warning,00104C36,M68k instruction 'rtd' is not supported yet.

[IIe Startup.zip](https://github.com/uxmal/reko/files/2851552/IIe.Startup.zip)

**Comment by uxmal** [comment]
Fixes made in `master` branch.
