### ISSUE TITLE
MacOS Classic - Dominator graph calculation timed out. 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#732]
One of the recent updates has introduced the following error with the file I have been testing with.  

Error,strncat,An error occurred during data flow analysis. Dominator graph calculation timed out. 
Error,strncpy,An error occurred during data flow analysis. Dominator graph calculation timed out. 

RTL code.
﻿void strncat(word32 dwArg04, word32 dwArg08, word32 dwArg0C)
{
strncat_entry:
l001062A8:
    a7 = fp
    a5 = a5world
    a0 = dwArg04
    d0 = a0
    CVZN = cond(d0)
l001062AE:
    v6 = Mem0[a0:byte]
    a0 = a0 + 0x01
    ZN = cond(v6 - 0x00)
    Z = (bool) ZN (alias)
    C = false
    V = false
    branch Test(NE,Z) l001062AE
l001062B2:
    a1 = dwArg08
    d1 = dwArg0C
    CVZN = cond(d1)
    ZN = CVZN (alias)
    V = (bool) CVZN (alias)
    Z = (bool) CVZN (alias)
    N = (bool) CVZN (alias)
    C = (bool) CVZN (alias)
    a0 = a0 - 0x01
    ccr = 0x00
    goto l001062C6
l001062C2:
    d1 = __swap(d1)
    ZN = cond(d1)
    C = false
    V = false
l001062C4:
    v16 = Mem0[a1:byte]
    a1 = a1 + 0x01
    v17 = v16
    Mem0[a0:byte] = v17
    a0 = a0 + 0x01
    CVZN = cond(v17)
    ZN = CVZN (alias)
    V = (bool) CVZN (alias)
    Z = (bool) CVZN (alias)
    N = (bool) CVZN (alias)
    C = (bool) CVZN (alias)
l001062C6:
    branch Test(EQ,Z) l001062D4
l001062C6_1:
    d1 = d1 - 0x01
    branch d1 != ~0x00 l001062C4
    d1 = __swap(d1)
    ZN = cond(d1)
    C = false
    V = false
    d1 = d1 - 0x01
    branch d1 != ~0x00 l001062C2
    goto l001062D4
l001062D2:
    Mem0[a0:byte] = 0x00
    Z = true
    C = false
    N = false
    V = false
l001062D4:
    return
strncat_exit:
}

**Comment by uxmal** [comment]
Is this one of the binaries you've submitted previously?

**Comment by gbody** [comment]
Yes, the linkkIIgs
  ----- Original Message -----

**Comment by uxmal** [comment]
Thanks for reporting this. It was a regression that wasn't caught by the test suite.
