### ISSUE TITLE
Discussion MacOS - conditional expressions generated

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#733]
Having look at the output of the sample file - linkiigs, I noticed that a large number of the conditional expressions generated could be made simpler to read. Is this something that is still a work in progress.

Example 

==========================================
Disassembled 68K Code fragment

;; main: 00100B6A
main proc
	link	a6,#$0000
	move.l	d7,-(a7)
	move.l	$0008(a6),d7
	pea	$0042(a5)
	jsr.l	$3EAE(pc)                                            ; 00104A26
	moveq	#$00,d0
	move.l	d0,-(a7)
	jsr.l	$4B78(pc)                                            ; 001056F8
	jsr.l	$05FA(pc)                                            ; 0010117E
	move.l	$000C(a6),-(a7)
	move.l	d7,-(a7)
	jsr.l	$0600(pc)                                            ; 0010118E

Start of related code 
-----------------------------
	move.l	d0,d7
	moveq	#$02,d0
	cmp.l	d7,d0
	lea	$000C(a7),a7
	bne	$00100BB4

l00100B9E:
	tst.b	-$11FE(a5)
	bne	$00100BAA

l00100BA4:
	tst.b	-$121A(a5)
	beq	$00100BB4
------------------------------
End of related code

 
===========================================
Generated code for related code

if (0x02 - d0_36 == 0x00 && (a5world->bFFFFEE02 != 0x00 || a5world->bFFFFEDE6 != 0x00))

===========================================

I would have expected the section "0x02 - d0_36 == 0x00" to be simplified.
eg. 
d0_36 == 0x02  
or
0x02 == d0_36

so output is
if (d0_36 == 0x02 && (a5world->bFFFFEE02 != 0x00 || a5world->bFFFFEDE6 != 0x00))

**Comment by uxmal** [comment]
Thanks for bringing this to our attention. Commit 80e4466 addresses this.
