### ISSUE TITLE
Proximity graph

### ISSUE THREAD

**Issue by Cairn23** [uxmal/reko#747]
Provide the functionality so that a user can see, what methods are calling the function in a graph, and then provide the inverse of this so see what functions the method is calling

**Comment by uxmal** [comment]
First half of this (show all callers) is implemented starting with commit 7127c8248ebf2235f7b85bd58ee10c8e873d3031. The second half, show all callees, will be done soon.

**Comment by uxmal** [comment]
Second half now implemented. Let me know if there are any enhancements you want.

**Comment by uxmal** [comment]
Here's a snapshot of the Call Hierarchy tool window in action:

![image](https://user-images.githubusercontent.com/10154465/59562607-dd777680-902e-11e9-9bcd-d3df77c21392.png)

**Comment by ptomin** [comment]
Nice!
