### ISSUE TITLE
Make stable names for ssa identifers and equivalence classes

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#751]
`Reko` generates names like 'eax_12' and `Eq_17`. They can be changed across different `reko` versions. And so there are dufficulties during comparing of decompiler output. Stable ids make it easier. Python code can modified to use `regexp` to replace such ids to `eax_?` and `Eq_?` after running regression tests. And it coud help to compare output between `master` and `analysis_development`

**Comment by ptomin** [comment]
I have implementation on my local machine. But it has false positive result for segmented-addressed function names. `fn040_010` converts to `fn_040_?`

**Comment by ptomin** [comment]
Done in #752

**Comment by uxmal** [comment]
This is implemented now. Close?

**Comment by ptomin** [comment]
Yes, it could be closed
