### ISSUE TITLE
MSDOS .com file / general binary disassembly

### ISSUE THREAD

**Issue by bleuge** [uxmal/reko#754]
.com files are reported as "The format of the file is unknown", adding support (just load it at 100h), could be useful for general Raw binary disassembly (sys dos drivers, bios, raw binary code...) 
So, providing a dialog in the case of format unknown, with load binary to xxxxh address could be great.
Of course I can convert a .com file to .exe easily, but if I remember right, this didn't work always. 

Thanks!

**Comment by uxmal** [comment]
Reko does know how to do this, but I agree it should be easier to discover. Do the following:

`File` > `Open as...`

You should see `Open as` dialog. Pick a file and then select the raw file ms-dos COM executable
![image](https://user-images.githubusercontent.com/10154465/54768454-7dc02980-4bff-11e9-92b6-c30abfb3df26.png)

Reko will load the COM file at address 0800h:0100h

**Comment by uxmal** [comment]
@bleuge : I just committed a change that will automatically open the `Open As...` dialog if Reko can't automatically recognize the file format of the file. You can then select "MS-DOS" as indicated in the screenshot above. I hope this makes it easier to work with the GUI.
