### ISSUE TITLE
Duplicated alias statement (slices)

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#755]
See
https://github.com/uxmal/reko/blob/d5e9ac4af7366b24712655b560f66f8710bd0320/subjects/PE/x86-64/varargs_test/varargs_test.c#L846
and
https://github.com/uxmal/reko/blob/d5e9ac4af7366b24712655b560f66f8710bd0320/subjects/PE/x86-64/varargs_test/varargs_test.c#L847

**Comment by uxmal** [comment]
I have a fix on my machine. Unfortunately, the fix uncovered other bugs that cause regression tests to fail. Investigation is underway.

**Comment by uxmal** [comment]
This has now been committed to `analysis-development`
