### ISSUE TITLE
MacOS Classic - Procedure definitions after analysis. 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#762]
using the the analysis-development I am seeing the same issue with D7 where it is being included in the procedure declaration. This had been reported and fixed previously in #635

**Comment by uxmal** [comment]
Can you specify a binary + procedure (address) that exhibits the problem more specifically?

**Comment by gbody** [comment]
application used for testing is linkIIgs,  procedure _mapOSerr 00105290 and _uerror 001053C2
D7 is being pushed onto the stack on entry and pulled prior to exit.

;; _uerror: 001053C2
_uerror proc
	link	a6,#$0000
	move.l	d7,-(a7)
	move.w	$000E(a6),d7
	move.w	d7,-$02F2(a5)
	bne	$001053D8

l001053D2:
	move.l	$0008(a6),d0
	bra	$001053E2

l001053D8:
	ext.l	d7
	move.l	d7,-(a7)
	jsr.l	-$014C(pc)                                           ; 00105290
	addq.w	#$04,a7

l001053E2:
	move.l	d0,-$02F0(a5)
	move.l	-$0004(a6),d7
	unlk	a6
	rts

**Comment by uxmal** [comment]
Thanks for reporting this; fixing this improves the output of many of the subjects in the Reko regression suite.
