### ISSUE TITLE
UnusedOutValuesRemover removes live out ids incorrectly for subregisters

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#766]
`UnusedOutValuesRemover` removes live out ids incorrectly for subregisters. I have created unit test (ef8f764) to reproduce it.

Expected:
```
fn_entry:
body:
	a = 0x00000012
fn_exit:
	use a
```
but was:
```
fn_entry:
body:
	a = 0x00000012
fn_exit:
```

**Comment by uxmal** [comment]
Looks fixed to me now.

**Comment by ptomin** [comment]
Thanks, John!

**Comment by ptomin** [comment]
I have found one more failing test case: 88c96a2
Expected:
```
========================
fn_entry:
body:
	a = 0x00000012
fn_exit:
	use a
========================
main_entry:
body:
	call fn (retsize: 4;)
		defs: regA:a
main_exit:
	use a
```
but was:
```
========================
fn_entry:
body:
fn_exit:
========================
main_entry:
body:
	call fn (retsize: 4;)
main_exit:
	use a
```

**Comment by uxmal** [comment]
Just letting you know I'm still working on this. It was trickier than I thought at first.

**Comment by ptomin** [comment]
> It was trickier
Really? I thought, It's enough to apply same changes as 50db127 to `UserRegisterFinder`: https://github.com/uxmal/reko/blob/88c96a255a6bd1722148ed684e2d7dcfe17566ed/src/Decompiler/Analysis/UsedRegisterFinder.cs#L256

**Comment by uxmal** [comment]
I thought so too, but I'm running into difficulties with registers with subregisters (e.g. `eax` and `ah` etc). I'll keep tinkering this week.

**Comment by uxmal** [comment]
@ptomin: try this now?

**Comment by ptomin** [comment]
Very nice! Thanks, John!
