### ISSUE TITLE
SsaTransform failed to bind byte parameter with 32-bit reading

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#767]
`SsaTransform` failed to bind byte parameter with 32-bit reading. I have created unit test (3085c23) to reproduce it.
```
Expected:

	def dwArg04
	def byteArg
	dwArg04_7 = DPB(dwArg04, byteArg, 0)
body:
	a_3 = dwArg04_7
```
but was:
```
	def dwArg04
body:
	a_3 = dwArg04
```

**Comment by uxmal** [comment]
Сегодня мой день рождения;   спасибо тебе для этом подарок :)

**Comment by uxmal** [comment]
*за этот. Русская грамматика - очень трудная :)

**Comment by uxmal** [comment]
More seriously: this is a very common occurrence.  A small (less than word size) is passed in a word-aligned stack slot. The called procedure then reads the whole slot but uses only a few bits. 

Here we must respect the signature as canonical.  So the word sized read of the argument should, if we're strict, have the the high bits filled with garbage.  

Im AFK right now but will return with a counter suggestion later.

**Comment by ptomin** [comment]
C днем рождения!
> *за этот. Русская грамматика - очень трудная :)
Но ты с ней справился успешно!

**Comment by ptomin** [comment]
> So the word sized read of the argument should, if we're strict, have the the high bits filled with garbage.

Is not
```
dwArg04_7 = DPB(dwArg04, byteArg, 0)
```
assignment makes "the high bits filled with garbage."?

**Comment by ptomin** [comment]
... and then Value Propagator and Dead Code eliminator should eliminate `dwArg04`

**Comment by uxmal** [comment]
Look at my recent commits, Pavel, and let me know if you're satisfied

**Comment by ptomin** [comment]
Looks good! Can be closed now
