### ISSUE TITLE
MacOS Classic - Jump table not being identified

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#784]
Test case LinkIIgs
example
Jump instruction 1C9C- jmp.l ($02,pc,d0.w)
jump table at 1CA0

Size of jump table appears to get indentified correctly with JumpTableIndexInterval of 0-8
After evaluating the jump expression
{0x00101C9E + (int32) ((int16) SEQ(v66, Mem0[0x00101CA0 + d0 * 0x00000002:word16]))}
there are zero results

﻿00101C8C 0C80 0000 0008 cmpi.l #$00000008,d0
00101C92 6E00 0100 bgt $00101D94
00101C96 D080 add.l d0,d0
00101C98 303B 0806 move.w ($08,pc,d0),d0
00101C9C 4EFB 0000 jmp.l ($02,pc,d0.w)
00101CA0 00 E0 00 C6 00 AE 00 94 00 7A 00 60 00 46 00 2C .........z.`.F.,
00101CB0 00 14 4A 07 66 00 01 4A 4A 2E FF F8 6D 00 01 42 ..J.f..JJ...m..B
00101CC0 08 EE 00 07 FF F8 60 00 01 5A 4A 07 66 00 01 32 ......`..ZJ.f..2
00101CD0 08 2E 00 06 FF F8 66 00 01 28 08 EE 00 06 FF F8 ......f..(......
00101CE0 60 00 01 40 4A 07 66 00 01 18 08 2E 00 05 FF F8 `..@J.f.........
00101CF0 66 00 01 0E 08 EE 00 05 FF F8 60 00 01 26 4A 07 f.........`..&J.
00101D00 66 00 00 FE 08 2E 00 04 FF F8 66 00 00 F4 08 EE f.........f.....
00101D10 00 04 FF F8 60 00 01 0C 4A 07 66 00 00 E4 08 2E ....`...J.f.....
00101D20 00 03 FF F8 66 00 00 DA 08 EE 00 03 FF F8 60 00 ....f.........`.
00101D30 00 F2 4A 07 66 00 00 CA 08 2E 00 02 FF F8 66 00 ..J.f.........f.
00101D40 00 C0 08 EE 00 02 FF F8 60 00 00 D8 4A 07 66 00 ........`...J.f.
00101D50 00 B0 4A 2E FF F8 6D 00 00 A8 08 AE 00 07 FF F8 ..J...m.........
00101D60 60 00 00 C0 4A 07 66 00 00 98 08 2E 00 01 FF F8 `...J.f.........
00101D70 66 00 00 8E 08 EE 00 01 FF F8 60 00 00 A6 4A 07 f.........`...J.
00101D80 66 7E 08 2E 00 00 FF F8 66 76 08 EE 00 00 FF F8 f~......fv......
00101D90 60 00 00 90                                     `...
00101D94 4A07 tst.b d7
00101D96 6668 bne $00101E00

**Comment by gbody** [comment]
I have spent time working through what I think is happening and found that when processing jumpExpr {0x00101C9E + (int32) ((int16) SEQ(v66, Mem0[0x00101CA0 + d0 * 0x00000002:word16]))}, the 0x00101C9E is identified as a constant, then the casts  (int32) (int16) are stripped, then when processing v66 it is identified as not being a constant and then further processing of the jumpExpr stops and not data is returned for the jumptable to be buildt.

**Comment by uxmal** [comment]
Indeed, the logic handling the casts should handle the `SEQ` better. I will try to fix it this weekend, but due to commitments it may have to wait until monday.

**Comment by uxmal** [comment]
I just pushed a proposed fix for this. I didn't have your binary available on the machine I'm working on so I wasn't able to verify it. Please verify that the fix works; if not, reopen the issue and I will look at it again.

**Comment by gbody** [comment]
@uxmal not able to reopen so just adding comment. I should have included an addition example as there are jumpExpr with SLICE and the slice throws an not implemented exception. 

The following jumpExpr lists are working .
addrSwitch	{00101C9C}
jumpExpr	{0x00101C9E + (int32) ((int16) SEQ(v66, Mem0[0x00101CA0 + d0 * 0x00000002:word16]))}

addrSwitch	{001066A0}
jumpExpr	{0x001066A2 + (int32) ((int16) SEQ(v96, Mem0[0x001066A4 + d1 * 0x00000002:word16]))}


The following jumpExpr lists are not working and include the SLICE, which throws an exception.

addrSwitch	{00101426}
jumpExpr	{0x00101428 + (int32) ((int16) SEQ(v105, Mem0[0x0010142A + (int32) ((int16) SEQ(v103, SLICE(SEQ(v101, d0) * 0x00000002, word16, 0))):word16]))}

addrSwitch	{00103F78}
jumpExpr	{0x00103F7A + (int32) ((int16) SEQ(v34, Mem0[0x00103F7C + (int32) ((int16) SEQ(v32, SLICE(SEQ(v30, d0) * 0x00000002, word16, 0))):word16]))}

addrSwitch	{0010A488}
jumpExpr	{0x0010A48A + (int32) ((int16) SEQ(v73, Mem0[0x0010A48C + (int32) ((int16) SEQ(v71, SLICE(SEQ(v69, d0) * 0x00000002, word16, 0))):word16]))}

addrSwitch	{0010EC2E}
jumpExpr	{0x0010EC30 + (int32) ((int16) SEQ(v139, Mem0[0x0010EC32 + (int32) ((int16) SEQ(v137, SLICE(SEQ(v135, d0) * 0x00000002, word16, 0))):word16]))}

addrSwitch	{0010F1C6}
jumpExpr	{0x0010F1C8 + (int32) ((int16) SEQ(v89, Mem0[0x0010F1CA + (int32) ((int16) SEQ(v87, SLICE(SEQ(v85, d0) * 0x00000002, word16, 0))):word16]))}

**Comment by uxmal** [comment]
Thanks for posting the failure cases: that really helps.  It should be straightforward to fix them.

**Comment by uxmal** [comment]
Back at home, verified that all those addresses work OK again.
