### ISSUE TITLE
MacOS Classic - analysis-development, sequence fusion performance - Feedback

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#785]
Trying the current state of analysis-development with sample file LinkIIgs file.
When starting the Reconstructing datatypes, transforming datatypes process, the decompiler memory foot print climbs from 115MB to 2.9GB and is constantly paging and this impacts performance, only 4GB physical memory in the system.

**Comment by uxmal** [comment]
I've also noticed a regression in performance recently. After profiling it appears the `TypeTransformer` class is responsible for most of the slowdown. I'm investigating this.

**Comment by uxmal** [comment]
Commit 6d12f7273ad03d1fae56c7c96e93df186586814f greatly improves perfomance on your sample.
