### ISSUE TITLE
Reko crashes badly on Sacred.exe

### ISSUE THREAD

**Issue by Piruzzolo** [uxmal/reko#815]
I've tried the following game binary [Sacred.zip](https://github.com/uxmal/reko/files/3883017/Sacred.zip)

It fails with Unhandled Exception

**Comment by uxmal** [comment]
Thanks for reporting this. How far does Reko go before it crashes? Does it get beyond the "Scanning" phase?

**Comment by Piruzzolo** [comment]
Turns out to be fixed in newer builds, I was using 0.9.0.0 release. Latest nightly works a treat
