### ISSUE TITLE
Failed to decompile 16bit MZ executable, "Expression of type Slice doesn't support Invert. "

### ISSUE THREAD

**Issue by philpem** [uxmal/reko#821]
I tried to decompile a DOS MZ executable. The disassembly went okay, but decompilation fails. The following errors are present in the log window:

```
Error,0800:436B,An error occurred while processing the statement Mem574[ss:sp_569 + 0x0000:word16] = di_550 - si_119. Not handling (memptr T_14398 (struct 0001 (0 byte b0000) (1 byte b0001))) and (memptr T_14398 (struct 0001 (0 byte b0000) (1 byte b0001))) yet. 

Error,0800:501E,An error occurred while processing the statement word16 dx_32 = si - si. Not handling (memptr T_17719 (struct (0 T_17735 t0000))) and (memptr T_17719 (struct (0 T_17735 t0000))) yet. 

Error,fn0800_00B0,An error occurred while rewriting procedure to high-level language. The given key was not present in the dictionary. 

Warning,l0800_3ADF,Non-integral switch expression

Error,fn0800_5308,An error occurred while rewriting procedure to high-level language. Expression of type Slice doesn't support Invert. 
```

At this point, Reko is unusable - the disassembly windows and function browsing appear blank. Further errors appear in the log:

```
Error,,An error occurred while displaying the program. Object reference not set to an instance of an object. 
```

The EXE isn't guaranteed to be okay, it was OCR'd from the patent and may contain errors.

EXE link: https://drive.google.com/open?id=14assohqihZRVdgtRk_mCo5trZtHgTGwC

**Comment by uxmal** [comment]
Thanks for providing the binary.  I will investigate this in a couple of days when I'm back in front of my development gear.

**Comment by uxmal** [comment]
Reko should be more stable now. There are still errors, but these are being worked on in separate issues.
