### ISSUE TITLE
Feature request - support CodeView NB00 symbol table import

### ISSUE THREAD

**Issue by philpem** [uxmal/reko#822]
I have an executable (https://drive.google.com/open?id=14assohqihZRVdgtRk_mCo5trZtHgTGwC) which dates back to 1989 and contains a "NB00" format Microsoft Codeview symbol table.

Reko seems to be able to import some versions of the Codeview data, but not this specific version. It would be nice if Reko could load at least the function names. The data also contains library and data type definitions which may be useful to feed into the decompiler.

I've written a Python script to decode this data:
https://drive.google.com/open?id=11xXdJs1LkOhuOHvw8myWzoHI0dp7mN0R

The format is described in the Microsoft C 6.0 Developers Toolkit Reference Manual:
https://gopher.floodgap.com/gopher/gw?=gopher.superglobalmegacorp.com+70+30302f6d73706c2f6d73632f6d7363746c6b
(or if you have Gopher access: gopher://gopher.superglobalmegacorp.com:70/00/mspl/msc/msctlk )

**Comment by uxmal** [comment]
@philpem looks like you've fone the legwork already for this proposed feature! I will be back in front of a computer in a couple of days to look at this more closely. Would you be ok with my porting your Python script with https://github.com/uxmal/pytocs and then incorporating it into Reko? Naturally you would be credited for your contribution.

**Comment by philpem** [comment]
@uxmal Absolutely! Feel free to use it. You can consider it licensed under the GNU GPL, which makes it compatible with Reko's licence. :)

**Comment by uxmal** [comment]
@philpem: I've now added your subsection parser, translated to C#, and integrated it into the Reko MzExe loader. The next issue to tackle is how to make sense of the type information segment in the file. The documentation is a bit difficult to read, but I will make a stab at getting it to work this week. Feel free to pitch in with more Python code if you have the inclination :-)

**Comment by uxmal** [comment]
@philpem: this code is now feature complete, perhaps a little rough around the edges. Thanks for the feature suggestion and the initial Python code.
