### ISSUE TITLE
System cannot find file specified Reko.Arch.i8051.dll

### ISSUE THREAD

**Issue by kimstik** [uxmal/reko#824]
subj on reko-0.9.0.0-x64.msi
It seems file really not exist. Should it be?

**Comment by uxmal** [comment]
Thanks for reporting this, it should be easily fixed.

**Comment by uxmal** [comment]
It turns out that the 0.9.0.0 mistakenly shipped with the `Reko.Arch.i8051.dll` missing. That error has been corrected since then.  Are you able to build Reko yourself? If not, you can try the latest CI build from appveyor: https://ci.appveyor.com/project/uxmal/reko/build/artifacts
