### ISSUE TITLE
MacOS Classic - Master, User defined Procedure names not honoured after Scan Binaries

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#829]
Sample file Linkiigs
I am seeing a couple of procedures that I have defined in a project file, being named with a MACBUGS symbol name after the scan binaries.
examples:
fn0010455A  (address 10455a) is being named ﻿__CplusInit
INITCURSORCTL (address 1056f8) is being renamed binhex

The same effect can be generated with loading sample file, scan binary.
Edit the signature of procedure binhex at address 1056f8 and name INITCURSORCTL 
Select restart, scan binary. 
Select procedures tab, the procedure at 1056f8 is called binhex and not INITCURSORCTL.

**Comment by uxmal** [comment]
Reko should honour your user-specified names now. "User is always right (even if he's wrong)".
