### ISSUE TITLE
Reko does not recognise 16-bit NE format protected-mode executables

### ISSUE THREAD

**Issue by dirkenstein** [uxmal/reko#831]
For some reason, the automatic format detector is failing to identify NE executables for win16 apps and asks for processor, environment and base address information. 16-bit DLLs are recognized fine.

**Comment by uxmal** [comment]
Could you provide me with an executable that exhibits this behaviour?

**Comment by dirkenstein** [comment]
Try this - should be an ancient win16 turbo pascal program I wrote in '93.

[WGPIBPLO.EXE.zip](https://github.com/uxmal/reko/files/4112371/WGPIBPLO.EXE.zip)

**Comment by uxmal** [comment]
I've found the cause: your binary contains a relocation type that isn't supported by Reko yet. I'll try to get a fix in, but it may be a while as finding documentation for Win16 is sometimes difficult :)

**Comment by uxmal** [comment]
The issue appears to be fixed: the binary you provided now loads without failure. Thanks for reporting the issue!
