### ISSUE TITLE
16-bit OS/2 executables are not supported

### ISSUE THREAD

**Issue by claunia** [uxmal/reko#841]
When trying to open HPOFS20.IFS it crashes in NeImageLoader.cs;L211 because cs is 0.
When trying to open UHPOFS.DLL it crashes in LoadResources, probably because the resources format is different from Windows.

You can download the executables from https://amaus.net/static/S100/IBM/PS2/options/ in the file hpofs20.exe.

I have a NE parser in https://github.com/claunia/libexeinfo that may be of help (I also have a parser for 32-bit OS/2 executable format, LX).

**Comment by uxmal** [comment]
I saw PR #842 you submitted: thanks for that. As for the LX parser, I'd be happy to accept a PR for that, as well. I will work on adding a new `OS2` platform to Reko today.

What would you say the major differences in the resource format is between Windows and OS/2 NE files?

**Comment by claunia** [comment]
Hi, LX is for 32-bit excecutables, it is similar to LE, but not the worry for now.

The resource format is completely different so you need a different parser. My project libexeinfo has a parser for many of the resources. I don't remember where I got the documentation from but I tried it with several executables from OS/2 1.x.

I could not find where the entry point is defined in drivers, only found that CS points to the ring (so 0 for most drivers and 2 for some others), and that they use pascal calling convention.

I can make the resource parser while you prepare the entry point and the start of the platform and then I can add all libraries to the platform?

**Comment by uxmal** [comment]
@claunia: I pushed the new ```OS2Platform``` class an hour or so ago. It's possible that OS/2 drivers have some other entry point mechanism. I'll have to hunt around for documentation for this. Adding support for the `pascal` calling convention shouldn't be too hard; it could be reused from the existing implementation in `Windows`.

**Comment by claunia** [comment]
Excellent I'll take a look after lunch

**Comment by claunia** [comment]
Fixed in e5636ffe701939a5b8731d7e9286ab850041a157.

**Comment by uxmal** [comment]
Commit ad53150ec fixes an exception when loading the device driver file -- not sure if it's the one you reported in #842, but it may help.
