### ISSUE TITLE
Latest master branch is not compiling. 

### ISSUE THREAD

**Issue by junalmeida** [uxmal/reko#85]
Got the following errors:
```
37>------ Rebuild All started: Project: Cpm, Configuration: Release Any CPU ------
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(2,7,2,7): error CS1031: Type expected
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(2,1,2,1): error CS1056: Unexpected character '਍'
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(2,2,2,2): error CS1056: Unexpected character '⼀'
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(2,3,2,3): error CS1056: Unexpected character '⨀'
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(2,5,2,5): error CS1056: Unexpected character 'ഀ'
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(2,6,2,6): error CS1056: Unexpected character 'ഀ'
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(3,16,3,17): error CS1001: Identifier expected
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(3,18,3,22): error CS1002: ; expected
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(3,18,3,22): error CS1022: Type or namespace definition, or end-of-file expected
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(3,40,3,40): error CS1001: Identifier expected
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(3,40,3,40): error CS1003: Syntax error, '(' expected
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(4,1,4,1): error CS1056: Unexpected character '਍'
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(4,3,4,3): error CS1056: Unexpected character '⨀'
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(4,4,4,4): error CS1056: Unexpected character 'ഀ'
31>D:\Projetos\Testes\Reko\src\Gui\Windows\Controls\MemoryControl.cs(4,5,4,5): error CS1056: Unexpected character 'ഀ'
```

And others.

**Comment by uxmal** [comment]
How odd, it's building on my machine. Have you tried cloning a fresh repository?

**Comment by uxmal** [comment]
Browsing the file 
https://github.com/uxmal/reko/blob/master/src/Gui/Windows/Controls/MemoryControl.cs
looks ok.

**Comment by ptomin** [comment]
I have the same problem.

I opened MemoryControl.cs in hex editor and noticed that file started with 0xfffe BOM
It means that encoding is UTF-16. So size of all symbols is 2 bytes and end of line symbol is '0x000a' instead of '0x0a'. If autocrlf git option is set then the '0x000a' symbol is converted to '0x000d0a' and file will be corrupted. Maybe on you machine autocrlf option is not set so it is builing successfully.

Looking at the history I see that MemoryControl.cs encoding was changed to UTF-16 after 476314dc60b415c0784ded482d69dc1d06dccdb5 commit

**Comment by uxmal** [comment]
I see that MemoryControl.cs was set to UTF-16. I will convert it back to UTF-8. Let me know if the problem persists.

**Comment by ptomin** [comment]
Now it is compiled successfully. Thanks

**Comment by uxmal** [comment]
I'm keeping an eye on this one. I admit freely I'm not 100% conversant with how git and Visual Studio interact on Windows, but this is the second time this particular file has had this problem. AFAIK Visual Studio defaults to either CP 1252 (pseudo ISO 8859-1) or UTF-8. It's possible that @nemerle may have accidentally switched to UTF-16 on his commit, although I think that is unlikely. Please let me know if this happens again.

**Comment by junalmeida** [comment]
Thank you @uxmal. It is compiling successfully.
```
========== Rebuild All: 47 succeeded, 0 failed, 0 skipped ==========
```
