### ISSUE TITLE
M68K architecture rewriter.cs issue for set/clear SNE and associated mnemonics

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#851]
The M68K architecture rewriter.cs incorrectly generates the RTL for the following mnemonics

                case Mnemonic.scc: RewriteScc(ConditionCode.UGE, FlagM.CF); break;
                case Mnemonic.scs: RewriteScc(ConditionCode.ULT, FlagM.CF); break;
                case Mnemonic.seq: RewriteScc(ConditionCode.EQ, FlagM.ZF); break;
                case Mnemonic.sge: RewriteScc(ConditionCode.GE, FlagM.NF | FlagM.VF); break;
                case Mnemonic.sgt: RewriteScc(ConditionCode.GT, FlagM.NF | FlagM.VF | FlagM.ZF); break;
                case Mnemonic.shi: RewriteScc(ConditionCode.UGT, FlagM.CF | FlagM.ZF); break;
                case Mnemonic.sle: RewriteScc(ConditionCode.LE, FlagM.NF | FlagM.VF | FlagM.ZF); break;
                case Mnemonic.sls: RewriteScc(ConditionCode.ULE, FlagM.CF | FlagM.ZF); break;
                case Mnemonic.slt: RewriteScc(ConditionCode.LT, FlagM.NF | FlagM.ZF); break;
                case Mnemonic.smi: RewriteScc(ConditionCode.LT, FlagM.NF); break;
                case Mnemonic.sne: RewriteScc(ConditionCode.NE, FlagM.ZF); break;
                case Mnemonic.spl: RewriteScc(ConditionCode.GT, FlagM.NF); break;
                case Mnemonic.svc: RewriteScc(ConditionCode.NO, FlagM.VF); break;
                case Mnemonic.svs: RewriteScc(ConditionCode.OV, FlagM.VF); break;
                case Mnemonic.st: orw.RewriteMoveDst(instr.Operands[0], instr.Address, PrimitiveType.Bool, Constant.True()); break;
                case Mnemonic.sf: orw.RewriteMoveDst(instr.Operands[0], instr.Address, PrimitiveType.Bool, Constant.False()); break;

What should occur.
Register bits 8-31 unmodified
Register bits 0-7 are modified to either 00000000 or 11111111 based on state of condition code flags 

RTL code currently generated is
Variable = SLICE(reg, word31, 8)
reg = SEQ(variable, Z)

The SLICE size is being generated as word31 instead of word24, due to the size of the Z Flag being boolean.

**Comment by uxmal** [comment]
Thanks for reporting this. The code should be more correct now. For extra credit, simplify the resulting ternary expressions, especially in the context of a `NOT` instruction.
