### ISSUE TITLE
Data Flow Analysis continues in the background after canceling 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#853]
After starting Dataflowanalysis, if you select cancel during processing, processing continues in the background until finished. This was noticed while debugging with verbose tracing on. The trace output from the analysis continued to generate data, after the progress Dialogue had been closed.

**Comment by uxmal** [comment]
I've sprinkled a few calls to `DecompilerEventListener.IsCanceled` in `DataFlowAnalysis.cs` and related classes.
