### ISSUE TITLE
Incorrect path for nunit.framework.dll in Windows.csproj

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#86]
I tried to compile reko and got compilation error.
I see that Windows.csproj contains following Nunit assembly link path:

..\..\..\..\tabbed-gui\external\NUnit-2.6.3\nunit.framework.dll

If reko source directory is other than "tabbed-gui" (it is "reko" by default) then compilation error occurs. 
Attached patch can fixed it.
[0001-Fix-path-for-nunit.framework.dll-in-Windows.csproj.patch.txt](https://github.com/uxmal/reko/files/60232/0001-Fix-path-for-nunit.framework.dll-in-Windows.csproj.patch.txt)

**Comment by uxmal** [comment]
Thanks for fixing this. Could you please submit this as a PR (pull request)?

**Comment by ptomin** [comment]
I have created #87 pull request
