### ISSUE TITLE
Request for enhancement of file output

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#863]
The assembly output file includes a a list of locations the procedure is called from.
Example:
;;   Called from:
;;     0010E6FE (in add_Lib_symbol)
;;     0010E74E (in find_Lib_symbol)
;;     0010E83E (in add_RTL_symbol)
;;     0010E88C (in find_RTL_symbol)

Would it possible to have a header included in other output files for procedures to include a summary of the unique calling procedures. I have always found this information useful.
Whether that would include .C and/or .DIS files.

Example 

//   Called from:
//     add_Lib_symbol
//     find_Lib_symbol
//     add_RTL_symbol
//     find_RTL_symbol
//
Procedure_DoStuff

**Comment by uxmal** [comment]
This has been implemented. Let me know if you have any comments (no pun intended) on the implementation.
