### ISSUE TITLE
Simplify switch statements having a constant offset in the expression?

### ISSUE THREAD

**Issue by blindmatrix** [uxmal/reko#874]
I think switch-statements where the first case has a value greater then 0 should be simplified from 
```C++
switch(variable - 0x01)
{
	case 0x00:
```

into

```C++
switch(variable)
{
	case 0x01:
```

I have a suggestion for a quick-fix [here](https://github.com/blindmatrix/reko/commit/956e58372fa5e3a65f417bff5e9c978c85af4f75). But it does the fix rather late, maybe it could be done earlier? Also, I guess it should be configurable. Maybe have a global opt-out option, and a per-switch option too?

Sample binary:
[RekoIssueSwitch.zip](https://github.com/uxmal/reko/files/4742670/RekoIssueSwitch.zip)

Source for sample program (VS2017 C++ Release build without optimizations, `main` is ﻿`fn00401000`):
```C++
volatile int global;
volatile int index;

int main()
{
	switch (index)
	{
	case 1:
		global = 1;
		break;
	case 2:
		global = 2;
		break;
	case 3:
		global = 3;
		break;
	case 4:
		global = 4;
		break;
	case 5:
		global = 5;
		break;
	case 6:
		global = 6;
		break;
	}
}
```

Feedback?

**Comment by uxmal** [comment]
Nice idea! I merged your change, wrote a unit test to generalize the logic to handle both `+ constant` and `- constant`, and committed to `master`. Works fine with your sample binary.
