### ISSUE TITLE
0.9.1.0, Mach-O+ARM64: "Processor format 16777228 is not supported"

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#880]
Sample is just one open source program from the apple app store (https://apps.apple.com/us/app/monal-xmpp-chat/id317711500). Other programs also have this problem.
[Monal-4.6.exe.zip](https://github.com/uxmal/reko/files/4801042/Monal-4.6.exe.zip)

**Comment by uxmal** [comment]
Thanks @rfalke ; I can take a peek in the weekend.

**Comment by rfalke** [comment]
Hmm I just found out that the binaries for iOS are encrypted (as is the attached binary). So while the the original error message is still an issue don't expect any reasonable content in the code section.

**Comment by uxmal** [comment]
I noticed. Reko's aarch64 disassembler is incomplete, but not that incomplete!

**Comment by rfalke** [comment]
I created my own executable (and not downloading it from the app store) at https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/ios-helloworld

It also contains a recursive Fibonacci in swift to analyze a bit of meat.

**Comment by uxmal** [comment]
Reko now loads AArch64 MachO binaries. However, it doesn't find the Fibonacci function because the startup detection code is not completed yet.

**Comment by rfalke** [comment]
FYI: I added Mach-O loading to holdec and found 2 interesting methods (see https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/ios-helloworld/arm64_macho/by_holdec_regtest.c) The swift compiler splits the method indeed in strange ways. I haven't for example found the method which calls fib with the result of time_based_random call. But it is good enough for me to verify that the Mach-O loader works.
