### ISSUE TITLE
x86-16 Incorrect parameters used when using return-values as parameters (faked far calls)

### ISSUE THREAD

**Issue by blindmatrix** [uxmal/reko#881]
Wrong stack location is used when making function calls where some arguments are the result of other function calls when the "argument function" is a far proc that's called as a near call (`push cs; call near func;`)

Affected assembly:
```asm
; func and argfunc1 are far procs
push 4                ; sp+A when inside func
push 2                ; sp+8 when inside func
push cs               ; This is the problem (extra sp = sp-2)
call near argfunc1
push ax               ; sp+6 when inside func
push 1                ; sp+4 when inside func
push cs
call near func
```

Reko fails to remove the added offset for the first `push cs` when valuating the arguments for `func`.

Demo program: [pushcs.zip](https://github.com/uxmal/reko/files/4810263/pushcs.zip)

```C
volatile int var1;
volatile int var2;

void func(int a, int b, int c, int d)
{
	var2 = a + b + c + d;
}

int argfunc1()
{
	return var1;
}

int main(void) {
	func(1, argfunc1(), 3, 4);
	
	return 0;
}
```

Expected output:
```C
void main()
{
    func(0x01, argfunc1(), 0x03, 0x04);
}
```

Actual output:
```C
void main()
{
    func(0x01, argfunc1(), wLoc06, 0x03);
}
```

I believe the issue is in how the rewriter handles `push cs; call near func;` in `X86Rewriter.RewritePush`

**Comment by blindmatrix** [comment]
Having a quick look I think even I can fix this :P I'm going to give it a try.

**Comment by uxmal** [comment]
See my comments on #882. I have a fix on my machine, but there are some regressions in the regression suite I need to examine before I can push to `master`.

**Comment by uxmal** [comment]
My fix wasn't working correctly, and the likelihood of `push cs / call <near>` not being a simulated far call is so small that I decided to pull #882 instead. Thanks for taking the time to report this.
