### ISSUE TITLE
Extra cast for bool

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#894]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/dmi/transformation/ia32_elf/

Before:
```
uint32 basic_1_ternary_simple(Eq_11 dwArg04)
 {
   return (word32) (dwArg04 != 0x2A);
 }
```
now:

```
uint32 basic_1_ternary_simple(Eq_11 dwArg04)
{
	return (uint32) (1) (dwArg04 != 0x2A);
}
```

**Comment by rfalke** [comment]
Also in subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/dmi/transformation/ia32_elf

```
uint32 basic_1_ternary_simple(Eq_11 dwArg04)
{
	return (uint32) (1) (dwArg04 != 0x2A);
}
```

**Comment by uxmal** [comment]
As of commit c272e352fcfa31d6196ab2dbe78005834c69b681, this issue is gone, but the redundant cast is still there:
```
uint32 basic_1_ternary_simple(Eq_10 dwArg04)
{
    return (uint32) (int8) (dwArg04 != 0x2A);
}
```

**Comment by rfalke** [comment]
Still relevant in version 0.11.4.0-931ca7d.

IMHO a decompiler can and should know that `dwArg04 != 0x2A` can only be 0 or 1 and therefore the first cast (`(int8)`) can be removed.
