### ISSUE TITLE
Regression: scanf parameter

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#896]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/fibo_return_on_stack/ia32_elf/

Before:
```
        printf("Input number: ");
   __isoc99_scanf("%d", tLoc28);
        printf("fibonacci(%d) = %d %d\n", dwLoc10, fibo_normal(dwLoc10), fibo_return_on_stack(dwLoc10));
```

Now:
```
	printf("Input number: ");
	__isoc99_scanf("%d", 0x00);
	printf("fibonacci(%d) = %d %d\n", dwLoc10, fibo_normal(dwLoc10), fibo_return_on_stack(dwLoc10));
```

0 is passed to __isoc99_scanf

Also the parameter passed to the fibo calls is not connected to the scanf. Should be something like:
```
    int32_t v1;
    scanf("%d", &v1);
    ... fibo_normal(v1);
```

**Comment by uxmal** [comment]
The `scanf` format string parser wasn't hooked up. We now get:
```C
	printf("Input number: ");
	__isoc99_scanf("%d", fp - 0x10);
	printf("fibonacci(%d) = %d %d\n", dwLoc10, fibo_normal(dwLoc10), fibo_return_on_stack(dwLoc10));
```
The `fp - 0x10` is a WIP -- it will eventially become `&dwLoc10`.
