### ISSUE TITLE
User should be able to mark procedures as "no-decompile" 

### ISSUE THREAD

**Issue by uxmal** [uxmal/reko#9]
Select procedure, then mark it as "no-procedure". The decompiler will need to restart the analysis, but is helpful for removal of procedures that are injected by compiler run-time libraries.

**Comment by ptomin** [comment]
John, is not it already implemented?

**Comment by uxmal** [comment]
I want to confirm that if the no-decompile option is chosen the user must supply a valid signature.

**Comment by ptomin** [comment]
So `Procedure Editor` dialog should be modified so if the no-decompile option is chosen that OK button was disabled until valid signature is set

**Comment by uxmal** [comment]
Yes. Also the project loader should reject user procedues in the dcproj file (with a warning ) that have been marked no-decompile and have no signature.
