### ISSUE TITLE
Question: why different syntax structures?

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#900]
Subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/dmi/cfg/ia32_elf

```
void intermediate_11_loop_with_two_breaks(Eq_11 dwArg04)
{
	Eq_11 ebx_19 = dwArg04;
	if (dwArg04 > 0x00)
	{
		do
		{
			puts("head");
			if (time(null) == ebx_19)
				return;
			puts("tail");
			--ebx_19;
		} while (ebx_19 != 0x00);
	}
}
```

and

```
void intermediate_13_loop_with_one_continue(Eq_11 dwArg04)
{
	if (dwArg04 <= 0x7B)
		return;
	while (true)
	{
		puts("head");
		if (dwArg04 != time(null))
			puts("tail");
	}
}
```

The `if(cond1){something}` and `if(cond2) return; something` are equivalent. 

Why different ones are chosen? Is one preferred? Is it a good idea to use only one?

**Comment by uxmal** [comment]
The different is certainly not deliberate. Personally, I find the "early return" feature easier to read, but others may not.  I can look into this and see if there is a particular reason for the difference.

**Comment by rfalke** [comment]
Not really relevant.
