### ISSUE TITLE
No output for COM files

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#903]
Subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_pouet.net/with_source_388/ia32_com (all ia32_com show same behavior, this one is just the largest)

Reko: `mono .../decompile.exe subject.exe --arch x86-real-16 --env ms-dos --base 0C00:0100 --reg ax:0`

Result: 3 files `subject.reko/subject_code.asm`,   `subject.reko/subject.globals.c` and `subject.reko/subject.h`, but no real decompiled C file.

It looks like this is broken for some time.

**Comment by uxmal** [comment]
You need to specify an entry point (`--entry 0C00:0100`) for COM files. Also, be advised that this particular sample is actually a (packed) EXE file, not a COM file. I tried the most recent commit of Reko on `decompiler-subjects\from_pouet.net\with_source_332\ia32_com\subject.exe` (which in fact is a COM file) and it produced satisfactory results.
