### ISSUE TITLE
Introduce Convert expression type

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#913]
Changes done in 4971642 (see also #911) discover weakness of `Cast` expression type. It have not source data type. High level languages can deduce it from source expression, we can not.
@uxmal I agree with your suggestion to add `Convert` expression type, which takes an input expression, the data type from which it is being converted, and the target data type. Rewriters should emit `Convert` instead of `Cast`. The analysis and type inference parts of `Reko` could use the type information to improve their output. As a final step in `TypedExpressionRewriter`, all Convert instructions would be converted into `Cast`

**Comment by uxmal** [comment]
I've started work on this.

**Comment by uxmal** [comment]
The new `Conversion` class was just pushed (I used that name to avoid conflicts with `System.Convert`). I will now proceed to refactor all rewriters to use the new `Conversion` class.

**Comment by uxmal** [comment]
If anyone has comments on the textual syntax of the new Conversion class, now's the time to let me know about them before I start rewriting hundreds of unit tests :)

**Comment by ptomin** [comment]
Good start! I have added some comments to ee9d4a1

**Comment by rfalke** [comment]
I don't know about details in Reko but there are sometimes multiple ways to do a conversion. So for example you can convert an int into a float number like a C language cast or you can interpret the bits of the int as a floating point number (you would use a `union` in C for this). In both cases you have the same source and destination data type. But a different conversion function. It is possible however that the later is not a conversion you have in mind in this issue. One example for the latter is `fmov` in aarch64. But looking at https://github.com/uxmal/reko/blob/aedb969620051e6569d963dac461894532ac7262/src/Arch/Arm/AArch64/A64Rewriter.Fpu.cs#L204 this is handled in a different way.

**Comment by ptomin** [comment]
`Reko.Core.Expressions.Conversion` should be used only for C-style cast. There is no special expression type for reinterpret cast. For instance assignment with different type of source and destination is actually reinterpret cast

**Comment by ptomin** [comment]
All unit tests passed! This is great work, John! I have added few notes to 13bf4bc

**Comment by uxmal** [comment]
There are still some 90 unit tests that are using `ExpressionEmitter.Cast`. I'm removing those now. After that it should be ok to merge to `master`.

**Comment by uxmal** [comment]
(Those uses, that is -- the tests  obviously will  remain!)

**Comment by uxmal** [comment]
Commit c670cd5201ca3ad3efbffbbc5f07e5960309d134 removes all calls to `ExpressionEmitter.Cast` except for structure analysis tests. I now will proceed in making the regression tests pass.

**Comment by ptomin** [comment]
Good. I have added one comment: https://github.com/uxmal/reko/commit/c670cd5201ca3ad3efbffbbc5f07e5960309d134#r41374608

**Comment by ptomin** [comment]
Implementation of `Conversion` expression type is finished. Thanks for the great work, John!
