### ISSUE TITLE
Wrong function parameter for PIC code

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#919]
PIC: https://en.wikipedia.org/wiki/Position-independent_code

Example subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/pic/x64_elf_clang_O2_pic

With pic the printf parameters are wrong:
```
void main()
{
	printf("in main: %d\n", 0x00);
	g_dw404024 = (word32) (uint64) ((word32) (uint64) g_dw404024 + 0x01);
	printf("in func: %d\n", 0x00);
}
```

The variant without pic (https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/pic/x64_elf_clang_O2_plain) is a bit verbose but correct:
```
void main()
{
	printf("in main: %d\n", (uint64) g_dw404024);
	Eq_77 rsi_13 = (uint64) ((word32) (uint64) g_dw404024 + 0x01);
	g_dw404024 = (word32) rsi_13;
	printf("in func: %d\n", rsi_13);
}
```

**Comment by uxmal** [comment]
As of commit c20ee77f4ea46a, this looks much better. The '0' wrong parameter is not present.
