### ISSUE TITLE
Should use global variable name from binary

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#920]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/pic/x64_elf_clang_O1_plain/

The symbol table contains the information for `a_global`:
```
$ objdump -t x64_elf_clang_O1_plain/subject.exe | grep a_global
0000000000404024 g     O .data  0000000000000004              a_global
$
```

Yet reko doesn't use it:
```
void main()
{
        printf("in main: %d\n", (uint64) g_dw404024);
        ++g_dw404024;
        a_func();
}
```

**Comment by uxmal** [comment]
Implemented in commit 90b583d.
