### ISSUE TITLE
Virus detected?

### ISSUE THREAD

**Issue by thereald3bug** [uxmal/reko#927]
[test1.exe.zip](https://github.com/uxmal/reko/files/5053688/test1.exe.zip)

The file included is in the path: reko-master\subjects\regressions\snowman-79\
It is detected as a virus variant:  Gen:Variant.Ursu.873141  by Bitdefender.  The culprit appears to be the EXE inside that ZIP file.  I have renamed it so it cannot be accidentally executed.   The ZIP password is:  12345

**Comment by uxmal** [comment]
The file is a simple `Hello world` program. It's a false positive by Bitdefender.

**Comment by thereald3bug** [comment]
Submitted to Bitdefender for analysis/exclusion
