### ISSUE TITLE
Unhandled Exception (Commodore 64)

### ISSUE THREAD

**Issue by thereald3bug** [uxmal/reko#928]
Tried to decode a C64 binary, however, it apparently doesn't work.
Also got this exception:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Reko.Environments.C64.C64Basic.<CreateDisassembler>d__4.MoveNext()
   at Reko.UserInterfaces.WindowsForms.Controls.DisassemblyTextModel.GetLineSpans(Int32 count)
   at Reko.UserInterfaces.WindowsForms.Controls.TextViewLayout.VisibleLines(TextViewModel model, Size size, Graphics g, Font defaultFont, StyleStack styleStack)
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.ComputeLayout(Graphics g)
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.ChangeLayout()
   at Reko.UserInterfaces.WindowsForms.Controls.TextView.OnModelChanged(EventArgs e)
   at Reko.UserInterfaces.WindowsForms.LowLevelViewInteractor.OnProgramChanged(Program value)
   at Reko.UserInterfaces.WindowsForms.LowLevelViewServiceImpl.ShowWindowImpl(Program program)
   at Reko.UserInterfaces.WindowsForms.LowLevelViewServiceImpl.ShowMemoryAtAddress(Program program, Address addr)
   at Reko.Gui.TreeNodeDesignerHost.tree_AfterSelect(Object sender, EventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
WindowsDecompiler
    Assembly Version: 0.9.1.0
    Win32 Version: 0.9.1.0
    CodeBase: file:///C:/Program%20Files/jklSoft/Reko/WindowsDecompiler.exe
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Reko.UserInterfaces.WindowsForms
    Assembly Version: 0.9.1.0
    Win32 Version: 0.9.1.0
    CodeBase: file:///C:/Program%20Files/jklSoft/Reko/Reko.UserInterfaces.WindowsForms.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Reko.Gui
    Assembly Version: 0.9.1.0
    Win32 Version: 0.9.1.0
    CodeBase: file:///C:/Program%20Files/jklSoft/Reko/Reko.Gui.DLL
----------------------------------------
Reko.Core
    Assembly Version: 0.9.1.0
    Win32 Version: 0.9.1.0
    CodeBase: file:///C:/Program%20Files/jklSoft/Reko/Reko.Core.DLL
----------------------------------------
Reko
    Assembly Version: 0.9.1.0
    Win32 Version: 0.9.1.0
    CodeBase: file:///C:/Program%20Files/jklSoft/Reko/Reko.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Reko.Environments.C64
    Assembly Version: 0.9.1.0
    Win32 Version: 0.9.1.0
    CodeBase: file:///C:/Program%20Files/jklSoft/Reko/Reko.Environments.C64.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll

**Comment by uxmal** [comment]
Thanks for reporting this. Can you make the offending binary available to me, so I can reproduce the error? You can reach me on https://gitter.im/uxmal/reko if you're not comfortable attaching it to this issue.

**Comment by thereald3bug** [comment]
[test01.zip](https://github.com/uxmal/reko/files/5056523/test01.zip)
Here is the binary you requested.   It's a program called "Arkive"... very old binary compiled with an unknown compiler.

**Comment by uxmal** [comment]
The file is indeed a BIN file, which is to be loaded at `$0800`. At first glance it appears to contain a mix of BASIC and machine language, but no `SYS` directive. The machine languages makes several calls into the BASIC interpreter -- floating point accumulator calls. Perhaps this is BASIC compiled to 6502?

Since there is no `SYS` directive -- the file is a blob of bytes -- attempting to load it as a C64 BASIC program will fail. The failure should be reported however, and not result in the crash you reported. I will make a fix for that in addition to adding some more support for the C64 BASIC entry points being called.

**Comment by thereald3bug** [comment]
I don't know why, but I had not checked before I sent that file.  It appears to have been modified.  The SYS call is no longer present.
I have included 3 screenshots in order (SS-01, SS-02, SS-03) as well as the file I tried to open (again)... this time I checked it first and it is complete.
Different error this time.




________________________________

**Comment by uxmal** [comment]
Could you try sending the unmodified binary again? I didn't see any attached images.

**Comment by thereald3bug** [comment]
Here it is again (I used 7zip to archive everything this time)


________________________________

**Comment by uxmal** [comment]
You should be able to load PRG now. The sample you provided contains some self-modifying code, which Reko is not well equipped to handle yet. You should be able to manually select and mark 6502 procedures in the GUI to get better coverage of the binary.

**Comment by thereald3bug** [comment]
I must be doing something really wrong then.
I am trying to load the program and I get unhandled exceptions when it does supposedly load it... selecting any of the items in the tree causes it...
I try opening it as C64 environment, and C64 BASIC as well as MOS 6502... I used loading addresses of 0 as well as $0801 and 2049(decimal).
Every single combination I tried fails.
When I select C64 environment, MOS6502, load address of 0 I get a different error.  Screenshot included.


________________________________
