### ISSUE TITLE
Reduce simple arithmetic of constant values

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#931]
Background: http://kronotai.com/wordpress/339/testing-decompiler-semantics/
Subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/stress_int_ia32/ia32_elf_base_inst__1_var__no_complex

Current output:
```
word32 inst_10_values_var_0()
{
	return -2802897708 + 2802897708;
}
```

This should be "return 0;".

**Comment by uxmal** [comment]
Agreed, this should be simplified.

**Comment by rfalke** [comment]
Return 0 -> close issue.
