### ISSUE TITLE
Add Nuget Package(s)

### ISSUE THREAD

**Issue by tgiphil** [uxmal/reko#937]
Please add a nuget package(s) for this project.

**Comment by uxmal** [comment]
All the ground work has been done for making a NuGet package for Reko. We're waiting for all reviewers to approve of the changes in #938, after which I will make a formal release of version 0.9.2.0. I hope this will happen within a day or two.

Once the NuGet package is published I will ask you to update your project to use it as a dependency and test everything to make sure it works (as well all know, it already "works on _my_ machine" :)

**Comment by tgiphil** [comment]
Is the package published yet?

**Comment by uxmal** [comment]
I hope to have a release middle of next week

**Comment by uxmal** [comment]
A prerelease version of Reko 0.9.2 has been released on NuGet:
https://www.nuget.org/packages/Reko.Decompiler.Runtime/0.9.2-prerelease
@tgiphil : please update your project to use this NuGet. There have been some refactorings, renamings, etc of the classes that you're interested in, so you may experience a build failure. You can contact me on https://gitter.im/uxmal/reko for assitance if this is the case. Once you've confirmed that everything is working properly, please let me know so I can make a formal 0.9.2 release. Once that release is made, you should be able to upgrade your package reference from `0.9.2-prelease` to `0.9.2`.

Thanks for your patience with this issue.

**Comment by uxmal** [comment]
Well, dang. That package was broken. Try the new one:
https://www.nuget.org/packages/Reko.Decompiler.Runtime/0.9.2-prerelease2

**Comment by uxmal** [comment]
And the final release of this version: https://www.nuget.org/packages/Reko.Decompiler.Runtime/0.9.2

I will close this issue now as completed. If you discover a problem, please don't hesitate to open a new issue.
