### ISSUE TITLE
Show constants without leading zeros

### ISSUE THREAD

**Issue by tgiphil** [uxmal/reko#938]
Example:

Display as: **cmp eax, 0x21** rather than **cmp	eax,00000021** 

Include 0x for hex values, and keep lower case too.

**Comment by uxmal** [comment]
X86 instructions have at least three ways to be rendered: the original Intel format:
`cmp eax,21h`
Various assemblers prefer using `0x` prefixes for hex constants:
`cmp eax,0x21`
Finally, the weird AT&T syntax uses different mnemonics and renders the operands "backwards":
`cmpl 0x21,%eax`

I can implement the first two rather easily, the last one is going to be more work. Will the first one work for you?

**Comment by tgiphil** [comment]
I prefer the second one.

**Comment by uxmal** [comment]
Since this may be required across different architectures, I will make it possible for programmers to choose which output syntax they require. You can then pick the one you prefer in your code.

**Comment by tgiphil** [comment]
Agreed. It should be an option!

**Comment by tgiphil** [comment]
Also: Add a space (or tab) between the operands.

**Comment by uxmal** [comment]
Commit 1fe354e now implements these features. It introduces a new parameter to `MachineInstruction.Render`; its type is `MachineInstructionWriterOptions`. Its three fields are 
* **Syntax**: lets you pick the type of syntax you want. For X86, you can pick `"Intel"` or `"NASM"`. Leaving it blank defaults to Intel. The Intel style has also been improved to better match what Intel has in its manuals. 
* **Flags** same as before the change
* **OperandSeparator** you can now specify the string you wish to inject between operands. The default is `","` 

Usage:
```C#
var options = new MachineInstructionWriterOptions(
    syntax:"Nasm", operandSeparator:", ");
instr.Render(writer, options);
``` 
@tgiphil : you can reach out to me on gitter.im if you have questions.

**Comment by uxmal** [comment]
I wrote the following function to illustrate how to use the new code:
```C#
        public void Frobozz()
        {
            const bool want_detailed_control_of_output = true;
            var arch = new X86ArchitectureFlat32(new ServiceContainer(), "x86");
            var rnd = new System.Random(0x4711);
            var bytes = new byte[256];
            rnd.NextBytes(bytes);
            var mem = new MemoryArea(Address.Ptr32(0x0010_0000), bytes);
            var rdr = mem.CreateLeReader(0);
            var dasm = arch.CreateDisassembler(rdr);
            var options = new MachineInstructionWriterOptions("NASM", operandSeparator: ", ");
            foreach (X86Instruction instr in dasm)
            {
                if (want_detailed_control_of_output)
                {
                    // You can write your own MachineInstructionWriter implementation
                    // and control finely the output details. This will also be more efficient 
                    // as you can collect the output instead of generating lots of little strings.
                    var r = new StringRenderer(instr.Address);
                    instr.Render(r, options);
                    System.Console.WriteLine(r.ToString());
                }
                else 
                {
                    // Convenient, but not efficient.
                    var sInstr = instr.ToString(options);
                    System.Console.WriteLine(sInstr);
                }
            }
        }
```

**Comment by tgiphil** [comment]
Thanks!

**Comment by tgiphil** [comment]
Thanks!
