### ISSUE TITLE
5 unit tests failed

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#94]
Following tests failed:

Reko.UnitTests.Analysis.DataFlowAnalysisTests2.Dfa2_Simple:
  Expected string length 195 but was 237. Strings differ at index 75.
  Expected: "..._entry:\r\n\t// succ:  l1\r\nl1:\r\n\tMem3[0x00010008:word32] = Me..."
  But was:  "..._entry:\r\n\t// succ:  l1\r\nl1:\r\n\tword32 r1_1 = Mem0[0x0001000..."
  ----------------------------------------------------^

Reko.UnitTests.Analysis.DataFlowAnalysisTests2.Dfa2_StackArgs:
  Expected string length 207 but was 204. Strings differ at index 75.
  Expected: "..._entry:\r\n\t// succ:  l1\r\nl1:\r\n\tMem6[0x00010008:word32] = dw..."
  But was:  "..._entry:\r\n\t// succ:  l1\r\nl1:\r\n\tword32 r1_5 = dwArg04 + dwAr..."
  ----------------------------------------------------^

Reko.UnitTests.Analysis.RegisterPreservationTests.Regp_Factorial:
  Expected string length 3 but was 806. Strings differ at index 0.
  Expected: "@@@"
  But was:  "// fact\r\n// Return size: 0\r\nvoid fact()\r\nfact_entry:\r\n\tdef fp..."
  -----------^

Reko.UnitTests.Structure.SimpleStructureTests.StrReg00006:
  File differs on line 135
  Expected string length 47 but was 347. Strings differ at index 1.
  Expected: "\tMem336[Mem135[esi_118:word32]:word16] = ax_317"
  But was:  "\t\tuses: ax_327,bl_304,bp_301,C_333,cx_306,di_305,dwLoc04_4,dw..."
  -------------^

Reko.UnitTests.Typing.DataTypeBuilderTests.DtbFnPointerMock:
  File differs on line 9
  Expected string length 7 but was 13. Strings differ at index 1.
  Expected: "\treturn"
  But was:  "\t\tuses: pfn_0"
  -------------^

**Comment by uxmal** [comment]
These were accidentally committed with their [Ignore] attribute commented out or removed. I'm not in a place where I can fix this so for the while just disable them with [Ignore ] attributes.

**Comment by ptomin** [comment]
I have disabled them and created pull request #95

**Comment by uxmal** [comment]
These are now being ignored until further notice. They will be uncommented once `DataFlowAnalyzer2` is capable of handling recursion.
