### ISSUE TITLE
Amiga lib function(s) return(s) something

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#941]
I'm looking though the changes made by `--aggressive-branch-removal` and I came across https://github.com/rfalke/decompiler-subjects/tree/master/from_aminet/albion_demo/demo/m68k_amiga:

```
Eq_3 fn000013D2(Eq_3 d0, Eq_3 d1, Eq_3 a1, Eq_3 a2, Eq_3 a3)
{
	CreateIORequest(d0, 48);
	if (true)
		return 48;
	word32 a0_60;
	return fn0000141A(25, d1, d0, a1, a2, a3, out a0_60);
}
```

Asm:
```
fn000013D2 proc
        movem.l d1/a0-a1,-(a7)
        movea.l d0,a0
        moveq   #$30,d0
        move.l  a6,-(a7)
        movea.l $00000004,a6
        jsr.l   -$028E(a6)
        movea.l (a7)+,a6
        tst.l   d0
        bne     $000013F4

l000013EC:
        moveq   #$19,d0
        jmp.l   $0000141A

l000013F4:
        movem.l (a7)+,d1/a0-a1
        rts
```

So reko things that `jsr.l   -$028E(a6)` aka CreateIORequest does return void and therefore `d0` is not overwritten. http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node0344.html says that `CreateIORequest` returns something.

I'm not sure which other library functions are affected.

**Comment by uxmal** [comment]
It may be a problem with the Amiga metadata files. The `exec.funcs` file, provided by @nemerle, doesn't specify if functions return anything or not. Perhaps Reko needs another source of metadata for AmigaOS?

**Comment by rfalke** [comment]
I didn't find a source which is easy to parse. One option is going to  http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_2._guide/node0012.html, download the files for each library and parse them. Attached is an intermediate result which may be helpful.

[amiga_returns_something.txt](https://github.com/uxmal/reko/files/5237131/amiga_returns_something.txt)

A general note: it is more defensive to assume that all library functions return something. In the worst case you end up with some asm like:
```
d0=42;
jsr OwnBlitter(); // takes no parameters and returns void
putchar(d0+1);
```
and the decompiler things `putchar(OwnBlitter()+1)`. But the asm code is bad in the first place since d0 is a scratch register. So the risk of such case should be minimal.

**Comment by uxmal** [comment]
I'm not intimately familiar with the ABI on AmigaOS. Is it the case that D0 is always the return register? Or could A0 sometimes have been used to return values?

**Comment by uxmal** [comment]
I've implemented your suggestion of making D0 the default return register if nothing else is specified. I see some improvements in the Reko test suite, perhaps you'll see the same in `decompiler-subjects`.

**Comment by rfalke** [comment]
From http://amigadev.elowar.com/read/ADCD_2.1/Libraries_Manual_guide/node000F.html:
> The Amiga library functions are set up to accept parameters in certain
68000 registers and always return results in data register D0.

From http://teleinfo.pb.edu.pl/krashan/new/amiga-assembler-and-system:
> A convention used throughout the whole AmigaOS treats CPU registers D0, D1, A0 and A1 as scratch registers. Every OS function is allowed to change them and leave at unspecified values (D0 register usually contains the function result).
