### ISSUE TITLE
Assumes wrongly that functions return void (because of partial decompile?)

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#943]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/stress_int_x64/x64_elf_base_inst__1_var__no_complex/subject.exe

Output:
```
void main()
{
	inst_0_values_var_0();
	inst_0_flags_var_0();
	inst_1_values_var_0();
...
	inst_44_values_var_0();
	inst_44_flags_var_0();
	inst_45_values_var_0();
}
```

Expected: return values of all 840! function calls are added together and compared to 0.

**Comment by uxmal** [comment]
Reko was missing some of the X86 instructions, so it was treating them as `invalid`. This causes the procedure that contains the invalid procedure to have a "noreturn" quality. Implementing the missing instructions made the error go away.

**Comment by rfalke** [comment]
Thanks. Must better now. I'm now waiting for #931.
