### ISSUE TITLE
Extract character in ARM decoding

### ISSUE THREAD

**Issue by tgiphil** [uxmal/reko#944]
````
Output:
00000008 08 10 9e e4                     ldr r1, [lr], #&8
0000000c 0c 20 9e e4                     ldr r2, [lr], #&C
````

The & sign should be removed.

**Comment by uxmal** [comment]
The `&` is for "hexadecimal" in the ARM assembly language; it's needed for `#&C`. Are you using a different tool that emits different outputs.

**Comment by tgiphil** [comment]
The ARM instruction set manual uses this format:

BIC R0,R0,#0x1F
TEQ Rc,#127

I didn't find a single example of & in the manual.

**Comment by tgiphil** [comment]
ODA Disassembler:

ldr r1, [lr], #8
ldr r2, [lr], #12
