### ISSUE TITLE
MacOS Classic (Master) - TRAPs rewritten in RTL including stack pointer 4 byte increment issue 

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#951]
I have noticed a number of TRAPs when rewritten in RTL have included a stack pointer increment of 4. This is an existing issue just identified. In my sample file LinkIIgs, the procedure print_time currently produces the output of:
word32 print_time(word32 dwArg04, ptr32 & d3Out).

In this case the TRAP Secs2Date RTL generated
    Secs2Date(a1, d0)
    a7 = a7 + 0x04

When processed through valuepropergator you can see that a7_29 = fp - 0x1E<32> points to the value for a3 on the stack, instead of d3.

print_time_entry:
	def fp
	def a5world
	def a6
	def a4
	def a3
	def d3
	a7_2 = fp
	a5_4 = a5world
	// succ:  l00104186
l00104186:
	a7_5 = fp - 4<32>
	Mem7[fp - 4<32>:word32] = a6
	a6_8 = fp - 4<32>
	a7_9 = fp - 0x16<32>
	a7_10 = fp - 0x1A<32>
	Mem12[fp - 0x1A<32>:word32] = a4
	a7_13 = fp - 0x1E<32>
	Mem15[fp - 0x1E<32>:word32] = a3
	a7_16 = fp - 0x22<32>
	Mem18[fp - 0x22<32>:word32] = d3
	a3_19 = a5world + -2370<i32>
	a4_20 = Mem18[fp + 4<32>:word32]
	a1_21 = fp + 0xFFFFFFEA<32>
	a0_22 = fp + 0xFFFFFFEA<32>
	v10_23 = Mem18[0x0000020C<p32>:word32]
	Mem24[fp + 0xFFFFFFEA<32>:word32] = v10_23
	d0_25 = Mem24[fp + 0xFFFFFFEA<32>:word32]
	CVZN_26 = cond(d0_25)
	a1_27 = fp + 0xFFFFFFEE<32>
	a0_28 = fp + 0xFFFFFFEE<32>
	Secs2Date(fp + 0xFFFFFFEE<32>, d0_25)
	a7_29 = fp - 0x1E<32>
 
Exit section of print_time d3_143 is equivalent to a5_30 + -2372<i32>, which shouldn't be and causes d3out to be generated as output from the procedure and is a side effect of the stackpointer being incremented by 4 when it should not have been.

	a7_133 = fp - 0x22<32>
	Mem135[fp - 0x22<32>:word32] = a5_30 + -2372<i32>
	a7_136 = fp - 0x26<32>
	Mem137[fp - 0x26<32>:word32] = a5_30 + -396<i32>
	d0_138 = fprintf(Mem137[fp - 0x26<32>:(ptr32 (struct "FILE"))], Mem137[fp - 0x22<32>:(ptr32 char)], 0<32>)
	d0_140 = Mem137[fp + 0xFFFFFFEA<32>:word32]
	CVZN_141 = cond(d0_140)
	v46_142 = fp + 0xFFFFFFDE<32>
	d3_143 = Mem137[fp + 0xFFFFFFDE<32>:word32]
	v46_144 = fp + 0xFFFFFFE2<32>
	a3_145 = Mem137[fp + 0xFFFFFFE2<32>:word32]
	v46_146 = fp + 0xFFFFFFE6<32>
	a4_147 = Mem137[fp + 0xFFFFFFE6<32>:word32]
	v46_148 = fp + 0xFFFFFFEA<32>
	a7_149 = fp - 4<32>
	a6_150 = Mem137[fp - 4<32>:word32]
	a7_151 = fp
	return

**Comment by uxmal** [comment]
I found this suspicious line:
https://github.com/uxmal/reko/blob/4ce3216f28562fd20ec33d05c51d94b30fd9924b/src/Environments/MacOS/Classic/InlineCodeInterpreter.cs#L135

If you change the `= 4` to `= 0`, what happens?

**Comment by uxmal** [comment]
Indeed, the signature of `print_time` changed to:
```C
// 00104186: Register Eq_4370 print_time(Stack Eq_11 dwArg04)
// Called from:
//      main
//      Get_Input
Eq_4370 print_time(Eq_11 dwArg04)
```
Could you change the 4 to 0 on your machine and test to see what results?

**Comment by gbody** [comment]
Yes that fixed the issue. I will have a look through the InlineCodeInterpreter

**Comment by uxmal** [comment]
I think I'll close this issue. There was a redundant +4 that caused the error.
