### ISSUE TITLE
x86 decoding issue with roundss & roundsd

### ISSUE THREAD

**Issue by tgiphil** [uxmal/reko#952]
66 0f 3a 0a d2 03 	roundss xmm2, xmm2, 3

is decoding as:

66 0f 3a 0a                     illegal
d2 03                           rol [ebx], cl

Similar issue with roundsd.

**Comment by uxmal** [comment]
Thanks for reporting this. I have a fix on my machine. Do you require a new NuGet release (this would make it 0.9.3)?

**Comment by uxmal** [comment]
This has been pushed to github. Let me know if you need a new NuGet release.

**Comment by tgiphil** [comment]
Thanks for the quick fix! I can wait for the next nuget release.
