### ISSUE TITLE
x64 build under VS2019 fails due to ArmNative files not found

### ISSUE THREAD

**Issue by gbody** [uxmal/reko#957]
Building x64 under debug or release results in 

Debug x64
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\path\reko\src\Native\build\x64\Debug\ArmNative\ArmNative.pdb" because it was not found.	UnitTests	C:\path\reko\src\UnitTests\UnitTests.csproj	1304	
Error		Could not copy the file "C:\path\reko\src\Native\build\x64\Debug\ArmNative\ArmNative.dll" because it was not found.	UnitTests	C:\path\reko\src\UnitTests\UnitTests.csproj	1304	

Release x64
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\path\reko\src\Native\build\x64\Release\ArmNative\ArmNative.dll" because it was not found.	CmdLine			
Error		Could not copy the file "C:\path\reko\src\Native\build\x64\Release\ArmNative\ArmNative.pdb" because it was not found.	CmdLine

**Comment by uxmal** [comment]
What happens if you build the `NativeProxy` project? AppVeyor and Travis-CI are both reporting no errors.

**Comment by uxmal** [comment]
I just updated to VS2019 v16.7.6, and I'm now also seeing this error. It appears as a cmake configuration error, but I'm not sure how to solve it yet. Maybe @smx-smx, the CMake expert, can figure it out?

**Comment by uxmal** [comment]
...well the solution was easy: rebuild the solution completely in VStudio : `Build` > `Rebuild Solution`
