### ISSUE TITLE
Can't decompile RISC-V ELFs?

### ISSUE THREAD

**Issue by WildCryptoFox** [uxmal/reko#958]
Hello world. I'm currently looking for a RISC-V decompiler. Reko claims to be one, but I've reached an unimplemented error when trying to decompile a RISC-V elf.

[`Relocator for architecture EM_RISCV not implemented yet`](https://github.com/uxmal/reko/blob/master/src/ImageLoaders/Elf/ElfLoader.cs#L406)

Can I get an estimation for how much work would be involved in adding this support? Is anyone already working on it?

Thank you.

**Comment by uxmal** [comment]
Thanks for reporting this. I will look into the issue when I'm back in front of my development rig on Monday. I'm surprised by the error, as there are RiscV ELF binaries in Reko's regression suite that load successfully. Would it be possible to provide a binary that causes the issue? You can contact me on a private channel on gitter.im if need be.

**Comment by WildCryptoFox** [comment]
I tried to decompile these [`.elf` files](https://github.com/pine64/bl602-re/tree/master/blobs) built from [the SDK](https://github.com/pine64/bl_iot_sdk) for the BL604, a RISC-V based, more powerful alternative to the ESP32 et al. I don't think these files belong in your regression suite, only something like a hello world built for embedded contexts (Note: not a Linux target).

**Comment by uxmal** [comment]
I just verified that this was a bug in the Reko ELF loader. It didn't handle loading 32-bit ELFs. This has been fixed. 

I ran Reko on some of the ELF files, and it's reporting quite a few reserved instructions. Since the RiscV ISA is still somewhat of a moving target, I will investigate the coming week if these are now officially supported instructions and if so I will implement decoders and rewriters for them; that doesn't take long. However, if the instructions are extensions to the core ISA, you'll need to provide me with the specs for those extensions.

Look towards a commit in the coming days with support for the ELF format and such RiscV instructions that I can find in the ISA document (I'm using the latest specs from [here](https://github.com/riscv/riscv-isa-manual/releases).

**Comment by WildCryptoFox** [comment]
As far as we know, all instructions should be from the standard RV32IMAFC.

**Comment by WildCryptoFox** [comment]
Fixed? I don't see new commits?

**Comment by uxmal** [comment]
I've cleaned up the Risc-V disassembler and rewriter, and fixed the issues in the ELF loader. As I run the samples you provided, I'm noticing that Reko is failing to handle the indirect jumps generated by compiling `switch` statements to Risc-V. I will track that in a separate issue.

**Comment by WildCryptoFox** [comment]
Thanks. It seems to make progress but it reached the limits of my virtual machine. (Which I decided to use because I didn't want to debug a mono build error.) How resource intensive is Reko on the usual binary? It seemed to need more than a few GiB, before crashing due to insufficient memory.

Side note; probably worth its own issue but I haven't looked into it more. Static ELFs, even on x64, don't seem supported. `cc -static hello.c -o hello` I tried this `-static` after Reko failed to decompile the main function -- of the trivial stdio-printf hello world -- but did think it was done, presenting the start function in C.

**Comment by uxmal** [comment]
What I'm seeing is about 1 kiB for each byte in the binary; so an 8 MiB binary may consume 8 GiB. 

If you find other issues (like the one you mention) please report it so I can investigate. Reko should be able to load static ELFs just fine.

**Comment by WildCryptoFox** [comment]
I'm currently waiting for it to decompile the smallest of these ELFs; 1.3M. So far running for 20 minutes, consuming approx 3GiB of RAM, and still rising slowly. Most of this time in the "Transforming datatypes" stage.

**Comment by WildCryptoFox** [comment]
*sigh* after it finished; just as I was about to look through the results --- the virtual machine crashed! Not sure why... @uxmal Would you be okay to run the 3 .elf files through reko and upload the results; when you're done with any fixes? If not, I'll wait until you're ready before trying again. Thanks again.

**Comment by uxmal** [comment]
I can take a peek later tonight.

**Comment by uxmal** [comment]
[bl602_demo_at.reko.zip](https://github.com/uxmal/reko/files/5477100/bl602_demo_at.reko.zip)
[bl602_demo_wifi.reko.zip](https://github.com/uxmal/reko/files/5477101/bl602_demo_wifi.reko.zip)
[sdk_app_ble_sync.reko.zip](https://github.com/uxmal/reko/files/5477106/sdk_app_ble_sync.reko.zip)

**Comment by WildCryptoFox** [comment]
Thank you @uxmal !

**Comment by WildCryptoFox** [comment]
Hmm.. Bulk report from these `.zip`s ;)

```
$ grep -ir 'please report this issue' | wc -l
2986
```
