### ISSUE TITLE
x87: Doesn't compute expressions which can be computed

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#961]
Subject: https://github.com/rfalke/decompiler-subjects/blob/master/from_holdec/i386_x87_fpu/ia32_elf

Reko can compute `fabs(-1.0)` or `(1.0 + 1.0) + 1.0` or `cos(3.14159265358979 / ((1.0 + 1.0) + 1.0))` but doesn't. This makes the output harder to understand.

Maybe it is a design decision to not compute floating point expressions.

**Comment by uxmal** [comment]
In general, it's unsafe to simplify floating point arithmetic, as can be learned from many places. Reko intentionally doesn't simplify floating point arithmetic to avoid creating subtle errors. If there is enough interest for it, I suppose an `--unsafe-math-optimizations` could be added.

**Comment by rfalke** [comment]
Hmm this is a new topic for me. But shouldn't evaluating in the original order be ok? So if `(1.0/3.0)+(2.0/3.0)` is first evaluated to `0.33..+0.66..` and than to `0.99..` it should be ok. What would not be ok if a transformation is applied. So `(1.0/3.0)+(2.0/3.0)` is transformed to `(1.0+2.0)/3.0` which than evaluated to `1.0` is not ok. How far of am I?

I wonder if there are some scientific papers out there what can be done safely and what not.
