### ISSUE TITLE
Should detect/model double parameter as such

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#981]
Subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/i386_call_type_promotion/ia32_elf

print_double_as_hex should only have one parameter of type double (aka real64) but not

```
void print_double_as_hex(uint32 dwArg04, uint32 dwArg08)
```

**Comment by uxmal** [comment]
I'm not sure what can be done here. I may be dense, but AFAIK, nowhere in the machine code for `print_double_as_hex` is there any evidence that the 8 bytes passed as arguments are supposed to be treated as a single unit, let alone a double. The body of the function consists of many different slices of the data on the stack, none of which give any indication of floating point values. Neither does the `printf` format string have any clue that a double is being referred.
