### ISSUE TITLE
Unnecessary cast

### ISSUE THREAD

**Issue by rfalke** [uxmal/reko#982]
Subject: https://github.com/rfalke/decompiler-subjects/tree/master/from_holdec/i386_call_type_promotion/ia32_elf

Output:
```
void print_char(byte bArg04)
{
	printf("got a char '%c'\n", (char) (word32) bArg04);
}
```

A byte is cast to a word32 and then to a char again?!

**Comment by uxmal** [comment]
Fixed in b6f19a4.
