### ISSUE TITLE
Crash: Opening Project Global variables before scan binaries

### ISSUE THREAD

**Issue by Elthial** [uxmal/reko#986]
If a Project Global variables tab is open when clicking the scan binaries button then application will freeze and crash.

This can occur when user is reviewing a previous project, fresh projects are unlikely to encounter due to likely no global variables created yet. Scan Binaries still works if global variables page is closed when clicking.

Error:
System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'
>	Reko.UserInterfaces.WindowsForms.dll!Reko.UserInterfaces.WindowsForms.Controls.MixedCodeDataModel.CountDisassembledLines(Reko.Core.ImageMapBlock bi) Line 143	C#

**Comment by uxmal** [comment]
Commit f990ca0 should resolve this race condition.
