### ISSUE TITLE
UserSignatureBuilder does not resolve type references

### ISSUE THREAD

**Issue by ptomin** [uxmal/reko#99]
e.g. if CSignature = "BYTE testFunc(BYTE a, BYTE b)" then UserSignatureBuilder throws CParserException exception. Type BYTE was not found but it was defined in windows32.xml.

I think, UserSignatureBuilder should pass type defintions were obtained from *.xml files to CParser
(Typedefs property of ParserState should be set)

**Comment by uxmal** [comment]
Good catch. Reko should first load all type definitions, and then use them to resolve type references.

**Comment by ptomin** [comment]
My suggestion to fix it : 8afa035

**Comment by uxmal** [comment]
Next problem is that the `ProcedureSerializer` in use by `UserSignatureBuilder` is returning, on Win32,  `LPSTR` as a typedef of `<unknowntype>`, where it should be `typedef CHAR * LPSTR`. Working on it...

**Comment by ptomin** [comment]
Yes, I known this problem. New constructor of TypeLibraryLoader should be added so that it can get predefined types

**Comment by uxmal** [comment]
The `TypeLibraryLoader` class needs to be altered, indeed. It should be more like an "augmenter", which takes as input a `TypeLibrary`, which may or may not already contain types, and then sucks in the contents of the *serialized* type library and adds types and functions to the `TypeLibrary` that was passed in. Watch this space for more news....

**Comment by uxmal** [comment]
OK, Pavel, please try the master branch after commit 56e0fac to see if this issue has finally been resolved.

**Comment by ptomin** [comment]
1. UserSignatureBuilder works correctly with type references. Thanks!
2. Should unit test(s) be added for new functionality( Now CreateProcedureSerializer() returns procedure serialised populated with the types defined by the platform )?
3. What about user-defined (not system) types? Could user add them to project?

**Comment by uxmal** [comment]
1. Glad to finally have knocked this out of the park!
2. If you identify the need for unit tests, don't hesistate to write them and submit PR's  <g>
3. There is a feedback loop here. A user runs reko on a binary and it discovers structures. Today, these are imginatively called `Eq_1`, `Eq_2` etc. At the end of the decompilation run, user should be able to edit the names and fields of the data structures, whereupon a restart of reko should pick up the new names. 

There should be a way for a user to add custom data types to the project, the question is how. Adding a C header file should be easy enough; reko has an ANSI C compiler to handle that. Is that enough? Does reko need a full blown source code editor, or something in between.

 In any case, this belongs in a separate issue. I will close this now and open a separate issue for 3. above.
