### ISSUE TITLE
Why does the ELFLoader ignore the base address of the ELF file itself?

### ISSUE THREAD

**Issue by twischer** [uxmal/reko#993]
When I am opening an ELF file always the DefaultAddress (0x8048000) is used. It looks like the addresses of the symbols in the ELF file are remapped. My original base address is 0x40000000. This is also the address I see when I am checking the ELF file with xtensa-lx106-elf-nm.

**Comment by uxmal** [comment]
This is a bug in the ELF loader. Thanks for reporting it. Hope to fix this in a week.

**Comment by uxmal** [comment]
I spoke too soon; it does appear as the base address is computed as the minimum of the program segment addresses, which should be respected -- unless you are loading an object file; is this the case? Or are you attempting to load a shared library at a specific address? 

Would you be able to provide me with the binary so I can take a look at the problem? You can reach out to me via https://gitter.im/uxmal/reko or the discord server at https://discord.gg/9PMWVxEjqr. Alternatively, could you execute the following commands: `readelf -hlSs <yourfile>` and report the output.

**Comment by twischer** [comment]
> it does appear as the base address is computed as the minimum of the program segment addresses

For me it looks like this would be
```
  Entry point address:               0x40000000
```
> Would you be able to provide me with the binary so I can take a look at the problem?

[bootrom.elf.tar.gz](https://github.com/uxmal/reko/files/5844552/bootrom.elf.tar.gz)
This elf file was generated with the make file from https://github.com/jcmvbkbc/esp-elf-rom.

> Alternatively, could you execute the following commands: readelf -hlSs <yourfile> and report the output.

The output is contained in [bootrom.elf.txt](https://github.com/uxmal/reko/files/5844565/bootrom.elf.txt)

**Comment by uxmal** [comment]
Again, thanks for reporting this. The root cause was the Reko ELF linker not respecting the section addresses, as you reported.
