### ISSUE TITLE
Analyze dataflow fails with "An internel error occurred. The method or operation is not implemented."

### ISSUE THREAD

**Issue by twischer** [uxmal/reko#995]
I am using a similar elf file as attached in https://github.com/uxmal/reko/issues/993. It only contains additional symbols.
[bootrom.elf.tar.gz](https://github.com/uxmal/reko/files/5881884/bootrom.elf.tar.gz)
Without this additional symbols it was working fine.

I am using version f990ca017d on Linux.

**Comment by uxmal** [comment]
Commi 65cc329 addresses this issue.
