### ISSUE TITLE
external dir missing Msagl subdirectory

### ISSUE THREAD

**Issue by JRRuzinok** [uxmal/reko#998]
I just cloned the repo and attempted to build with VS2019 (CMake and WiX installed) and the build failed. Traced down to the 3 DLL's being referenced from reko/external/Msagl (Gui.csproj references all 3, other projects reference some of them) not in the repo. After obtaining the latest Msagl NuGets and extracting the 3 required files the build was successful. I recommend adding these to the repo.

**Comment by uxmal** [comment]
Thanks for reporting this. Msagl is now available as a NuGet, and I could've sworn I'd incorporated references to it. I will fix the build shortly.

**Comment by uxmal** [comment]
I've corrected `Gui.csproj` to no longer refer to the deleted assembly. Again, thanks for reporting tis issue.
